### ISSUE TITLE
Is this repo up to date?

### ISSUE THREAD

**Issue by erikd** [haskell/containers#1012]
The latest version latest version in this repo is [0.6.8](https://github.com/haskell/containers/blob/master/containers/containers.cabal), but the latest on Hackage is  [0.7](https://hackage.haskell.org/package/containers).

Can this repo please be updated? Both the code changes and the tags need to be updated.

**Comment by erikd** [comment]
Have mailed the libraries mailing list: https://mail.haskell.org/pipermail/libraries/2024-July/031664.html

**Comment by treeowl** [comment]
There was a slight git screwup and the version bump needs to be merged from a branch, with changelog conflicts and such resolved. Do you have time to take a look at doing that? If not, I'll try to do it in the next two days.

**Comment by erikd** [comment]
Thanks @treeowl . If you give me some links, I can take a look.

**Comment by meooow25** [comment]
There seems to be two issues here.

1. A tag for the 0.7 version, already exists: https://github.com/haskell/containers/releases/tag/v0.7. @erikd does this work for you?
2. Updating the cabal file on master to 0.7 because it still says 0.6.8. @treeowl had a PR for this (#994). I can take a shot at updating it.

**Comment by erikd** [comment]
Sorry, I needed to do `git pull --tags` to get the required tag :facepalm:

**Comment by erikd** [comment]
The tag does not build with `ghc-9.10.1` and requires:
```
diff --git a/containers-tests/containers-tests.cabal b/containers-tests/containers-tests.cabal
index 5d3ea2b8..b58374e5 100644
--- a/containers-tests/containers-tests.cabal
+++ b/containers-tests/containers-tests.cabal
@@ -37,7 +37,7 @@ common deps
   build-depends:
       array    >=0.4.0.0
     , base     >=4.10    && <5
-    , deepseq  >=1.2     && <1.5
+    , deepseq  >=1.2     && <1.6
     , template-haskell
 
 common test-deps
@@ -54,7 +54,7 @@ common benchmark-deps
   import: deps
   build-depends:
       containers-tests
-    , deepseq           >=1.1.0.0 && <1.5
+    , deepseq           >=1.1.0.0 && <1.6
     , tasty-bench       >=0.3.1   && <0.4
 
 -- Copy of containers library,
 ```

**Comment by erikd** [comment]
Closing this as resolved.
