### ISSUE TITLE
Consider maintaining the x.y.z.a versioning

### ISSUE THREAD

**Issue by ulysses4ever** [haskell/containers#1013]
I inherited a package that uses the caret-style bounds and depends on containers ([`rere`](https://hackage.haskell.org/package/rere)). In the cabal file it had:

```
    , containers    ^>=0.4.0.0 || ^>=0.5.0.0 || ^>=0.6.0.1
```

I got a request to allow containers 0.7, and I thought it should be as easy as changing this to 

```
    , containers    ^>=0.4.0.0 || ^>=0.5.0.0 || ^>=0.7.0.0
```

but it doesn't build that way: 0.7 doesn't get picked up and if i specify `--constraint="containers ^>=0.7.0.0"` to `cabal build`, the solver fails with:

```
❯ cabal build --dry --constraint="containers ^>=0.7.0.0"
Warning: The package list for 'hackage.haskell.org' is 25 days old.
Run 'cabal update' to get the latest list of available packages.
Resolving dependencies...
cabal: Could not resolve dependencies:
[__0] trying: rere-0.2.0.1 (user goal)
[__1] next goal: containers (dependency of rere)
[__1] rejecting: containers-0.7/installed-7628 (conflict: rere =>
containers^>=0.4.0.0 || ^>=0.5.0.0 || ^>=0.6.0.1 || ^>=0.7.0.0)
[__1] skipping: containers-0.7 (has the same characteristics that caused the
previous version to fail: excluded by constraint '^>=0.4.0.0 || ^>=0.5.0.0 ||
^>=0.6.0.1 || ^>=0.7.0.0' from 'rere')
[__1] rejecting: containers-0.6.8, containers-0.6.7, containers-0.6.6,
...
(constraint from command line flag requires ^>=0.7.0.0)
[__1] fail (backjumping, conflict set: containers, rere)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: containers, rere
```

The reason for this is that `0.7` < `0.7.0.0` (the versions are compared lexicographically).

Given that `containers` historically strictly followed the `x.y.z.a` numbering scheme, it would make sense to continue using it, perhaps? Arguably, this is a Cabal quirk, but in the interest of the wider audience who may unintentionally restrict a `0.x` version, it may be desirable to stick to the `x.y.z.a` precedent going forward.

**Comment by treeowl** [comment]
Whichever we do here, someone is sure to be annoyed, right?

**Comment by ulysses4ever** [comment]
I don't think so. If, say, 0.7.0.0 is on Hackage. Using `0.7` in my cabal file and building with  `--constraint="containers ^>=0.7"` will succeed (as well as with `0.7.0.0` of course) by picking up 0.7.0.0. This is allowed, again, because 0.7 < 0.7.0.0 and they are not too far away so that ^ is happy (I think).

**Comment by treeowl** [comment]
I'm happy to do that if there are no objections.

**Comment by Bodigrim** [comment]
@ulysses4ever just put `containers >=0.4 && <0.8`, eh?

> Given that `containers` historically strictly followed the `x.y.z.a` numbering scheme, it would make sense to continue using it, perhaps?

It did not.

**Comment by Bodigrim** [comment]
(I'm not a maintainer here)

**Comment by mitchellwrosen** [comment]
I think `^>= 0.7` is the way to go here (not `^>= 0.7.0.0`). And if you require a particular minor version you can always say so, e.g. `^>= 0.6.8`.
