### ISSUE TITLE
Data.Map.Strict.mergeWithKey does not force the result of the combining function

### ISSUE THREAD

**Issue by meooow25** [haskell/containers#1022]
`mergeWithKey` should force `x'`:

https://github.com/haskell/containers/blob/96a8decab565da6b6e70031cd16e128751a27f17/containers/src/Data/Map/Strict/Internal.hs#L1251-L1253

Found in #1021

---

IntMap seems fine

https://github.com/haskell/containers/blob/96a8decab565da6b6e70031cd16e128751a27f17/containers/src/Data/IntMap/Strict/Internal.hs#L760-L761

**Comment by treeowl** [comment]
Good catch. I wonder if that's been there forever or if I accidentally introduced it with the merge algorithm change.... If it was my fault, I'm sorry. Fortunately, almost no one uses this hideous function.

**Comment by meooow25** [comment]
Looks like it's been there since the function was introduced.

> Fortunately, almost no one uses this hideous function.

We can fix it now, but do we plan to remove it at some point?

**Comment by treeowl** [comment]
I tried a few years ago, but one or two people opposed it.

**Comment by meooow25** [comment]
Oh well, at least it has good documentation explaining how it is unsafe.

**Comment by treeowl** [comment]
We should also document that the function doesn't crack open the replacement trees to force values within.
