### ISSUE TITLE
Link to "Efficient sets: a balancing act" is rotten

### ISSUE THREAD

**Issue by Bodigrim** [haskell/containers#1034]
https://github.com/haskell/containers/blob/2ad4ea3123d0d5116d02e8e47f0210117ac256a0/containers/src/Data/Set.hs#L51-L53

I cannot find anything relevant at https://groups.csail.mit.edu/mac/projects/mac/

**Comment by treeowl** [comment]
Is this the right one? https://groups.csail.mit.edu/mac/users/adams/BB/index.html

**Comment by meooow25** [comment]
We could use DOI URLs to make it more resistant to bitrot. https://doi.org/10.1017/S0956796800000885.  
The downside is that it will only point to the paper. In contrast, https://groups.csail.mit.edu/mac/users/adams/BB/index.html has some more useful information such as source code by the author (but it might rot again in the future).

**Comment by treeowl** [comment]
How about both? I like both.
