### ISSUE TITLE
Export Set intersections and Intersection

### ISSUE THREAD

**Issue by meooow25** [haskell/containers#1038]
#756 added these two definitions

https://github.com/haskell/containers/blob/028e187120c2cd6ed9f74d67a03bec1431f74be3/containers/src/Data/Set/Internal.hs#L897-L911

but they were never exported from `Data.Set`.

We should export them, but there is an opportunity for improvement today. `base-4.18` got [`Foldable1`](https://hackage.haskell.org/package/base-4.18.0.0/docs/Data-Foldable1.html), so we could change `intersections` to be `(Ord a, Foldable1 f) => f (Set a) -> Set a`.

And whatever we do for Set we should also do for IntSet.

**Comment by meooow25** [comment]
Ah, there's something to be considered about `IntSet`. Unlike `Set`, we can have a monoid because `mempty` is well defined here (`fromList [0..]`). But this set cannot be constructed in practice because it is too large. So I think we should not have the instance, though technically it could be defined correctly.

If we end up implementing #999 it will be possible to construct this set and we can revise this decision.

**Comment by alexfmpe** [comment]
> Unlike Set
> But this set cannot be constructed in practice because it is too large.

I mean, isn't this the same issue with the Set monoid for intersections? 
One could have `instance (Finite a, Ord a) => Monoid (Set a)` and the same "small enough" concern applies.

**Comment by meooow25** [comment]
Sure, you could say that. But there is no `class Finite` in `base`, which makes it less of a concern for `containers`.
