### ISSUE TITLE
Offer type classes that abstract container manipulations.

### ISSUE THREAD

**Issue by eownerdead** [haskell/containers#1045]
Many packages provide almost the same API as this, like [unordered-containers](https://hackage.haskell.org/package/unordered-containers) and [enummapset](https://hackage.haskell.org/package/enummapset). It would be good if we could manipulate these in the same manner.

**Comment by eownerdead** [comment]
Roughly, I want a class with all of the functions that Data.Map and Data.HashMap commonly provides.
Sorry for the poor descriptions...

**Comment by Bodigrim** [comment]
What happens if the intersection of API changes? Adding a new type class member is a breaking change.

**Comment by eownerdead** [comment]
@Bodigrim Maybe splitting class members into some classes?

**Comment by Bodigrim** [comment]
@eownerdead have you seen https://hackage.haskell.org/package/mono-traversable?

**Comment by eownerdead** [comment]
Sorry, I didn't seen it. That's what I wanted...

**Comment by meooow25** [comment]
> Roughly, I want a class with all of the functions that Data.Map and Data.HashMap commonly provides.

Well, _why_ do you want it?

Anyway, if mono-traversable satisfies your requirements that's good to hear.
