### ISSUE TITLE
seq-properties build failures with `ghc-9.10.1` and later

### ISSUE THREAD

**Issue by erikd** [haskell/containers#1051]
Running the tests as `cabal test seq-properties` with different versions of GHC I get:

* `ghc-9.6.4` - Pass
* `ghc-9.8.2` - Pass
* `ghc-9.10.1` - Link failure

```
> cabal test seq-properties
Build profile: -w ghc-9.10.1 -O1
In order, the following will be built (use -v for more details):
 - containers-tests-0 (test:seq-properties) (cannot read state cache)
Preprocessing test suite 'seq-properties' for containers-tests-0...
Building test suite 'seq-properties' for containers-tests-0...
[1 of 1] Compiling Main             ( tests/seq-properties.hs, /home/erikd/Git/Haskell/containers/dist-newstyle/build/x86_64-linux/ghc-9.10.1/containers-tests-0/t/seq-properties/build/seq-properties/seq-properties-tmp/Main.o )
<no location info>: error:
    /home/erikd/Git/Haskell/containers/dist-newstyle/build/x86_64-linux/ghc-9.10.1/binary-0.8.9.2/build/libHSbinary-0.8.9.2-inplace-ghc9.10.1.so: undefined symbol: containerszm0zi7zminplace_DataziSetziInternal_zdwascLinkTop_info
```

This same link error happens with `ghc-9.12` comiled from the newly created `ghc-9.12` branch in git.

**Comment by treeowl** [comment]
Don't scare me like that! I thought you meant the property tests failed. How confident are you that you don't have something corrupted on your end? Can you reproduce the problem on a different installation?

**Comment by meooow25** [comment]
I don't see any issues on my system (also x86_64-linux) or on our CI with 9.10.1.

**Comment by Bodigrim** [comment]
@erikd what's your build plan? You can pipe `dist-newstyle/cache/plan.json` into [`cabal-plan`](https://hackage.haskell.org/package/cabal-plan).

**Comment by meooow25** [comment]
@erikd do you have any more information on this? Are you still seeing the failure?

**Comment by meooow25** [comment]
Please reopen if you have information.
