### ISSUE TITLE
Add a variant of `Data.Graph.dfs` which doesn't include start nodes in reachable set

### ISSUE THREAD

**Issue by mpickering** [haskell/containers#1064]
It would be useful for me if there was a variant of `Data.Graph.dfs` which didn't include the start nodes in the reachable set (apart from if they are reachable from another starting node).

Implementation could be along the lines of 

```
dfs2 :: G.Graph -> [Vertex] -> [Vertex]
dfs2 g vs0 = run (bounds g) $ start vs0
  where
    start :: [Vertex] -> SetM s [Vertex]
    start [] = pure []
    start (v:vs) = do
      as <- concat <$> mapM go (g ! v)
      bs <- start vs
      pure $ as ++ bs

    go :: Vertex -> SetM s [Vertex]
    go v = do
      visited <- contains v
      if visited
      then return []
      else do
        include v
        bs <- concat <$> mapM go (g!v)
        return (v:bs)
```

I specialised this version to `preOrderF` after the call to `dfs` as I just needed a list of nodes but you get the idea and it follow the same API as `dfs`. 

Would a contribution like this be welcomed and what would a suitable name be?

**Comment by meooow25** [comment]
> Would a contribution like this be welcomed and what would a suitable name be?

What is the use case for this?

> Implementation could be along the lines of...

This can be implemented using the existing `dfs`.

```hs
dfs2 :: Graph -> [Vertex] -> [Tree Vertex]
dfs2 g vs = dfs g (concatMap (g!) vs)
```

Note that this will include a start node if any node reachable from it leads back to it. This also applies to your code.

If this is not desirable, one can remove all the roots after a dfs:

```hs
dfs3 :: Graph -> [Vertex] -> [Tree Vertex]
dfs3 g vs = concatMap subForest (dfs g vs)
```

**Comment by mpickering** [comment]
The use-case is when I want to compute the set of reachable nodes from a node in the graph but to not include the node itself. The filtering approach doesn't work precisely because of I don't want to include start nodes, but I do want to include nodes which are start nodes if they are transitive dependencies. 

You suggestion for how to implement `dfs2`, looks good. I just wonder if it should be in the library or not.

**Comment by meooow25** [comment]
I'm still unsure whether you're asking for `dfs2` or `dfs3`.

To demonstrate,

```hs
> dfs2 g vs = dfs g (concatMap (g!) vs)
> dfs3 g vs = concatMap subForest (dfs g vs)
> let g = buildG (1,3) [(1,3),(1,2),(2,1)]
> dfs2 g [1,3]
[Node {rootLabel = 2, subForest = [Node {rootLabel = 1, subForest = [Node {rootLabel = 3, subForest = []}]}]}]
> dfs3 g [1,3]
[Node {rootLabel = 2, subForest = []},Node {rootLabel = 3, subForest = []}]
```

* Both will include start nodes if they are transitive dependencies (like `3` above)
* `dfs2` will include a start node if it is reachable from itself, `dfs3` will not (like `1` above).

> I just wonder if it should be in the library or not.

If it's a lesser-known/used algorithm and also easily defined using `dfs`, I feel it is not worth it.

**Comment by meooow25** [comment]
@mpickering I hope you can use one of the above (which don't seem worth adding to me).  
Please reopen if there are other variations to consider.
