### ISSUE TITLE
foldl' and foldr' for Seq are not strict in the starting value

### ISSUE THREAD

**Issue by meooow25** [haskell/containers#1072]
This is unlike every other structure we have.

```
λ> import qualified Data.Foldable as F
λ> import qualified Data.Set as S -- or Map or IntSet or IntMap
λ> F.foldl' (\_ _ -> ()) undefined (S.singleton ())
*** Exception: Prelude.undefined
CallStack (from HasCallStack):
  ...
λ> F.foldr' (\_ _ -> ()) undefined (S.singleton ())
*** Exception: Prelude.undefined
  ...
λ> import qualified Data.Sequence as Seq
λ> F.foldl' (\_ _ -> ()) undefined (Seq.singleton ())
()
λ> F.foldr' (\_ _ -> ()) undefined (Seq.singleton ())
()
```

I think we should make these strict.

Perhaps it's worth mentioning that for lists, `foldl'` is strict in the starting value but `foldr'` is not ([GHC #25508](https://gitlab.haskell.org/ghc/ghc/-/issues/25508)).

**Comment by meooow25** [comment]
@treeowl do you have opinions on this?

**Comment by treeowl** [comment]
The whole story is unfortunate. Historically, `foldl'` was lazy in the starting value for lists. Some other structures made it strict (I think that included `HashMap`, but I don't remember for sure). Then `foldl'` for lists became strict—by accident. Do we follow the trend? Probably yes. It's usually better that way, and there probably aren't many relying on the laziness.

**Comment by meooow25** [comment]
Interesting, I found your issue for the accidental change: [GHC #12173](https://gitlab.haskell.org/ghc/ghc/-/issues/12173).  
It seems that no one has complained about the change since, and there is one comment in favor of it.
I expect it would be fine to do the same for `Seq` too then.
