### ISSUE TITLE
containers-0.4.2.1 versus deepseq 1.4.x

### ISSUE THREAD

**Issue by peti** [haskell/containers#134]
Hi, I'm using this old version of `containers` for building with GHC 7.0.4, and I've run into trouble because containers 0.4.2.1 doesn't accept `deepseq` 1.4.x as a build input (even though the build works just fine when the constraint is lifted). Would you mind editing the Cabal file at http://hackage.haskell.org/package/containers/maintain to include the latest version of `deepseq` in the acceptable package set?

**Comment by treeowl** [comment]
This should probably be fine. I doubt that `containers` ever relied on the old default definition of `rnf`.

**Comment by tibbe** [comment]
I've updated the constraints for 0.4.2.1.

**Comment by peti** [comment]
I'm sorry for discovering this late, but it appears that deepseq 1.4.x is not supported after all: http://hydra.cryp.to/build/495180/nixlog/1/raw. The build fails with GHC 7.2.2. Not sure why that didn't show up with other versions of GHC, but I'd guess that deepseq enables a fancier implementation when it's built with 7.2.x or later that breaks the containers build. The relaxed constraint should probably be undone. :-(

**Comment by tibbe** [comment]
Undone.
