### ISSUE TITLE
Offer sequence internals

### ISSUE THREAD

**Issue by treeowl** [haskell/containers#149]
I've been playing with some ideas that require access to `Data.Sequence` internals, but that don't seem likely to ever go into `containers` because of dependencies. I would really like to see a `Data.Sequence.Internals` module that exports all interesting internals. Among the things to include:
1. The `Sized` class.
2. The `FingerTree`, `Digit`, `Node`, and `Elem` types.
3. A general version of `appendTree0` (not just specialized to `Elem`).
4. consing, snoccing, and viewing functions for FingerTrees.
5. Primitive splitting functions, including at least `splitTree`.

FYI: The particular idea I'm playing with now (incremental randomized sorting) is to use a `FingerTree` whose leaves are not `Elem`s but rather sequences (requiring `Seq a` to be an instance of `Sized`, which is trivial).

As usual, the maintainers would not be making any promises about API stability for such a module, and users would have to watch out for changes at any time.

**Comment by foxik** [comment]
I am not sure if that is worth it (i.e. if there is any demand -- obviously, you are one such user). Wouldn't it be easier to implement specialized tree implementation for the incremental sorting algorithm?

But if there is demand, having `Internal` module with "no API guarantee" would be probably fine.

**Comment by treeowl** [comment]
@foxik, it might be easier in some sense, but cutting and pasting the entire `appendTree` mess and replacing all the type names within in order to make GHC compile a whole new copy of that monstrosity does not strike me as a terribly polite thing to do. I'd also need to copy the conses, snocs, views, partition code, indexing code ... it wouldn't be particularly hard, but I think it would be a bit silly.

**Comment by treeowl** [comment]
Another thing is that the algorithm I'm working on is structured around `splitMap`, which is not currently exported. If it were, then I could, if necessary, do without additional internals.

**Comment by foxik** [comment]
@tibbe Johan, do you have any insight? I am quite undecisive about the `Internal` module. Although it is being used in several packages, it feels like violating the encapsulation and any API stability. One does also have to specify what exactly is available in the `Internal` module -- do we export everything we are using, or only something?

Also, if we decide to do this, should be have `Internal` modules for `{,Int}{Set,Map}`?

**Comment by treeowl** [comment]
We don't want to export quite everything, I don't think, because that can
be bad for the optimizer. Most packages, I think, offer no API stability
guarantees. The main reason not to export is to ensure no one can break
invariants, but they can actually do that already by making overly large
sequences, so I don't see the point of hiding things too much.

**Comment by sjakobi** [comment]
`containers` exposes both [`Data.Sequence.Internal`](http://hackage.haskell.org/package/containers-0.6.3.1/docs/Data-Sequence-Internal.html) and [`Data.Sequence.Internal.Sorting`](http://hackage.haskell.org/package/containers-0.6.3.1/docs/Data-Sequence-Internal-Sorting.html) these days, so I'll optimistically close this.

If there's more to do here, please reopen, or maybe open a new issue.
