### ISSUE TITLE
Add alterLookupWithKey function

### ISSUE THREAD

**Issue by schernichkin** [haskell/containers#151]
It would be nice to have alterLookupWithKey similar to insertLookupWithKey and updateLookupWithKey functions.

**Comment by foxik** [comment]
As this is API change, please follow the https://wiki.haskell.org/Library_submissions#Guide_to_proposers, notably please start discussion about `alterLookupWithKey` on libraries@haskell.org.

Thanks,
cheers,
Milan Straka

**Comment by hvr** [comment]
Seems slightly related to #28

**Comment by schernichkin** [comment]
#28 seems to be more radical. Surely it would cover this request if it were implemented.

**Comment by treeowl** [comment]
This functionality is subsumed by #220, which will be merged once its argument order is settled.
