### ISSUE TITLE
Data.Graph: document complexities O(...)

### ISSUE THREAD

**Issue by andreasabel** [haskell/containers#157]
The documentation of Data.Graph misses complexity information.

**Comment by foxik** [comment]
Any pull requested with the missing complexity information would be appreciated :-)

**Comment by andreasabel** [comment]
Yes, of course.  I won't prepare it, though, as I have 2^n Agda bugs chasing me... ;-)

**Comment by stefan-j** [comment]
Well in the study they indicate their DFS empirically as linear - O (V + E)

> Using these models, (see for example Sands (1993)) we believe our implementation of the DFS algorithms to be linear, but because these models have not been fully tested, we also ran empirical tests ourselves

Strongly connected components is two DFS so its linear as well
