### ISSUE TITLE
Data.Set: add insertUnlessMember 

### ISSUE THREAD

**Issue by andreasabel** [haskell/containers#161]
For `Data.Set`, I am missing something comparable to `Map.lookupInsertWithKey` that combines a `lookup` and an `insert`.  Suggestion (specification):

``` haskell
insertUnlessMember :: Ord a => a -> Set a -> Maybe (Set a)
insertUnlessMember a s = if member a s then Nothing else Just $ insert a s
```

Of course, that should have an efficient implementation that only traverses the tree once.

**Comment by tibbe** [comment]
Might be worth checking the performance gain. Lookups are usually much faster than inserts so a lookup + insert is often as fast as just an insert.

**Comment by andreasabel** [comment]
Yes, maybe, but why then has `Map` such a function and not `Set`?

**Comment by tibbe** [comment]
Someone probably thought it was faster (perhaps it is!), but I doubt it was tested.

**Comment by tibbe** [comment]
We could add it for consistency, but I would at least like to know if it actually helps. Our API suffers from a combinatoric explosion unfortunately, so I'd like to avoid growing it if not necessary.

**Comment by treeowl** [comment]
When comparison is expensive, the combined approach obviously wins. Obviously, that's not the best scenario for `Set` anyway, but it might be worth considering.

**Comment by tibbe** [comment]
@treeowl right, it can in theory be arbitrarily expensive. In the typical case however the runtime is dominated by the allocation done on insert. It's a typical memory bound problem (like most performance problems on modern CPUs).

**Comment by foxik** [comment]
Personally I am not sure we can make the implementation faster than the suggested one, notably when comparison is cheap like in the `Set Int` case. The reason are the Maybe allocations on every level.

Together with the fact that the proposed function is a simple combination of existing functions and is at most twice slower (assuming lookup complexity is dominated by insert complexity), I am not a big fan.

But please do not hesitate to surprise me with benchmark results :-)

**Comment by treeowl** [comment]
There are no `Maybe`

**Comment by m-renaud** [comment]
This is very similar to #291, #166, #290 which propose:

```haskell
lookupEntry :: (Ord a) => a -> Set a -> Maybe a
lookupEntry :: (Ord k) => k -> Map k v -> Maybe (k, v)
```

Would these functions address your use case? These have already (mostly*) been approved by the libraries committee and have the potential of going into the API soon.

\* _There was general agreement, but the discussion was a while ago so I'm going to raise it again to make sure everyone is on board still._

**Comment by treeowl** [comment]
No, I think they go together.

**Comment by m-renaud** [comment]
Oh yeah, duh, I read this wrong. Sorry for the noise.

**Comment by sjakobi** [comment]
With the `Data.Set.alterF` function added in 0.6.3.1, it's easy to define

```haskell
insertUnlessMember = alterF (\member_ -> if member_ then Nothing else Just True)
```

I'll tentatively close this issue, but feel free to reopen, if there's more to do here.
