### ISSUE TITLE
Possible documentation error for IntMap.alter

### ISSUE THREAD

**Issue by tsahyt** [haskell/containers#165]
The docs for lazy and strict IntMaps disagree on the complexity of the `alter` operation. As far as I can tell, both should list *O(min(n,W))*, but the strict version is listed as *O(log(n))*. As far as I understand, the strictness annotations should not change the complexity of altering elements in this case.

**Comment by foxik** [comment]
Thanks for noticing.

You are right, the `IntMap.Strict.alter` should have also the *O(min(n,W))* complexity.
