### ISSUE TITLE
Data.Map : modify insertWith type signature

### ISSUE THREAD

**Issue by bmabsout** [haskell/containers#170]
the current type signature is : Ord k => (a -> a -> a) -> k -> a -> Map k a -> Map k a
shouldn't it be :  Ord k => (b -> a -> a) -> k -> b -> Map k a -> Map k a
to support for example:
map :: Map Int [Int]
key :: Int
element :: Int
insertWith (:) key element map

or any function that doesn't take 2 arguments of the same type.
I guess other function's signatures would change as well but it's backwards compatible and I think it makes more sense.

**Comment by foxik** [comment]
The current signature is in fact correct, because when the given key does not exist in the map, the given key and value are inserted into the map.

In your case, you would be inserting `key::k` and `value::b` to `Map k a`, which would obviously fail.

For you version to work, `insertWith` would have to get also another `b -> a` function, or the combining function would have to be `b -> Maybe a -> a`.

**Comment by bmabsout** [comment]
Ahh i see i don't know how i missed that. b -> Maybe a -> a and  b -> a would work but simply also adding a would work as the default value (in my example it would be []) but i guess that changes the function and it won't be backwards compatible. in my case doing `insertWith (++) key [element]` works but in the case where you cannot easily convert from type a to type b then you will have to manually get the element from the map and update or insert it. But i guess backwards compatibility is much more important.

**Comment by foxik** [comment]
Backward compatibility is very serious issue with `containers`, which are used by many users.

Also note that if you can achieve the functionality you suggested in the first example using
`
insertWith ( element:) key element map
`

**Comment by foxik** [comment]
Backward compatibility is very serious issue with containers, which are used by many users.

Also note that if you can achieve the functionality you suggested in the first example using
`insertWith (const (element:)) key [element] map`
or, if you are sure the `key` is already in the map, you can do
`adjust (element:) key map`
