### ISSUE TITLE
Please use annotated Git version/release tags

### ISSUE THREAD

**Issue by hvr** [haskell/containers#172]
Lightweight Git tags are not appropriate for tagging releases as they carry no additional meta-data.
Moreoever, `git describe` and `git submodule` ignore lightweight tags by default. 

See also https://ghc.haskell.org/trac/ghc/wiki/Status/GHC-8.0.1/Libraries#Gittaggingtherelease

**Comment by foxik** [comment]
@hvr I just released 0.5.7.1, which is tagged using annotated tag. I also added changelog file in 0.5.7.1 and changed https://ghc.haskell.org/trac/ghc/wiki/Status/GHC-8.0.1/Libraries to list 0.5.7.1 as the wanted containers version.

Cheers,
Milan

**Comment by hvr** [comment]
Perfect, I've already updated GHC HEAD to point to the 0.5.7.1 tagged commit!

Cheers
