### ISSUE TITLE
 v0.5.7.1: Missing documentation on hackage

### ISSUE THREAD

**Issue by nd2s** [haskell/containers#175]
Documentation for latest version is not accessible on hackage: https://hackage.haskell.org/package/containers-0.5.7.1

**Comment by foxik** [comment]
As far as I understand, the docs are just not built yet (status of Docs on hackage is "pending").

The 0.5.7.1 was submitted less than 2 days ago, so lets wait some more.

**Comment by nd2s** [comment]
Sorry, I wasn't aware this takes so long to generate (and haven't seen the `pending` status).

**Comment by foxik** [comment]
Well, the documentation is _still_ not built... But if the building failed, we would see the error in the web interface.

I am leaving this open and will check again in 2016.

**Comment by treeowl** [comment]
It's there now, anyway.
