### ISSUE TITLE
Data.Sequence filter performance

### ISSUE THREAD

**Issue by lwdye** [haskell/containers#176]
The following is a criterion benchmark of a simple filter on [Int] and Seq Int.  The [Int] demonstrates linear complexity in the length of the list and Seq Int appears to be quadratic.  (Complete results at end)

[2.1x, 3.2x, 14x]  of List for length = (100,1000,10000)

Tested LTS 4.1 (version 5.6.1) and current versions 5.7.1
ghc -O3

Q.1  Is this what is expected?  If not can you identify error in test procedure?
Q.2  What other Data.Sequence functions will underperform equivalent List functions ?
Q.3  Are there any significant improvements planned relating to GHC 8.01+ ?

Thanks!

--------------------------------------------------------------------------------

{-# LANGUAGE FlexibleContexts, ScopedTypeVariables #-}

import Criterion.Main
import qualified Data.List as L
import qualified Data.Sequence as S

nSeq::IO (S.Seq Int, S.Seq Int, S.Seq Int)
nSeq = return (S.fromList [1..100], S.fromList [1..1000], S.fromList [1..10000])

nList::IO ([Int],[Int],[Int])
nList = return ([1..100],[1..1000],[1..10000])

fL::[Int] -> [Int]
fL =  L.filter ( > (50 :: Int))

fS::S.Seq Int-> S.Seq Int
fS =  S.filter ( > (50 :: Int))

main :: IO ()
main = defaultMain [
        env nList $ \ ~(a,b,c) ->
             bgroup "List Int" [
               bgroup "filter" [
                 bench "filter 100"    $ nf fL a
               , bench "filter 1000"   $ nf fL b
               , bench "filter 10000"  $ nf fL c
               ]
          ]
         , env nSeq $ \ ~(a,b,c) ->
             bgroup "Seq Int" [
               bgroup "filter" [
                 bench "filter 100"    $ nf fS a
               , bench "filter 1000"   $ nf fS b
               , bench "filter 10000"  $ nf fS c
               ]
          ]
        ]

--------------------------------------- Results ------------------------------------

benchmarking List Int/filter/filter 100
time                 1.007 μs   (985.9 ns .. 1.024 μs)
                     0.996 R²   (0.995 R² .. 0.998 R²)
mean                 995.5 ns   (974.2 ns .. 1.016 μs)
std dev              70.35 ns   (57.38 ns .. 93.81 ns)
variance introduced by outliers: 80% (severely inflated)

benchmarking List Int/filter/filter 1000
time                 13.34 μs   (13.06 μs .. 13.60 μs)
                     0.996 R²   (0.995 R² .. 0.998 R²)
mean                 13.42 μs   (13.15 μs .. 13.68 μs)
std dev              880.3 ns   (745.9 ns .. 1.101 μs)
variance introduced by outliers: 72% (severely inflated)

benchmarking List Int/filter/filter 10000
time                 137.2 μs   (134.4 μs .. 139.7 μs)
                     0.996 R²   (0.994 R² .. 0.998 R²)
mean                 136.3 μs   (133.9 μs .. 139.2 μs)
std dev              9.450 μs   (7.973 μs .. 11.17 μs)
variance introduced by outliers: 67% (severely inflated)

benchmarking Seq Int/filter/filter 100
time                 1.928 μs   (1.905 μs .. 1.953 μs)
                     0.998 R²   (0.997 R² .. 0.999 R²)
mean                 1.927 μs   (1.890 μs .. 1.965 μs)
std dev              123.6 ns   (101.5 ns .. 149.5 ns)
variance introduced by outliers: 75% (severely inflated)

benchmarking Seq Int/filter/filter 1000
time                 42.22 μs   (41.39 μs .. 43.11 μs)
                     0.996 R²   (0.995 R² .. 0.998 R²)
mean                 42.32 μs   (41.59 μs .. 43.04 μs)
std dev              2.512 μs   (2.086 μs .. 3.078 μs)
variance introduced by outliers: 64% (severely inflated)

benchmarking Seq Int/filter/filter 10000
time                 1.776 ms   (1.739 ms .. 1.822 ms)
                     0.996 R²   (0.994 R² .. 0.997 R²)
mean                 1.823 ms   (1.794 ms .. 1.856 ms)
std dev              107.7 μs   (91.41 μs .. 139.2 μs)
variance introduced by outliers: 44% (moderately inflated)

**Comment by foxik** [comment]
Note that you should not use `filter (> 50)`, which causes the size of the result to be proportionally different depending on the size of the original structure (this is why List benchmarks for 1000 and 100 differ by a factor of 13 instead of 10).

When using `filter (>= 0)` and adding size `100000`, the benchmarks on my home machine (ghc 7.6.3 with default containers) are:
runtime of list benchmarks relative to the previous one: 1, 9.9, 10.01, 10,5 [should be 1, 10, 10, 10]
runtime of seq benchmarks relative to the previous one: 1, 12.4, 26, 20.9 [should be 1, 10, 10, 10]
slowdown factor of seq benchmarks relative to the list ones: 3, 3.7, 9.5, 19

So, the complexity of `Sequence.filter` seems superlinear, but it is far from quadratic.

Personally, I think this is just the real performance of `Sequence`: even if adding an element to `Seq` is amortized linear, the real slowdown is just that high.

For example, consider a benchmark which constructs a `Seq` from list by adding elements one by one (as `Sequence.filter` does it):
```haskell
fromListIteratively :: [Int] -> S.Seq Int
fromListIteratively xs = go S.empty xs
  where go !s [] = s
        go !s (x:xs) = go (s S.|> x) xs
```
Than running it on lists of size 100, 1000, 10000 and 100000 gives the following relative slowdowns:
1, 11.4, 16.7, 10.16
You can see the drop between 10000 and 1000, similar to the `filter` benchmarks.

One of the culprints are probably the more complex data constructors used when the sequence if deep enough. Another 'culprit' is the garbage collector -- the `Sequence.filter` generates much more garbage than `List.filter` (which generates _none_), so the superlinear runtime can be partially caused by the garbage collector.

So, to answer your questions:
Q1: I think this is expected. At least we do not know of any trivial error which we could fix.
Q2: Probably most of them. `Sequence` offers much more operations than `List`, so it is expected for it to be slower.
Q3: No. If you have any idea on how to achieve any speedup, any patch or even an idea is welcome.

**Comment by lwdye** [comment]
Thanks.  A good catch on the filter distorting the small N cases.  

I've looked at this a little more and it does appear that the GC costs explode for filter.  I've also extended the test to include IntSet, IntMap Map Int, and two alternative implementations of filter.  The first new implementation converts to List and back and has consistent super-linear growth.  The second changes foldl to foldl' in the current implementation and is about 5 times faster that the current implementation at N = 1M. 

The new foldl' (vs foldl) version of the function filter appears to perform the best.

IntSet, IntMap, and Map Int all seem to behave nicely with IntSet 2x faster than List.

I've included the test code below and tested with and initial 5G heap to push out the GC distortion.  Even with a 5G initial heap filter hits the GC hard above N=1M.  

----------------------------
 ./SequenceList +RTS -H5G -s
 
N = 100,1000,10000,100000,1000000

sequence = [3.977, 42.75, 545.0, 28.81, 409.7]
sequence' = [3.353 , 40.08, 539.8 , 8.267 * 1000, 121.3 * 1000]
sequence'' = [5.119, 60.24, 567.4, 6.190 * 1000, 76.84 * 1000 ]
list = [1.975, 15.42,  154.0 , 1.479 * 1000, 14.20 * 1000]
setInt = [2.642 , 27.57, 282.2 ,  3.195 *1000, 40.76 *1000 ]
mapInt = [ 2.281, 23.67, 243.9 ,  2.841 *1000,  39.02 *1000]

-------------------
 Normalized to List cost

[2.00,  2.8,  3.5, 19.5, 28.9] -- sequence 
[1.70,  2.6,  3.5,  5.6,  8.5]    -- sequence' - toList based
[2.59, 3.90, 3.68, 4.18, 5.41] -- sequence'' - foldl' based
[0.36, 0.46, 0.46, 0.47, 0.50] -- intSet
[1.34, 1.79, 1.83, 2.16, 2.87] --  setInt
[1.15, 1.53, 1.58, 1.92, 2.74] -- mapInt
[1.00, 1.00, 1.00, 1.00, 1.00] -- list

-- | /O(n)/.  The 'filter' function takes a predicate @p@ and a sequence
-- @xs@ and returns a sequence of those elements which satisfy the
-- predicate.
filter :: (a -> Bool) -> Seq a -> Seq a
filter p = foldl (\ xs x -> if p x then xs |> x else xs) empty

sequence' and sequence'' are given from

filter' :: (a -> Bool) -> S.Seq a -> S.Seq a
filter' p x = S.fromList $  L.filter p $ F.toList x

filter'' :: (a -> Bool) -> S.Seq a -> S.Seq a
filter'' p = F.foldl' (\ xs x -> if p x then xs S.|> x else xs) S.empty

This variation gives the same result as sequence.

filter''' :: (a -> Bool) -> S.Seq a -> S.Seq a
filter''' p = F.foldr (\ x xs -> if p x then  x S.<| xs else xs) S.empty

--------------------------------------------------


{-# LANGUAGE FlexibleContexts, ScopedTypeVariables #-}

import Criterion.Main
import qualified Data.List as L
import qualified Data.Sequence as S
import qualified Data.IntSet as IS
import qualified Data.Set as T
import qualified Data.IntMap as M
import qualified Data.Foldable as F

nList::IO ([Int],[Int],[Int],[Int],[Int])
nList = return ([1..100],[1..1000],[1..10000],[1..100000],[1..1000000])

nSeq::IO (S.Seq Int, S.Seq Int, S.Seq Int, S.Seq Int, S.Seq Int)
nSeq = return (S.fromList [1..100], S.fromList [1..1000], S.fromList [1..10000],S.fromList [1..100000], S.fromList [1..1000000])

nSet::IO (IS.IntSet,IS.IntSet,IS.IntSet,IS.IntSet,IS.IntSet)
nSet = return (IS.fromList [1..100], IS.fromList [1..1000],IS.fromList [1..10000],IS.fromList [1..100000],IS.fromList [1..1000000])

nT::IO (T.Set Int,T.Set Int,T.Set Int,T.Set Int,T.Set Int)
nT = return (T.fromList [1..100], T.fromList [1..1000],T.fromList [1..10000],T.fromList [1..100000],T.fromList [1..1000000])

nM::IO (M.IntMap Int,M.IntMap Int,M.IntMap Int,M.IntMap Int,M.IntMap Int)
nM = return (M.fromList $ zip [1..100]  [1..100], M.fromList $ zip [1..1000] [1..1000]
           , M.fromList $ zip [1..10000] [1..10000],  M.fromList $ zip [1..100000] [1..100000]
           , M.fromList $ zip [1..1000000] [1..1000000] )

filter' :: (a -> Bool) -> S.Seq a -> S.Seq a
filter' p x = S.fromList $  L.filter p $ F.toList x

filter'' :: (a -> Bool) -> S.Seq a -> S.Seq a
filter'' p = F.foldl' (\ xs x -> if p x then xs S.|> x else xs) S.empty

filter''' :: (a -> Bool) -> S.Seq a -> S.Seq a
filter''' p = F.foldr (\ x xs -> if p x then  x S.<| xs else xs) S.empty

fL::[Int] -> [Int]
fL =  L.filter ( > (0 :: Int))

fS::S.Seq Int-> S.Seq Int
fS =  S.filter ( > (0 :: Int))

fS'::S.Seq Int-> S.Seq Int
fS' =  filter' ( > (0 :: Int))

fS''::S.Seq Int-> S.Seq Int
fS'' =  filter'' ( > (0 :: Int))

fS'''::S.Seq Int-> S.Seq Int
fS''' =  filter''' ( > (0 :: Int))

fIS::IS.IntSet-> IS.IntSet
fIS =  IS.filter ( > (0 :: Int))

fT::T.Set Int-> T.Set Int
fT =  T.filter ( > (0 :: Int))

fM::M.IntMap Int-> M.IntMap Int
fM =  M.filter ( > (0 :: Int))

main :: IO ()
main = defaultMain [
        env nList $ \ ~(a,b,c,d,e) ->
             bgroup "List Int" [
               bgroup "filter" [
                 bench "filter 100"    $ nf fL a
               , bench "filter 1000"   $ nf fL b
               , bench "filter 10000"  $ nf fL c
               , bench "filter 100000"  $ nf fL d
               , bench "filter 1000000"  $ nf fL e
               ]
          ]
         , env nSeq $ \ ~(a,b,c,d,e) ->
             bgroup "Seq Int" [
               bgroup "filter" [
                 bench "filter 100"    $ nf fS a
               , bench "filter 1000"   $ nf fS b
               , bench "filter 10000"  $ nf fS c
               , bench "filter 100000"  $ nf fS d
               , bench "filter 1000000"  $ nf fS e
           ]
          ]
         , env nSeq $ \ ~(a,b,c,d,e) ->
             bgroup "Seq Int - filter' " [
               bgroup "filter" [
                 bench "filter 100"    $ nf fS' a
               , bench "filter 1000"   $ nf fS' b
               , bench "filter 10000"  $ nf fS' c
               , bench "filter 100000"  $ nf fS' d
               , bench "filter 1000000"  $ nf fS' e
               ]
          ]
         , env nSeq $ \ ~(a,b,c,d,e) ->
             bgroup "Seq Int - filter'' - foldl' based" [
               bgroup "filter" [
                 bench "filter 100"    $ nf fS'' a
               , bench "filter 1000"   $ nf fS'' b
               , bench "filter 10000"  $ nf fS'' c
               , bench "filter 100000"  $ nf fS'' d
               , bench "filter 1000000"  $ nf fS'' e
               ]
          ]
         , env nSeq $ \ ~(a,b,c,d,e) ->
             bgroup "Seq Int - filter''' - foldr based" [
               bgroup "filter" [
                 bench "filter 100"    $ nf fS''' a
               , bench "filter 1000"   $ nf fS''' b
               , bench "filter 10000"  $ nf fS''' c
               , bench "filter 100000"  $ nf fS''' d
               , bench "filter 1000000"  $ nf fS''' e
               ]
          ]
         , env nSet $ \ ~(a,b,c,d,e) ->
             bgroup "IntSet" [
               bgroup "filter" [
                 bench "filter 100"    $ nf fIS a
               , bench "filter 1000"   $ nf fIS b
               , bench "filter 10000"  $ nf fIS c
               , bench "filter 100000"  $ nf fIS d
               , bench "filter 1000000"  $ nf fIS e
               ]
          ]
         , env nT $ \ ~(a,b,c,d,e) ->
             bgroup "Set Int" [
               bgroup "filter" [
                 bench "filter 100"    $ nf fT a
               , bench "filter 1000"   $ nf fT b
               , bench "filter 10000"  $ nf fT c
               , bench "filter 100000"  $ nf fT d
               , bench "filter 1000000"  $ nf fT e
               ]
          ]
         , env nM $ \ ~(a,b,c,d,e) ->
             bgroup "IntMap Int" [
               bgroup "filter" [
                 bench "filter 100"    $ nf fM a
               , bench "filter 1000"   $ nf fM b
               , bench "filter 10000"  $ nf fM c
               , bench "filter 100000"  $ nf fM d
               , bench "filter 1000000"  $ nf fM e
               ]
          ]

        ]
