### ISSUE TITLE
Convenience methods for Sequences: head, tail

### ISSUE THREAD

**Issue by mcandre** [haskell/containers#187]
Could we get convenience methods like `head :: Seq a -> a` and `tail :: Seq a -> Seq a`?

**Comment by treeowl** [comment]
Once we've added pattern synonyms to inspect the ends, I think doing so will be easy enough. `head` and `tail` are discouraged for lists, so I don't think there's a great reason to offer them for sequences. `head` is just ``(`index` 0)`` anyway.

**Comment by treeowl** [comment]
And `tail` is `drop 1` as long as the sequence is not empty.

**Comment by mcandre** [comment]
Aye, implementation is relatively straightforward. I'm asking for *convenience functions* so that we users don't accidentally fudge up the implementations.

**Comment by foxik** [comment]
Firstly, thanks for working on improving `containers` :-)

Personally I am not much in favor of these partial functions -- `viewl` seems to provide same functionality, but with explicit handling of empty sequences. Nevertheless, if you feel strongly about this, please start a discussion at libraries@haskell.org, as outlined here: https://wiki.haskell.org/Library_submissions#Guide_to_proposers . That way we can find out what other think and add the requested functions if there is support for it.

**Comment by treeowl** [comment]
@mcandre, I'm going to close this issue for now. If you make some headway on the libraries list I can reopen it.
