### ISSUE TITLE
Integrate benchmarks with `cabal` and `stack`?

### ISSUE THREAD

**Issue by Gabriel439** [haskell/containers#188]
`cabal bench` and `stack bench` both support running benchmarks defined in `containers.cabal` as `Benchmark` suites.  For example, the benchmark suite for `benchmarks/Set.hs` module would look like this:

```
Benchmark set-benchmarks
    type: exitcode-stdio-1.0
    hs-source-dirs: benchmarks
    main-is: Set.hs
    ghc-options: -O2
    -- The final version would have dependency bounds
    build-depends: base >= 4.2 && < 5, containers, criterion, deepseq, mtl
```

This will not affect support for older `cabal` versions, because `cabal` ignores unrecognized sections for forwards compatibility.  Older versions of `cabal` will emit the following harmless warning when encountering these `Benchmark` sections:

```
Cabal file warning in path/to/containers/containers.cabal: Ignoring unknown section type: benchmark
```

I'd be happy to contribute this change if you are okay with it

**Comment by foxik** [comment]
While the tests are part of "public" part of the package (and therefore they are part of the cabal file), the benchmarks are mostly internal (they usually work only with specified version of criterion, for example), so I am happy they are not part of the cabal.

Do you have some specific usage in mind by adding the benchmarks to the cabal file?

BTW, I do not think you can add `containers` to `build-depends` -- wouldn't it use the already installed `containers`? Also I did not check if we really need it, but we use `-DTESTING` for compiling the benchmarks.

**Comment by Gabriel439** [comment]
Almost all benchmarks on Hackage only work with specific versions of `criterion` so `containers` is not unusual in this regard.  This is no different than your test suite depending on a specific version of `QuickCheck`.  Both `cabal` and `stack` do not conflate the benchmark/test suite dependencies with library dependencies, so your users won't accidentally pick up the dependencies by depending on `containers`.

The purpose of adding the benchmarks to the cabal file is so that they can be built reproducibly.  Right now the version bounds that your benchmarks depends on for dependencies like `criterion` are not documented anywhere so users have to guess how to build and run the benchmarks.

Also, it's good package hygiene to use standard interfaces for benchmarking (for the same reason that standard interfaces for testing are good).  This simplifies life for new contributors who wish to test performance enhancements: all they have to do once you add these stanzas is just run a single command, `stack bench`, and the rest is automated for them.

You can safely add `containers` to the build-depends of benchmark and test suites.  `cabal` and `stack` are both smart and will pick up that this is referring to the locally built `containers` package and not the one that ships with `ghc` as a boot library.  I just verified this (by adding some new function to the library and then using that function from the benchmark suite).

**Comment by foxik** [comment]
Nice to know that adding `containers` as build-depends works. I thought it was not working some time ago, so either it was fixed or I remember wrong.

Personally, I think our benchmarks are not as polished as they should be (they use very limited range, for example), so I do not feel we should promote them by adding them to cabal... We should start by rewriting the benchmarks in the first place :-)

**Comment by Gabriel439** [comment]
Alright, that sounds reasonable.  Would you like me to open up a separate issue to discuss how to first improve the benchmarks?

**Comment by foxik** [comment]
If you have the energy for it, why not :-)

But it will not be much of a discussion -- the containers benchmark suite is very low on my priorities. If you have the power to work on it, you are welcome to have a go. What should probably happen:
- make sure everything works with a reasonable new version of criterion
- support benchmarking of various sizes, not fixed 2^12; at least 3 sizes would be nice
- deal with SetOperations and LookupGE subdirectories. The LookupGE are mostly private benchmarks -- they should stay in the repo for historical reasons (to see why we have the lookups which we have), but should probably not be part of the cabal file; the SetOperations benchmarks could stay separate, we could merge them into one benchmark (instead of four), or (probably the best) we could merge them to top-level benchmarks (SetOperations-IntMap to IntMap, etc).
- anything you think is a good idea

**Comment by treeowl** [comment]
@Gabriel439, do you think you could open up a pull request to integrate the benchmarks into Cabal? We don't currently have anything for Stack, and I know virtually nothing about it. Do you know how much work it would take to set that up properly?

**Comment by Gabriel439** [comment]
So I have a pull request open to add `cabal` support for benchmarks: https://github.com/haskell/containers/pull/243

I could not get this working with `stack`.  The exact error I got was:

```bash
$ stack bench
...
aeson-0.9.0.1: copy/register
Progress: 24/28
--  While building package monad-par-0.3.4.7 using:
      /Users/gabriel/.stack/setup-exe-cache/x86_64-osx/setup-Simple-Cabal-1.22.5.0-ghc-7.10.3 --builddir=.stack-work/dist/x86_64-osx/Cabal-1.22.5.0 configure --with-ghc=/Applications/ghc-7.10.3.app/Contents/bin/ghc --with-ghc-pkg=/Applications/ghc-7.10.3.app/Contents/bin/ghc-pkg --user --package-db=clear --package-db=global --package-db=/Users/gabriel/.stack/snapshots/x86_64-osx/lts-5.5/7.10.3/pkgdb --package-db=/Users/gabriel/proj/containers/.stack-work/install/x86_64-osx/lts-5.5/7.10.3/pkgdb --libdir=/Users/gabriel/proj/containers/.stack-work/install/x86_64-osx/lts-5.5/7.10.3/lib --bindir=/Users/gabriel/proj/containers/.stack-work/install/x86_64-osx/lts-5.5/7.10.3/bin --datadir=/Users/gabriel/proj/containers/.stack-work/install/x86_64-osx/lts-5.5/7.10.3/share --libexecdir=/Users/gabriel/proj/containers/.stack-work/install/x86_64-osx/lts-5.5/7.10.3/libexec --sysconfdir=/Users/gabriel/proj/containers/.stack-work/install/x86_64-osx/lts-5.5/7.10.3/etc --docdir=/Users/gabriel/proj/containers/.stack-work/install/x86_64-osx/lts-5.5/7.10.3/doc/monad-par-0.3.4.7 --htmldir=/Users/gabriel/proj/containers/.stack-work/install/x86_64-osx/lts-5.5/7.10.3/doc/monad-par-0.3.4.7 --haddockdir=/Users/gabriel/proj/containers/.stack-work/install/x86_64-osx/lts-5.5/7.10.3/doc/monad-par-0.3.4.7 --dependency=abstract-deque=abstract-deque-0.3-c6d4de3fa7a16ea191ae0412a87d32d8 --dependency=abstract-par=abstract-par-0.3.3-5b5d8ffe05086f29debd2062543c648c --dependency=array=array-0.5.1.0-960bf9ae8875cc30355e086f8853a049 --dependency=base=base-4.8.2.0-cc43d8e06aa74e9c4c0132becc49ee25 --dependency=containers=containers-0.5.7.1-d57b18996a8f211ae73caea3984f4f46 --dependency=deepseq=deepseq-1.4.1.1-8eec8f9bea2efc2500f63544ec6ca569 --dependency=monad-par-extras=monad-par-extras-0.3.3-5a725b3637ee59f4d59e6553938ff34d --dependency=mtl=mtl-2.2.1-3af90341e75ee52dfc4e3143b4e5d219 --dependency=mwc-random=mwc-random-0.13.4.0-f02423851c94fdb6acd15755a6e144fb --dependency=parallel=parallel-3.2.1.0-2aa03959d466e8e832fec76fe83f9e7b
    Process exited with code: ExitFailure 1
    Logs have been written to: /Users/gabriel/proj/containers/.stack-work/logs/monad-par-0.3.4.7.log

    Configuring monad-par-0.3.4.7...
    setup-Simple-Cabal-1.22.5.0-ghc-7.10.3: The following installed packages are
    broken because other packages they depend on are missing. These broken
    packages must be rebuilt before they can be used.
    package mwc-random-0.13.4.0 is broken due to missing package
    time-1.5.0.1-14681d29751415f1a49b9321095eae91


--  While building package vector-algorithms-0.7.0.1 using:
      /Users/gabriel/.stack/setup-exe-cache/x86_64-osx/setup-Simple-Cabal-1.22.5.0-ghc-7.10.3 --builddir=.stack-work/dist/x86_64-osx/Cabal-1.22.5.0 configure --with-ghc=/Applications/ghc-7.10.3.app/Contents/bin/ghc --with-ghc-pkg=/Applications/ghc-7.10.3.app/Contents/bin/ghc-pkg --user --package-db=clear --package-db=global --package-db=/Users/gabriel/.stack/snapshots/x86_64-osx/lts-5.5/7.10.3/pkgdb --libdir=/Users/gabriel/.stack/snapshots/x86_64-osx/lts-5.5/7.10.3/lib --bindir=/Users/gabriel/.stack/snapshots/x86_64-osx/lts-5.5/7.10.3/bin --datadir=/Users/gabriel/.stack/snapshots/x86_64-osx/lts-5.5/7.10.3/share --libexecdir=/Users/gabriel/.stack/snapshots/x86_64-osx/lts-5.5/7.10.3/libexec --sysconfdir=/Users/gabriel/.stack/snapshots/x86_64-osx/lts-5.5/7.10.3/etc --docdir=/Users/gabriel/.stack/snapshots/x86_64-osx/lts-5.5/7.10.3/doc/vector-algorithms-0.7.0.1 --htmldir=/Users/gabriel/.stack/snapshots/x86_64-osx/lts-5.5/7.10.3/doc/vector-algorithms-0.7.0.1 --haddockdir=/Users/gabriel/.stack/snapshots/x86_64-osx/lts-5.5/7.10.3/doc/vector-algorithms-0.7.0.1 --dependency=base=base-4.8.2.0-cc43d8e06aa74e9c4c0132becc49ee25 --dependency=bytestring=bytestring-0.10.6.0-04b5cc1d05f993b3b016543ca2863add --dependency=mtl=mtl-2.2.1-3af90341e75ee52dfc4e3143b4e5d219 --dependency=mwc-random=mwc-random-0.13.4.0-f02423851c94fdb6acd15755a6e144fb --dependency=primitive=primitive-0.6.1.0-b2a7b9f8d5591c0d4ce7ef238a3217d2 --dependency=vector=vector-0.11.0.0-324da2b07f25721d305480db94a9f1d6
    Process exited with code: ExitFailure 1
    Logs have been written to: /Users/gabriel/proj/containers/.stack-work/logs/vector-algorithms-0.7.0.1.log

    Configuring vector-algorithms-0.7.0.1...
    setup-Simple-Cabal-1.22.5.0-ghc-7.10.3: The following installed packages are
    broken because other packages they depend on are missing. These broken
    packages must be rebuilt before they can be used.
    package mwc-random-0.13.4.0 is broken due to missing package
    time-1.5.0.1-14681d29751415f1a49b9321095eae91
```

My guess is that this is probably related to the fact that `stack` gives `containers` special treatment as a GHC boot package, so I'm putting `stack` support on hold for now.
