### ISSUE TITLE
keysSet

### ISSUE THREAD

**Issue by andrewthad** [haskell/containers#224]
For `Data.Map`, there is a `keys` function that produces a list. I can trivially make a `keysSet` function with:

    keysSet = Set.fromDistinctAscList . Map.keys

I think it would be nice to offer `keysSet` directly from the `Data.Map` modules so that users wouldn't have to call an unsafe function from `Set`. Then again, I don't know if `containers` tries to avoid having any of the types spill over into the other modules. But, then again one more time, `Set` and `Map` do have a somewhat close relationship since they're both rely on the same `Ord` constraint (and they're both implemented as trees).

**Comment by treeowl** [comment]
I like this idea. Not only are they both implemented as trees, but if I'm reading this right, they're implemented as binary trees *with the same balance invariant*. This means that your `keysSet` function should be extremely small and efficient:

```haskell
keysSet :: Map k v -> Set k
keysSet M.Tip = S.Tip
keysSet (M.Bin sz k v l r) = S.Bin sz k l r
```

I don't think it would be horrible to put such a thing in `Data.Map.Lazy` and `Data.Map.Strict`. But please don't put it in `Data.Map.Base`.

Note also: I spoke to Ed Kmett the other day, and we're both pretty excited about the idea of exposing "internal" `containers` modules so intrepid developers willing to risk some instability can get at the guts themselves. For the maps and sets, it should be really simple to do this. For `Data.Sequence` it poses a bit more of a potential challenge, but we can overcome that.

**Comment by treeowl** [comment]
Oops... If you read my last remark by email, please check GitHub for the correction.

**Comment by andrewthad** [comment]
Oh, that's even better than the implementation I had. And yes, I meant to imply that it would go into `Data.Map.Lazy` and `Data.Map.Strict` (I didn't even know that `Data.Map.Base` was a thing since I haven't poked around in the internal modules).

I can put up a PR for this now, or if you'd rather wait for more feedback, we can wait for a bit.

**Comment by treeowl** [comment]
Go ahead and put up the PR, but you should also write to libraries@haskell.org with a formal proposal. Others may want a different name, etc.

**Comment by treeowl** [comment]
Ahaha!

It's already there!

**Comment by treeowl** [comment]
https://hackage.haskell.org/package/containers-0.5.7.1/docs/Data-Map-Lazy.html#g:17

**Comment by andrewthad** [comment]
Ahhh!
