### ISSUE TITLE
Consider enforcing Nil restriction in Data.IntMap structurally

### ISSUE THREAD

**Issue by treeowl** [haskell/containers#225]
Conceptually,

``` haskell
data IntMap1 a = Bin ... | Tip ...
data IntMap a = IM !(IntMap1 a) | Nil
```

but in fact, we currently have

``` haskell
data IntMap a = Bin ... | Tip ... | Nil
```

I'd love to see if we can switch to the more precise form without too much pain or performance cost.

**Comment by treeowl** [comment]
The most obvious potential performance problem with the above is that it adds an extra indirection to the top of the tree. We could avoid this by inlining one step, at the cost of increasing code size:

```haskell
data IntMap1 a = Bin1 ... | Tip1 ...
data IntMap a = Bin ... (IntMap1 a) (IntMap1 a) | Tip ... | Nil
```

Kind of yucky, that. :(

**Comment by treeowl** [comment]
Ed Kmett doesn't think there's a way that will be nice and also fast. I want to benchmark the obvious way to see just how bad it really is.

**Comment by treeowl** [comment]
It looks like there are a couple ideas running around GHC development circles that could ultimately support this. Either `newtype` optimization for certain existential types or unpacking sum types could do the trick, although the latter seems currently to exclude recursive cases.

**Comment by m-renaud** [comment]
FYI #456 adds tests that validate the internal structure, including the `Nil` restriction in `Data.IntMap`.

**Comment by treeowl** [comment]
Yeah, I think we should close this, as it awaits research needed-type feature requests upstream. I'm not very happy about that.
