### ISSUE TITLE
Add Haddock "since" annotations for all new exports

### ISSUE THREAD

**Issue by treeowl** [haskell/containers#252]
This one's a long, thankless slog, but invaluable to users seeking to write code that will work across multiple `containers` versions. It would be great to work back at least to whichever version shipped with GHC 7.8, but people are probably still using whatever shipped with GHC 7.6 and possibly even earlier versions.

**Comment by sjakobi** [comment]
See my PR #447.

To make sure that future changes and additions are accompanied by the proper @since-annotations I'd recommend adding a [PR-template](https://github.com/blog/2111-issue-and-pull-request-templates) as used by [the cabal project for example](https://github.com/haskell/cabal/blob/master/.github/PULL_REQUEST_TEMPLATE.md).

**Comment by andreasabel** [comment]
Is this issue still open?  (The PR is merged.)

I was just looking for a `@since` annotation for `Data.Map.Strict.alterF`, but there wasn't any. 😢

**Comment by treeowl** [comment]
> Is this issue still open? (The PR is merged.)
> 
> I was just looking for a `@since` annotation for `Data.Map.Strict.alterF`, but there wasn't any.

I'm not sure there's much point in ever closing this issue. 😓 Please feel free to open a PR with whichever `@since` annotations you'd like.

**Comment by sjakobi** [comment]
> I was just looking for a `@since` annotation for `Data.Map.Strict.alterF`, but there wasn't any. 
> 
> BTW: For `alterF` it would be 0.5.8.

See https://github.com/haskell/containers/pull/735.

**Comment by treeowl** [comment]
@sjakobi, I'd rather not close tickets till their associated PRs are *merged*.

**Comment by sjakobi** [comment]
Yeah. I guess this is just a weird issue that might never be closed as long as `containers` gets new additions. It doesn't seem helpful as a reminder either…

Feel free to reopen the issue if you think it has value.
