### ISSUE TITLE
Binary searching in a Data.Sequence is "expensive"

### ISSUE THREAD

**Issue by noinia** [haskell/containers#279]
I've run into this issue now several times, and hence decided to open a ticket here.

Several times I've had the need to be able to binary search on a Data.Sequence, i.e. given a monotone predicate, split the sequence at the point where the predicate flips from False to True. With the current interface the only way to do that is to use splitAt on the n/2^th element, test the predicate, and recurse appropriately. However, this leads to a running time of sum_i=1^(log n) log(n/2^i) = sum_i=1^(log n) (log n - i) = log^2 n/2 + log n/2 = O(log^2 n), instead of the O(log n) one would hope for. 

I don't think there is any way of easily fixing this (i.e. providing a O(log n) split for a monotone predicate). The only way I see to get this access time would be to add additional data to the Measure's of the underlying finger tree, but that seems quite a pervasive change.... 

I would be happy to be proven wrong though :).

**Comment by treeowl** [comment]
I don't believe there's any way to get better than `O(log^2 n)` without enhancing the annotations, no. And we're not going to enhance the annotations for `Data.Sequence` because that would have a serious performance impact for everyone else. However, you can very likely speed up your code! The constant factors for `splitAt` are not so wonderful (although I've sped it up *considerably* in the GitHub master branch this month). `index`, and the new `lookup` and `(!?)`, are much faster. Since you're stuck with `O(log^2 n)` anyway, you may very well find that skipping the splitting and just indexing into the original sequence is faster.

**Comment by noinia** [comment]
I'll have a look at using lookup/regular indexing rather than splitAt. Furthermore, I understand the reluctance to change the annotations. Still, I can't help to be a bit dissapointed at what Data.Sequence buys me compared to the power of generic finger trees[1]. Somehow, I always end up with 'Seq can almost do it, but not quite', and the only use cases I actually end up using it for are a deqeue. For the more complicated operations you are forced to either use the generic finger trees without the fine tuned performance of Data.Sequence, or having to copy over whatever of the specialized implementation of Data.Seq is actually available, and maintain it yourself.  I wish there was a way of being able to profit from the work on Sequence for the generic FingerTrees as well. 

[1] Please don't get me wrong. I really value your, and others' work on it; please keep up

**Comment by treeowl** [comment]
I hear you. Much of the fine performance tuning for `Data.Sequence` relies on the fact that `Int`s can be unpacked into constructors, that `(Int, +, *)` is a ring we can pretend is ordered, and other things that just don't apply in general. It would be interesting to make a generic version with something like template Haskell to handle more/different annotations, unboxed elements, etc., but that would be a different thing. The generally poor constant factors for 2-3 finger trees make other approaches (like some of Ed Kmett's work on transients) attractive for high-performance sequence work. But `Data.Sequence` is what it is, and it can do some cool tricks, and it's a pretty good sequence type to slap in when you don't know just what operations you'll need but want non-horrible performance regardless.
