### ISSUE TITLE
Faster implementation of generic IntSet.lowestBitSet

### ISSUE THREAD

**Issue by amigalemming** [haskell/containers#289]
Is the generic implementation of `IntSet.lowestBitSet` still in use?
I think it can be made faster by first extracting the lowest bit with `x .&. (-x)` and then use an improved generic version of `indexOfTheOnlyBit`. This version would look like

```
(if x .&. 0xAAAAAAAA == 0 then 0 else 1) +
(if x .&. 0xCCCCCCCC == 0 then 0 else 2) +
(if x .&. 0xF0F0F0F0 == 0 then 0 else 4) +
(if x .&. 0xFF00FF00 == 0 then 0 else 8) +
(if x .&. 0xFFFF0000 == 0 then 0 else 16)
```

We would not need shifts and the computation has less data dependencies than the current implementation.

**Comment by treeowl** [comment]
It looks like I missed this ticket. The generic code is not used for GHC, so I doubt anyone is using it. This stuff all looks extremely hairy to me. If you can find a nicer way that benchmarks well, please go ahead and do something about it.

**Comment by wrengr** [comment]
All those conditionals are extremely bad news, performance-wise.

If we have a straightline version of `max` (or any function that maps all non-zero elements to one), then it's easy enough to straightline that code:

    foo x b n = max 1 (x .&. b) * n
    {-# INLINE foo #-}

    lowestBitSet x =
        foo x 0xAAAAAAAA 1 +
        foo x 0xCCCCCCCC 2 +
        foo x 0xF0F0F0F0 4 +
        foo x 0xFF00FF00 8 +
        foo x 0xFFFF0000 16

Though I very much doubt this will improve performance.

**Comment by amigalemming** [comment]
On Fri, 1 Jul 2016, wren romano wrote:

> All those conditionals are extremely bad news, performance-wise.

Does GHC support cmov? I assume that LLVM can generate it by optimization, 
once all laziness is eliminated. It might be cheaper than 'mul'.

> If we have a straightline version of max (or any function that maps all 
> non-zero elements to one), then it's easy enough to straightline that 
> code:
> 
> foo x b n = max 1 (x .&. b) * n
> {-# INLINE foo #-}


I guess you mean 'min'. Alternatively (i.e. using another function, 
mapping non-zero to one):

foo x b n = fromEnum (x .&. b /= 0) * n

**Comment by wrengr** [comment]
I don't know if GHC supports cmov, but in general GHC doesn't do anything fancy about low-level stuff. Basics like unboxing, sure; but nothing for branch-prediction or eliminating branches (last I checked).

yeah, I meant `min` semantics-wise. Performance-wise, on GHC we'd prolly prefer `(/=# 0)` (or `neWord# 0`) since it's a primop. Still, I'm dubious about the performance. Would want to see benchmarks on multiple architectures/OSes

**Comment by sjakobi** [comment]
Did https://github.com/haskell/containers/pull/379 improve the situation and/or possibly even fix this issue?!

**Comment by meooow25** [comment]
> Did #379 improve the situation and/or possibly even fix this issue?!

Seems so.
