### ISSUE TITLE
Add indexed function such as `elemAt` to `IntSet` and `IntMap`.

### ISSUE THREAD

**Issue by ppetr** [haskell/containers#29]
There are indexed functions for  `lookupIndex`, `findIndex`, `deleteIndex` and `elemAt`  in `Data.Set` as well as `Data.Map` (with additional `updateAt`). Please add similar functions to `Data.IntSet` and `Data.IntMap` if possible. I'd help me considerably. Thank you.

**Comment by GeorgeCo** [comment]
It would be nice if the documentation explained the rationale or just had a link to this page

**Comment by foxik** [comment]
Haha, your comment is more than 10 years after the previous post ;-)
