### ISSUE TITLE
Add validity checks to IntMap and IntSet tests

### ISSUE THREAD

**Issue by treeowl** [haskell/containers#304]
The other containers include validity checks to ensure that all operations on valid inputs produce valid outputs. For some reason, these seem to be missing from `IntMap` and `IntSet` tests. That makes me nervous!

**Comment by m-renaud** [comment]
I can take a stab at this if no one has started on it yet.

**Comment by treeowl** [comment]
Thanks!

**Comment by nomeata** [comment]
> The other containers include validity checks to ensure that all operations on valid inputs produce valid outputs. For some reason, these seem to be missing from IntMap and IntSet tests. That makes me nervous!

So far, I found no reason to worry: https://github.com/antalsz/hs-to-coq/blob/master/examples/containers/theories/IntSetProofs.v :-)

**Comment by treeowl** [comment]
Very interesting! I wonder how hard it would be to ensure such proofs stay
up to date. I know proof maintenance tends to be challenging.

**Comment by nomeata** [comment]
That is a very important and hard question, that I will avoid answering for now…
