### ISSUE TITLE
Mistake in the Data.Map.Strict documentation

### ISSUE THREAD

**Issue by carado** [haskell/containers#309]
I suspect the documentation for Data.Map.Strict was copy-pasted from Data.IntMap.Strict, as the explanation for mergeWithKey contains the line
> When calling mergeWithKey combine only1 only2, a function combining two **IntMap**s is created

in both (emphasis added). I suspect "IntMap" should probably read "Map" in the Data.Map.Strict documentation page, as it does on the Data.Map.Lazy documentation page.

**Comment by treeowl** [comment]
Good catch. Every single one of the combining functions will be replaced
within a couple of commits; I'll fix the docs at the same time.

**Comment by treeowl** [comment]
It looks like this was already fixed, in https://github.com/haskell/containers/commit/497e6a405b45da548e94bf184ef5a85523c6f4b8.
