### ISSUE TITLE
Redundant use of BangPatterns?

### ISSUE THREAD

**Issue by tomjaguarpaw** [haskell/containers#328]
These files enable `BangPatterns` but seems not to use them.  Is that intentional?

* https://github.com/haskell/containers/blob/master/benchmarks/IntSet.hs
* https://github.com/haskell/containers/blob/master/Data/Map/Strict/Merge.hs
* https://github.com/haskell/containers/blob/master/Data/Map/Lazy/Merge.hs
* https://github.com/haskell/containers/blob/master/Data/Map/Strict.hs

**Comment by treeowl** [comment]
I don't want to have to add them later if I need them. Does this lead to a warning or something?

**Comment by tomjaguarpaw** [comment]
It will lead to an HLint warning.

**Comment by treeowl** [comment]
Do we use HLint in this project? I don't think so.... Making containers
even close to HLint clean will be a major undertaking.

**Comment by tomjaguarpaw** [comment]
> Do we use HLint in this project?

I don't know!  I was just answering your question.  Sorry if I took it too literally.

As a new reader I found it somewhat confusing to see the redundant extensions and thought you might like to know in case it was unintentional.  If it's is indeed intentional then please do close the ticket.

**Comment by treeowl** [comment]
It was intentional, I'd say. If someone wants to try to make HLint do something useful for `containers` at some point then we can revisit the decision.
