### ISSUE TITLE
Lifted classes instances missing for all types.

### ISSUE THREAD

**Issue by expipiplus1** [haskell/containers#342]
It would be super handy to have instances for `Show1`, `Show2` and friends for the data types defined in containers. These classes are in `base` now so no additional dependencies are required.

**Comment by treeowl** [comment]
Great thought!

**Comment by treeowl** [comment]
The instances have now been added for all notable types, I believe: `Tree`, `Seq`, `Map`, `Set`, `IntMap`, and `SCC`.

**Comment by expipiplus1** [comment]
Thanks!
