### ISSUE TITLE
Feature Request: Data.Bag

### ISSUE THREAD

**Issue by andrewthad** [haskell/containers#345]
It would be nice to have `Data.Bag`. It seems like it could just be:

```
newtype Bag a = Bag (Map a Int)
```

And then there would be a bunch of functions that just call functions from `Data.Map`.

**Comment by mitchellwrosen** [comment]
Do you have a `Bag` API in mind from another programming language that you could share?

**Comment by andrewthad** [comment]
I was thinking that it would look a lot like the API from `Data.Set`. I'll try to think a little more about the bag-specific operations though.

**Comment by sjakobi** [comment]
There is already a [multiset](https://hackage.haskell.org/package/multiset) package in case you're not aware of that.

**Comment by treeowl** [comment]
Thanks for pointing that out, @sjakobi. I'm going to close this ticket. If `multiset` doesn't cover your needs, @andrewthad, you should consider opening a ticket against *that* package. No need to duplicate effort!

**Comment by andrewthad** [comment]
Wow. The implementation there is exactly what I had in mind. Good to know.
