### ISSUE TITLE
Typo in error message in Foldable instance

### ISSUE THREAD

**Issue by charles-cooper** [haskell/containers#349]
It's a little thing but the error message for `minimum` has a typo in it
https://hackage.haskell.org/package/containers-0.5.8.1/docs/src/Data.Map.Base.html#local-1627471894

```
    where start Tip = error "Map.Foldable.minumum: called with empty map"
```

**Comment by charles-cooper** [comment]
minumum -> minimum

**Comment by andrewthad** [comment]
You can probably PR this. I doubt that there will be any need to support the legacy misspelling ;)

**Comment by charles-cooper** [comment]
done
