### ISSUE TITLE
Question | Why is `showTreeWith` being deprecated?

### ISSUE THREAD

**Issue by charles-cooper** [haskell/containers#356]
This is quite a useful debugging function, especially for showing large maps which don't fit easily on one line.

**Comment by treeowl** [comment]
It's not actually being deprecated, but the deprecation pragma isn't able
to express that it's being moved. It will be available in the package for
the foreseeable future. Can you explain your use case a bit more? It sounds
like you probably actually want a function to pretty-print a map, rather
than to show its tree structure.

**Comment by charles-cooper** [comment]
Ah, I see.

Yes, you are correct that what I really would like is a pretty-printing function. In fact being able to reflect the sortedness of the keys rather than the internal structure would be helpful. My workaround would otherwise be to convert to a list and write some sort of pretty printing function on that.

The ideal format would be something like
```
k1 := `value which doesn't necessarily fit on one line'
k2 := `something else'
...
```
