### ISSUE TITLE
An Int64Map/Word64Map guaranteed to be 64-bits wide on all platforms?

### ISSUE THREAD

**Issue by AaronFriel** [haskell/containers#36]
I am sorely tempted to use IntMap as a backing for some C-interop code. The foreign library uses 64-bit handles (guaranteed to be equivalent to `int64_t`) but IntMap only guarantees Haskell's platform-sized `Int` compatibility. I don't want to restrict my library to only operating on x86-64, so I will have to use HashMap. I doubt the cost will be substantial, but I thought you would like to know that it's a use case that users might like to use IntMap but need a certain sized integer guaranteed.

I admit I haven't looked into the `IntMap` implementation to know if I've overlooked something.

**Comment by chessai** [comment]
perhaps using backpack with unpacked-containers would make this possible.
