### ISSUE TITLE
powerset

### ISSUE THREAD

**Issue by andrewthad** [haskell/containers#361]
Powerset would have the following type signature:

    powerset :: Ord a => Set a -> Set (Set a)

For what I'm writing, performance is not very important, so I'm just going to write a quick and inefficient implementation that converts it to a list and back. However, I speculate that there is a way to take advantage of knowledge of the `Ord` instance for `Set` to do this more efficiently.

**Comment by treeowl** [comment]
You should be able to write the listy implementation without an Ord
constraint. Start with zip [0..] (toList xs) to label each element with its
position. Then you should be able to work out a way to sort sublists.
There's probably a more efficient way, yes, and likely one that takes
advantage of the tree structure. I don't know how to write one off the top
of my head though

**Comment by sjakobi** [comment]
I think this issue should be closed in favor of #442.

**Comment by treeowl** [comment]
#442 is better. Thanks, @sjakobi.
