### ISSUE TITLE
showsPrec1 != showsPrec for Tree

### ISSUE THREAD

**Issue by RyanGlScott** [haskell/containers#380]
```
λ> :m + Data.Tree Data.Functor.Classes
λ> showsPrec1 11 (Node {rootLabel = 'a', subForest = []}) ""
"Node {rootLabel = 'a', subForest = []}"
λ> showsPrec 11 (Node {rootLabel = 'a', subForest = []}) ""
"(Node {rootLabel = 'a', subForest = []})"
```

`showsPrec1` doesn't surround it with parentheses like `showsPrec` does. I'll fix this.

**Comment by treeowl** [comment]
I merged your pull request, because these things obviously should behave the same, but I'm a bit mystified about why `showsPrec` uses parentheses here. Doesn't record syntax effectively bind more tightly than absolutely anything else?

**Comment by RyanGlScott** [comment]
> Doesn't record syntax effectively bind more tightly than absolutely anything else?

In normal Haskell code, yes. But it turns out that derived `Show` instances have always added these redundant parentheses around record syntax. There was at one point a proposal to change this, but it was defeated. See https://ghc.haskell.org/trac/ghc/ticket/2530.

**Comment by treeowl** [comment]
Well then!
