### ISSUE TITLE
Revert hand-inlining of strict constructors

### ISSUE THREAD

**Issue by treeowl** [haskell/containers#382]
A couple versions ago, I manually arranged to inline partially applied strict constructors to work around [GHC Trac 12990](https://ghc.haskell.org/trac/ghc/ticket/12990). Now that that's been fixed, we should clean up the code.

**Comment by m-renaud** [comment]
Do you have a link to the commit(s) where you added the hand-inlining?

**Comment by treeowl** [comment]
Not of-hand. If they're still around, they probably have names like bin'.

**Comment by m-renaud** [comment]
So I found this `bin` (no `bin'`s other than variable names):

https://github.com/haskell/containers/blob/356d4f91490385537b9bdd8d37c32f6e9220704e/Data/IntMap/Internal.hs#L3209-L3216

It does get partially applied in some places, but appears to serve more as a smart constructor and does additional checks (for Nil `r` or `l`) in addition to making the `Bin` constructor strict. So, I'm not sure if these hand-inlinings are still around, or if the above is the relevant function it's non-trivial to change it since those checks need to live somewhere.

IntSet has something similar, as do Map and Set (`bin` is a smart constructor).

**Comment by treeowl** [comment]
The final possibilities are node' and maybe deep' in Data.Sequence. If
those are gone, I think the ticket can be closed.

On Dec 22, 2017 3:53 PM, "Matt Renaud" <notifications@github.com> wrote:

So I found this bin (no bin's other than variable names):

https://github.com/haskell/containers/blob/356d4f91490385537b9bdd8d37c32f
6e9220704e/Data/IntMap/Internal.hs#L3209-L3216

It does get partially applied in some places, but appears to serve more as
a smart constructor and does additional checks (for Nil r or l) in addition
to making the Bin constructor strict. So, I'm not sure if these
hand-inlinings are still around, or if the above is the relevant function
it's non-trivial to change it since those checks need to live somewhere.

IntSet has something similar, as do Map and Set (bin is a smart
constructor).

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/haskell/containers/issues/382#issuecomment-353672967>,
or mute the thread

**Comment by m-renaud** [comment]
There `deep` which is a smart constructor for `Deep` (and only defined if `TESTING`), and no `node` or `node'`s.

https://github.com/haskell/containers/blob/master/Data/Sequence/Internal.hs#L948-L950

So, there doesn't appear to be any of this hand-inlining left.

**Comment by treeowl** [comment]
Great! Thanks for checking!

**Comment by treeowl** [comment]
For the record, I think they were actually called `node2'` and `node3'`, but they definitely don't exist anymore. FYI, @m-renaud, they were used to implement `traverse`-like functions, where we have things like `liftA2 (Node2 s) l r`.

The functions looked like

```haskell
node2' !s = \l r -> Node2 s l r
{-# INLINE node2 #-}
```

This was enough to convince GHC to inline `node2'` as soon as it was applied to `s`, which got rid of the silly boxing so the closure would store the size unboxed. The GHC fix does something pretty similar--strict constructor "wrapper" functions are now allowed to inline even when partially applied.

**Comment by m-renaud** [comment]
Ahh gotcha, thanks for the background :)
