### ISSUE TITLE
Data.Set has only "provisional" stability?!

### ISSUE THREAD

**Issue by sjakobi** [haskell/containers#389]
See https://github.com/haskell/containers/blob/edcf7c914f75d6072730ff6f8c62b90aa586880b/Data/Set.hs#L14.

These stability ratings don't really seem to mean that much. Maybe they should simply be removed?!

**Comment by treeowl** [comment]
Yes, I think they should be removed. Would you like to submit a pull
request?

**Comment by sjakobi** [comment]
I will!

**Comment by treeowl** [comment]
Would you like to give #388 a shot while you're digging around?

**Comment by sjakobi** [comment]
> Would you like to give #388 a shot while you're digging around?

I have it on my list now… :)
