### ISSUE TITLE
List fusion for function like `unions`

### ISSUE THREAD

**Issue by nomeata** [haskell/containers#396]
I was idly browsing https://phabricator.haskell.org/D3102 which had code that looked like

```
findPartiallyCompletedCycles :: [Module] -> [SCC ModSummary] -> Set.Set Module
findPartiallyCompletedCycles modsDone theGraph
   = Set.unions
       [mods_in_this_cycle
       | CyclicSCC vs <- theGraph  -- Acyclic? Not interesting.
        …
```
and I was wondering: There is a very reliable and good producer for list fusion (a list comprehension). Is `unions` a good producer.

And it seems it is not. It is defined in terms of a `container`-specific `strictFold`, and no fusion rules are set up for it.

Would it be worth implementing the same set of fusion rewrite rule we have for `foldl'` in `Data.Utils.StrictFold`?

**Comment by treeowl** [comment]
I think no. It *would* be worth getting rid of that foldlStrict cruft in
favor of foldl'. I think the original reason for the separate function is
gone now.

**Comment by treeowl** [comment]
As for the commit you were browsing, I don't *think* that particular bit of
code is performance-critical. And don't know if I even improved its
performance. But I do believe strongly that it's easier to read now, and if
it turns out to be performance-critical we'll be much better able to
address that.

**Comment by nomeata** [comment]
Right, That commit just made me wonder. I agree that it is a fine commit also without fusion.

**Comment by m-renaud** [comment]
>  It *would* be worth getting rid of that foldlStrict cruft in favor of foldl'

It sound sounds like this is the action item from this thread. Can we open a new issue for that and close this issue?

**Comment by treeowl** [comment]
@m-renaud Is the churn useful? I think not. There's only one issue here. Do you want to put together the PR, now that you have the benchmark suite set up?

**Comment by m-renaud** [comment]
> Is the churn useful? I think not.

That's fair, I've just been going through issues and cleaning them up. I'm fine leaving this open and made a note to put together benchmarks swapping out foldlStrict for foldl'.

**Comment by treeowl** [comment]
`foldlStrict` is entirely gone; we now use `foldl'`, which should fuse.
