### ISSUE TITLE
Fix strictness of Data.IntMap.Strict.traverseWithKey

### ISSUE THREAD

**Issue by treeowl** [haskell/containers#401]
I noticed that `Data.IntMap.Strict` reexports `traverseWithKey` from `Data.IntMap.Internal`. This is wrong, because it does not force values before installing them. That needs to be fixed, and all other re-exports should be checked. I highly recommend replacing the `import Data.IntMap.Internal hiding (...)` line with an `import Data.IntMap.Internal (...)` one; that makes it obvious what's being re-exported.

**Comment by sjakobi** [comment]
@wrengr Since you haven't been active in this project for quite a while, I'll remove your assignment in hopes that someone else might pick this up! :)

**Comment by treeowl** [comment]
@sjakobi, it looks like I fixed this and forgot to close it.
