### ISSUE TITLE
Improve the documentation on how IntSet is represented

### ISSUE THREAD

**Issue by wrengr** [haskell/containers#404]
The current comments/documentation on the internal representation of `IntSet` are poorly/confusingly phrased. This should be fixed to ease introducing future developers.

**Comment by m-renaud** [comment]
Thoughts on this being a README in the Data/IntMap/ directory (in addition to better comments in code)? That may make it easier to format and add graphics to help with the explanation. I can put something together since I've been digging around in the code a little bit.

**Comment by treeowl** [comment]
A README sounds okay, but there will need to be a strongly worded note in
the code reminding people to update it whenever the structure or invariants
change. Also, I think improving the comments remains a priority regardless.
