### ISSUE TITLE
Please upgrade the containers package on Stackage

### ISSUE THREAD

**Issue by ahri** [haskell/containers#420]
I wanted to use `Data.Sequence.lookup` and 0.5.7.1 is the latest I could get on Stackage. Please could you upgrade so everyone can have the safer `index` alternative if they so wish?

**Comment by treeowl** [comment]
We didn't put it on Stackage (someone else did; I think there was a ticket here to fix something so it could .

**Comment by treeowl** [comment]
We didn't put it on Stackage and we don't take responsibility for doing so. We don't have time. If you want it,, you'll have to deal with downstream.
