### ISSUE TITLE
Add `Dequeue`s

### ISSUE THREAD

**Issue by sgraf812** [haskell/containers#427]
They pop up quite often and I would find comfort in having them in `containers` instead of a 'third-party package' like [dequeue](https://hackage.haskell.org/package/dequeue-0.1.12).

**Comment by treeowl** [comment]
I'm certainly open to the idea. But what's wrong with other packages? If we
can actually do better, or if we can make a more uniform interface, then
sure, but I don't want to duplicate functionality just for the sake of
duplicating functionality.

**Comment by sgraf812** [comment]
Well, for one there's the idea of a well maintained (and well performing) de-facto standard package for containers. Just like one would expect from Java, C# or C++.

Also I was thinking from the rather dull perspective of reducing package dependencies. That might not be a big deal for regular cabal projects, but I was thinking more in the direction of having available standard data structures in GHC, which as I undestand isn't that open to including new packages in the bootstraps. Oh well, it's probably more of a gripe with GHC's build system.

**Comment by howsiwei** [comment]
I thought the reason why Okasaki's implicit recursive slowdown dequeue is not included in this package is that finger tree supports more operations and has comparable performance. So just use `Data.Sequence.Seq`?

**Comment by sgraf812** [comment]
Although the asymptotics might be similar, I really doubt the constants are. But yeah, using `Seq`s should be fine most of the time.
