### ISSUE TITLE
Add Show instance for SCC

### ISSUE THREAD

**Issue by yav** [haskell/containers#429]
Subject says it all---the type `SCC` from `Data.Graph` should be in the `Show` class.

**Comment by treeowl** [comment]
Your wish has already been granted. `SCC` gained instances of Foldable, Traversable, Data, Generic, Generic1, Eq, Eq1, Show, Show1, Read, and Read1 in containers-0.5.9.1.

**Comment by treeowl** [comment]
@yav, since you clearly use this type, I'm wondering if you can tell me if the derived `Eq` instance I gave it is actually the right one. Should it normalize cycles in some fashion?

**Comment by yav** [comment]
I think derived `Eq` is fine, I don't know that you can do much better since you know nothing about the members of the `SCC`.  It is just a simple tag type anyway, so I wouldn't worry about it.

**Comment by treeowl** [comment]
Well, you could impose an Ord constraint on them. I just don't know enough
about how this type is used to know what really makes sense.
