### ISSUE TITLE
Monoid instance for Map acts strangely 

### ISSUE THREAD

**Issue by sebastian-philipp** [haskell/containers#43]
I would expect, that mappend is also used for overlapping values:

```
ghci Data.Map Data.Monoid> Sum 5 <> Sum 3
Sum {getSum = 8}
ghci Data.Map Data.Monoid> fromList [(42, Sum 5)] <> fromList [(42, Sum 3)]
fromList [(42,Sum {getSum = 5})]

ghci Data.Map Data.Monoid> Product 5 <> Product 3
Product {getProduct = 15}
ghci Data.Map Data.Monoid> fromList [(1, Product 5)] <> fromList [(1, Product 3)]
fromList [(1,Product {getProduct = 5})]

ghci Data.Map Data.Monoid> "Hello" <> " World"
"Hello World"
ghci Data.Map Data.Monoid> fromList [("en", "Hello"), ("de", "Hallo")] <> fromList [("en", " world"), ("de", " Welt")]
fromList [("de","Hallo"),("en","Hello")]
```

Is there any reason, why this Monoid instance was implemented this way?

**Comment by andrewthad** [comment]
For what it's worth, I also would like this to be changed. I'm outlined a [way that it could be done](https://ghc.haskell.org/trac/ghc/ticket/1460#comment:8) and the benefits of doing so on the GHC trac. I understand the concern about breaking legacy stuff, but we do have PVP for a reason, and modifying code to replace `<>` with `M.union` isn't that hard.
