### ISSUE TITLE
Add intesectionSet :: Map k a -> Set k -> Map k a

### ISSUE THREAD

**Issue by phadej** [haskell/containers#430]
similarly `differenceSet :: Map k a -> Set k -> Map k`.

Making `Map.fromSet (const ())` feels wasteful to use `Map.intersection`, or is there some better way?

**Comment by treeowl** [comment]
`restrictKeys` and `withoutKeys`, in `Data.Map`, seem to be what you're after, restricting a map to the keys in a set and removing the keys found in a set, respectively. But we're missing the corresponding operations for cutting down a set based on the keys found in a map; proposal (for names) and PR welcome if you think those would be useful.

**Comment by phadej** [comment]
Thanks, I somehow missed them from the docs! Seems they are there since 0.5.8

**Comment by treeowl** [comment]
If you have any ideas for improving the documentation to make these easier
to find, please let me know! Also, do you think the reverse versions I
mentioned would be worth adding?
