### ISSUE TITLE
Building the containers tests on GHC 8.2.1 is especially noisy due to -Wmissing-home-modules

### ISSUE THREAD

**Issue by RyanGlScott** [haskell/containers#434]
On a recent build of the `containers` test suites using GHC 8.2.1, I encountered a veritable wall of warnings that were entirely due to `-Wmissing-home-modules`:

```
$ cabal test
Preprocessing test suite 'seq-properties' for containers-0.5.10.2..
Building test suite 'seq-properties' for containers-0.5.10.2..

<no location info>: warning: [-Wmissing-home-modules]
    These modules are needed for compilation but not listed in your .cabal file's other-modules: Data.Sequence
                                                                                                 Data.Sequence.Internal
                                                                                                 Utils.Containers.Internal.StrictPair

<no location info>: warning: [-Wmissing-home-modules]
    These modules are needed for compilation but not listed in your .cabal file's other-modules: Data.Sequence
                                                                                                 Data.Sequence.Internal
                                                                                                 Utils.Containers.Internal.StrictPair
Preprocessing test suite 'intmap-strict-properties' for containers-0.5.10.2..
Building test suite 'intmap-strict-properties' for containers-0.5.10.2..

<no location info>: warning: [-Wmissing-home-modules]
    These modules are needed for compilation but not listed in your .cabal file's other-modules: Data.IntMap.Internal
                                                                                                 Data.IntMap.Internal.Debug
                                                                                                 Data.IntMap.Internal.DeprecatedDebug
                                                                                                 Data.IntMap.Strict
                                                                                                 Data.IntSet
                                                                                                 Data.IntSet.Internal
                                                                                                 Utils.Containers.Internal.BitUtil
                                                                                                 Utils.Containers.Internal.StrictFold
                                                                                                 Utils.Containers.Internal.StrictPair

<no location info>: warning: [-Wmissing-home-modules]
    These modules are needed for compilation but not listed in your .cabal file's other-modules: Data.IntMap.Internal
                                                                                                 Data.IntMap.Internal.Debug
                                                                                                 Data.IntMap.Internal.DeprecatedDebug
                                                                                                 Data.IntMap.Strict
                                                                                                 Data.IntSet
                                                                                                 Data.IntSet.Internal
                                                                                                 Utils.Containers.Internal.BitUtil
                                                                                                 Utils.Containers.Internal.StrictFold
                                                                                                 Utils.Containers.Internal.StrictPair
Preprocessing test suite 'map-strictness-properties' for containers-0.5.10.2..
Building test suite 'map-strictness-properties' for containers-0.5.10.2..

<no location info>: warning: [-Wmissing-home-modules]
    These modules are needed for compilation but not listed in your .cabal file's other-modules: Data.Map.Internal
                                                                                                 Data.Map.Internal.Debug
                                                                                                 Data.Map.Internal.DeprecatedShowTree
                                                                                                 Data.Map.Strict
                                                                                                 Data.Map.Strict.Internal
                                                                                                 Data.Set.Internal
                                                                                                 Utils.Containers.Internal.BitQueue
                                                                                                 Utils.Containers.Internal.BitUtil
                                                                                                 Utils.Containers.Internal.PtrEquality
                                                                                                 Utils.Containers.Internal.StrictFold
                                                                                                 Utils.Containers.Internal.StrictMaybe
                                                                                                 Utils.Containers.Internal.StrictPair

<no location info>: warning: [-Wmissing-home-modules]
    These modules are needed for compilation but not listed in your .cabal file's other-modules: Data.Map.Internal
                                                                                                 Data.Map.Internal.Debug
                                                                                                 Data.Map.Internal.DeprecatedShowTree
                                                                                                 Data.Map.Strict
                                                                                                 Data.Map.Strict.Internal
                                                                                                 Data.Set.Internal
                                                                                                 Utils.Containers.Internal.BitQueue
                                                                                                 Utils.Containers.Internal.BitUtil
                                                                                                 Utils.Containers.Internal.PtrEquality
                                                                                                 Utils.Containers.Internal.StrictFold
                                                                                                 Utils.Containers.Internal.StrictMaybe
                                                                                                 Utils.Containers.Internal.StrictPair
Preprocessing test suite 'bitqueue-properties' for containers-0.5.10.2..
Building test suite 'bitqueue-properties' for containers-0.5.10.2..

<no location info>: warning: [-Wmissing-home-modules]
    These modules are needed for compilation but not listed in your .cabal file's other-modules: Utils.Containers.Internal.BitQueue
                                                                                                 Utils.Containers.Internal.BitUtil

<no location info>: warning: [-Wmissing-home-modules]
    These modules are needed for compilation but not listed in your .cabal file's other-modules: Utils.Containers.Internal.BitQueue
                                                                                                 Utils.Containers.Internal.BitUtil
Preprocessing test suite 'map-lazy-properties' for containers-0.5.10.2..
Building test suite 'map-lazy-properties' for containers-0.5.10.2..

<no location info>: warning: [-Wmissing-home-modules]
    These modules are needed for compilation but not listed in your .cabal file's other-modules: Data.Map.Internal
                                                                                                 Data.Map.Internal.Debug
                                                                                                 Data.Map.Internal.DeprecatedShowTree
                                                                                                 Data.Map.Lazy
                                                                                                 Data.Map.Merge.Lazy
                                                                                                 Data.Set
                                                                                                 Data.Set.Internal
                                                                                                 Utils.Containers.Internal.BitQueue
                                                                                                 Utils.Containers.Internal.BitUtil
                                                                                                 Utils.Containers.Internal.PtrEquality
                                                                                                 Utils.Containers.Internal.StrictFold
                                                                                                 Utils.Containers.Internal.StrictMaybe
                                                                                                 Utils.Containers.Internal.StrictPair

<no location info>: warning: [-Wmissing-home-modules]
    These modules are needed for compilation but not listed in your .cabal file's other-modules: Data.Map.Internal
                                                                                                 Data.Map.Internal.Debug
                                                                                                 Data.Map.Internal.DeprecatedShowTree
                                                                                                 Data.Map.Lazy
                                                                                                 Data.Map.Merge.Lazy
                                                                                                 Data.Set
                                                                                                 Data.Set.Internal
                                                                                                 Utils.Containers.Internal.BitQueue
                                                                                                 Utils.Containers.Internal.BitUtil
                                                                                                 Utils.Containers.Internal.PtrEquality
                                                                                                 Utils.Containers.Internal.StrictFold
                                                                                                 Utils.Containers.Internal.StrictMaybe
                                                                                                 Utils.Containers.Internal.StrictPair
Preprocessing test suite 'intmap-strictness-properties' for containers-0.5.10.2..
Building test suite 'intmap-strictness-properties' for containers-0.5.10.2..

<no location info>: warning: [-Wmissing-home-modules]
    These modules are needed for compilation but not listed in your .cabal file's other-modules: Data.IntMap.Internal
                                                                                                 Data.IntMap.Internal.DeprecatedDebug
                                                                                                 Data.IntMap.Strict
                                                                                                 Data.IntSet.Internal
                                                                                                 Utils.Containers.Internal.BitUtil
                                                                                                 Utils.Containers.Internal.StrictFold
                                                                                                 Utils.Containers.Internal.StrictPair

<no location info>: warning: [-Wmissing-home-modules]
    These modules are needed for compilation but not listed in your .cabal file's other-modules: Data.IntMap.Internal
                                                                                                 Data.IntMap.Internal.DeprecatedDebug
                                                                                                 Data.IntMap.Strict
                                                                                                 Data.IntSet.Internal
                                                                                                 Utils.Containers.Internal.BitUtil
                                                                                                 Utils.Containers.Internal.StrictFold
                                                                                                 Utils.Containers.Internal.StrictPair
Preprocessing test suite 'intset-properties' for containers-0.5.10.2..
Building test suite 'intset-properties' for containers-0.5.10.2..

<no location info>: warning: [-Wmissing-home-modules]
    These modules are needed for compilation but not listed in your .cabal file's other-modules: Data.IntSet
                                                                                                 Data.IntSet.Internal
                                                                                                 Data.Set
                                                                                                 Data.Set.Internal
                                                                                                 Utils.Containers.Internal.BitUtil
                                                                                                 Utils.Containers.Internal.PtrEquality
                                                                                                 Utils.Containers.Internal.StrictFold
                                                                                                 Utils.Containers.Internal.StrictPair

<no location info>: warning: [-Wmissing-home-modules]
    These modules are needed for compilation but not listed in your .cabal file's other-modules: Data.IntSet
                                                                                                 Data.IntSet.Internal
                                                                                                 Data.Set
                                                                                                 Data.Set.Internal
                                                                                                 Utils.Containers.Internal.BitUtil
                                                                                                 Utils.Containers.Internal.PtrEquality
                                                                                                 Utils.Containers.Internal.StrictFold
                                                                                                 Utils.Containers.Internal.StrictPair
Preprocessing test suite 'intmap-lazy-properties' for containers-0.5.10.2..
Building test suite 'intmap-lazy-properties' for containers-0.5.10.2..

<no location info>: warning: [-Wmissing-home-modules]
    These modules are needed for compilation but not listed in your .cabal file's other-modules: Data.IntMap.Internal
                                                                                                 Data.IntMap.Internal.Debug
                                                                                                 Data.IntMap.Internal.DeprecatedDebug
                                                                                                 Data.IntMap.Lazy
                                                                                                 Data.IntSet
                                                                                                 Data.IntSet.Internal
                                                                                                 Utils.Containers.Internal.BitUtil
                                                                                                 Utils.Containers.Internal.StrictFold
                                                                                                 Utils.Containers.Internal.StrictPair

<no location info>: warning: [-Wmissing-home-modules]
    These modules are needed for compilation but not listed in your .cabal file's other-modules: Data.IntMap.Internal
                                                                                                 Data.IntMap.Internal.Debug
                                                                                                 Data.IntMap.Internal.DeprecatedDebug
                                                                                                 Data.IntMap.Lazy
                                                                                                 Data.IntSet
                                                                                                 Data.IntSet.Internal
                                                                                                 Utils.Containers.Internal.BitUtil
                                                                                                 Utils.Containers.Internal.StrictFold
                                                                                                 Utils.Containers.Internal.StrictPair
Preprocessing test suite 'map-strict-properties' for containers-0.5.10.2..
Building test suite 'map-strict-properties' for containers-0.5.10.2..

<no location info>: warning: [-Wmissing-home-modules]
    These modules are needed for compilation but not listed in your .cabal file's other-modules: Data.Map.Internal
                                                                                                 Data.Map.Internal.Debug
                                                                                                 Data.Map.Internal.DeprecatedShowTree
                                                                                                 Data.Map.Merge.Strict
                                                                                                 Data.Map.Strict
                                                                                                 Data.Map.Strict.Internal
                                                                                                 Data.Set
                                                                                                 Data.Set.Internal
                                                                                                 Utils.Containers.Internal.BitQueue
                                                                                                 Utils.Containers.Internal.BitUtil
                                                                                                 Utils.Containers.Internal.PtrEquality
                                                                                                 Utils.Containers.Internal.StrictFold
                                                                                                 Utils.Containers.Internal.StrictMaybe
                                                                                                 Utils.Containers.Internal.StrictPair

<no location info>: warning: [-Wmissing-home-modules]
    These modules are needed for compilation but not listed in your .cabal file's other-modules: Data.Map.Internal
                                                                                                 Data.Map.Internal.Debug
                                                                                                 Data.Map.Internal.DeprecatedShowTree
                                                                                                 Data.Map.Merge.Strict
                                                                                                 Data.Map.Strict
                                                                                                 Data.Map.Strict.Internal
                                                                                                 Data.Set
                                                                                                 Data.Set.Internal
                                                                                                 Utils.Containers.Internal.BitQueue
                                                                                                 Utils.Containers.Internal.BitUtil
                                                                                                 Utils.Containers.Internal.PtrEquality
                                                                                                 Utils.Containers.Internal.StrictFold
                                                                                                 Utils.Containers.Internal.StrictMaybe
                                                                                                 Utils.Containers.Internal.StrictPair
Preprocessing test suite 'intset-strictness-properties' for containers-0.5.10.2..
Building test suite 'intset-strictness-properties' for containers-0.5.10.2..

<no location info>: warning: [-Wmissing-home-modules]
    These modules are needed for compilation but not listed in your .cabal file's other-modules: Data.IntSet
                                                                                                 Data.IntSet.Internal
                                                                                                 Utils.Containers.Internal.BitUtil
                                                                                                 Utils.Containers.Internal.StrictFold
                                                                                                 Utils.Containers.Internal.StrictPair

<no location info>: warning: [-Wmissing-home-modules]
    These modules are needed for compilation but not listed in your .cabal file's other-modules: Data.IntSet
                                                                                                 Data.IntSet.Internal
                                                                                                 Utils.Containers.Internal.BitUtil
                                                                                                 Utils.Containers.Internal.StrictFold
                                                                                                 Utils.Containers.Internal.StrictPair
Preprocessing test suite 'deprecated-properties' for containers-0.5.10.2..
Building test suite 'deprecated-properties' for containers-0.5.10.2..

<no location info>: warning: [-Wmissing-home-modules]
    These modules are needed for compilation but not listed in your .cabal file's other-modules: Data.IntMap
                                                                                                 Data.IntMap.Internal
                                                                                                 Data.IntMap.Internal.DeprecatedDebug
                                                                                                 Data.IntMap.Lazy
                                                                                                 Data.IntMap.Strict
                                                                                                 Data.IntSet.Internal
                                                                                                 Data.Map
                                                                                                 Data.Map.Internal
                                                                                                 Data.Map.Internal.Debug
                                                                                                 Data.Map.Internal.DeprecatedShowTree
                                                                                                 Data.Map.Lazy
                                                                                                 Data.Map.Strict
                                                                                                 Data.Map.Strict.Internal
                                                                                                 Data.Set.Internal
                                                                                                 Utils.Containers.Internal.BitQueue
                                                                                                 Utils.Containers.Internal.BitUtil
                                                                                                 Utils.Containers.Internal.PtrEquality
                                                                                                 Utils.Containers.Internal.StrictFold
                                                                                                 Utils.Containers.Internal.StrictMaybe
                                                                                                 Utils.Containers.Internal.StrictPair

<no location info>: warning: [-Wmissing-home-modules]
    These modules are needed for compilation but not listed in your .cabal file's other-modules: Data.IntMap
                                                                                                 Data.IntMap.Internal
                                                                                                 Data.IntMap.Internal.DeprecatedDebug
                                                                                                 Data.IntMap.Lazy
                                                                                                 Data.IntMap.Strict
                                                                                                 Data.IntSet.Internal
                                                                                                 Data.Map
                                                                                                 Data.Map.Internal
                                                                                                 Data.Map.Internal.Debug
                                                                                                 Data.Map.Internal.DeprecatedShowTree
                                                                                                 Data.Map.Lazy
                                                                                                 Data.Map.Strict
                                                                                                 Data.Map.Strict.Internal
                                                                                                 Data.Set.Internal
                                                                                                 Utils.Containers.Internal.BitQueue
                                                                                                 Utils.Containers.Internal.BitUtil
                                                                                                 Utils.Containers.Internal.PtrEquality
                                                                                                 Utils.Containers.Internal.StrictFold
                                                                                                 Utils.Containers.Internal.StrictMaybe
                                                                                                 Utils.Containers.Internal.StrictPair
Preprocessing test suite 'set-properties' for containers-0.5.10.2..
Building test suite 'set-properties' for containers-0.5.10.2..

<no location info>: warning: [-Wmissing-home-modules]
    These modules are needed for compilation but not listed in your .cabal file's other-modules: Data.IntSet
                                                                                                 Data.IntSet.Internal
                                                                                                 Data.Set
                                                                                                 Data.Set.Internal
                                                                                                 Utils.Containers.Internal.BitUtil
                                                                                                 Utils.Containers.Internal.PtrEquality
                                                                                                 Utils.Containers.Internal.StrictFold
                                                                                                 Utils.Containers.Internal.StrictPair

<no location info>: warning: [-Wmissing-home-modules]
    These modules are needed for compilation but not listed in your .cabal file's other-modules: Data.IntSet
                                                                                                 Data.IntSet.Internal
                                                                                                 Data.Set
                                                                                                 Data.Set.Internal
                                                                                                 Utils.Containers.Internal.BitUtil
                                                                                                 Utils.Containers.Internal.PtrEquality
                                                                                                 Utils.Containers.Internal.StrictFold
                                                                                                 Utils.Containers.Internal.StrictPair
Running 12 test suites...
```

This makes it quite difficult to see actual, substantive warnings that might appear. We should squash these warnings, either by adding the missing modules to `other-modules` in the right places or by suppressing them with `-Wno-missing-home-modules`.

**Comment by treeowl** [comment]
Yes, we should surely add missing things to other-modules.

On Aug 24, 2017 9:26 AM, "Ryan Scott" <notifications@github.com> wrote:

On a recent build of the containers test suites using GHC 8.2.1, I
encountered a veritable wall of warnings that were entirely due to
-Wmissing-home-modules:

$ cabal test
Preprocessing test suite 'seq-properties' for containers-0.5.10.2..
Building test suite 'seq-properties' for containers-0.5.10.2..

<no location info>: warning: [-Wmissing-home-modules]
    These modules are needed for compilation but not listed in your
.cabal file's other-modules: Data.Sequence

                          Data.Sequence.Internal

                          Utils.Containers.Internal.StrictPair

<no location info>: warning: [-Wmissing-home-modules]
    These modules are needed for compilation but not listed in your
.cabal file's other-modules: Data.Sequence

                          Data.Sequence.Internal

                          Utils.Containers.Internal.StrictPair
Preprocessing test suite 'intmap-strict-properties' for containers-0.5.10.2..
Building test suite 'intmap-strict-properties' for containers-0.5.10.2..

<no location info>: warning: [-Wmissing-home-modules]
    These modules are needed for compilation but not listed in your
.cabal file's other-modules: Data.IntMap.Internal

                          Data.IntMap.Internal.Debug

                          Data.IntMap.Internal.DeprecatedDebug

                          Data.IntMap.Strict

                          Data.IntSet

                          Data.IntSet.Internal

                          Utils.Containers.Internal.BitUtil

                          Utils.Containers.Internal.StrictFold

                          Utils.Containers.Internal.StrictPair

<no location info>: warning: [-Wmissing-home-modules]
    These modules are needed for compilation but not listed in your
.cabal file's other-modules: Data.IntMap.Internal

                          Data.IntMap.Internal.Debug

                          Data.IntMap.Internal.DeprecatedDebug

                          Data.IntMap.Strict

                          Data.IntSet

                          Data.IntSet.Internal

                          Utils.Containers.Internal.BitUtil

                          Utils.Containers.Internal.StrictFold

                          Utils.Containers.Internal.StrictPair
Preprocessing test suite 'map-strictness-properties' for containers-0.5.10.2..
Building test suite 'map-strictness-properties' for containers-0.5.10.2..

<no location info>: warning: [-Wmissing-home-modules]
    These modules are needed for compilation but not listed in your
.cabal file's other-modules: Data.Map.Internal

                          Data.Map.Internal.Debug

                          Data.Map.Internal.DeprecatedShowTree

                          Data.Map.Strict

                          Data.Map.Strict.Internal

                          Data.Set.Internal

                          Utils.Containers.Internal.BitQueue

                          Utils.Containers.Internal.BitUtil

                          Utils.Containers.Internal.PtrEquality

                          Utils.Containers.Internal.StrictFold

                          Utils.Containers.Internal.StrictMaybe

                          Utils.Containers.Internal.StrictPair

<no location info>: warning: [-Wmissing-home-modules]
    These modules are needed for compilation but not listed in your
.cabal file's other-modules: Data.Map.Internal

                          Data.Map.Internal.Debug

                          Data.Map.Internal.DeprecatedShowTree

                          Data.Map.Strict

                          Data.Map.Strict.Internal

                          Data.Set.Internal

                          Utils.Containers.Internal.BitQueue

                          Utils.Containers.Internal.BitUtil

                          Utils.Containers.Internal.PtrEquality

                          Utils.Containers.Internal.StrictFold

                          Utils.Containers.Internal.StrictMaybe

                          Utils.Containers.Internal.StrictPair
Preprocessing test suite 'bitqueue-properties' for containers-0.5.10.2..
Building test suite 'bitqueue-properties' for containers-0.5.10.2..

<no location info>: warning: [-Wmissing-home-modules]
    These modules are needed for compilation but not listed in your
.cabal file's other-modules: Utils.Containers.Internal.BitQueue

                          Utils.Containers.Internal.BitUtil

<no location info>: warning: [-Wmissing-home-modules]
    These modules are needed for compilation but not listed in your
.cabal file's other-modules: Utils.Containers.Internal.BitQueue

                          Utils.Containers.Internal.BitUtil
Preprocessing test suite 'map-lazy-properties' for containers-0.5.10.2..
Building test suite 'map-lazy-properties' for containers-0.5.10.2..

<no location info>: warning: [-Wmissing-home-modules]
    These modules are needed for compilation but not listed in your
.cabal file's other-modules: Data.Map.Internal

                          Data.Map.Internal.Debug

                          Data.Map.Internal.DeprecatedShowTree

                          Data.Map.Lazy

                          Data.Map.Merge.Lazy

                          Data.Set

                          Data.Set.Internal

                          Utils.Containers.Internal.BitQueue

                          Utils.Containers.Internal.BitUtil

                          Utils.Containers.Internal.PtrEquality

                          Utils.Containers.Internal.StrictFold

                          Utils.Containers.Internal.StrictMaybe

                          Utils.Containers.Internal.StrictPair

<no location info>: warning: [-Wmissing-home-modules]
    These modules are needed for compilation but not listed in your
.cabal file's other-modules: Data.Map.Internal

                          Data.Map.Internal.Debug

                          Data.Map.Internal.DeprecatedShowTree

                          Data.Map.Lazy

                          Data.Map.Merge.Lazy

                          Data.Set

                          Data.Set.Internal

                          Utils.Containers.Internal.BitQueue

                          Utils.Containers.Internal.BitUtil

                          Utils.Containers.Internal.PtrEquality

                          Utils.Containers.Internal.StrictFold

                          Utils.Containers.Internal.StrictMaybe

                          Utils.Containers.Internal.StrictPair
Preprocessing test suite 'intmap-strictness-properties' for
containers-0.5.10.2..
Building test suite 'intmap-strictness-properties' for containers-0.5.10.2..

<no location info>: warning: [-Wmissing-home-modules]
    These modules are needed for compilation but not listed in your
.cabal file's other-modules: Data.IntMap.Internal

                          Data.IntMap.Internal.DeprecatedDebug

                          Data.IntMap.Strict

                          Data.IntSet.Internal

                          Utils.Containers.Internal.BitUtil

                          Utils.Containers.Internal.StrictFold

                          Utils.Containers.Internal.StrictPair

<no location info>: warning: [-Wmissing-home-modules]
    These modules are needed for compilation but not listed in your
.cabal file's other-modules: Data.IntMap.Internal

                          Data.IntMap.Internal.DeprecatedDebug

                          Data.IntMap.Strict

                          Data.IntSet.Internal

                          Utils.Containers.Internal.BitUtil

                          Utils.Containers.Internal.StrictFold

                          Utils.Containers.Internal.StrictPair
Preprocessing test suite 'intset-properties' for containers-0.5.10.2..
Building test suite 'intset-properties' for containers-0.5.10.2..

<no location info>: warning: [-Wmissing-home-modules]
    These modules are needed for compilation but not listed in your
.cabal file's other-modules: Data.IntSet

                          Data.IntSet.Internal

                          Data.Set

                          Data.Set.Internal

                          Utils.Containers.Internal.BitUtil

                          Utils.Containers.Internal.PtrEquality

                          Utils.Containers.Internal.StrictFold

                          Utils.Containers.Internal.StrictPair

<no location info>: warning: [-Wmissing-home-modules]
    These modules are needed for compilation but not listed in your
.cabal file's other-modules: Data.IntSet

                          Data.IntSet.Internal

                          Data.Set

                          Data.Set.Internal

                          Utils.Containers.Internal.BitUtil

                          Utils.Containers.Internal.PtrEquality

                          Utils.Containers.Internal.StrictFold

                          Utils.Containers.Internal.StrictPair
Preprocessing test suite 'intmap-lazy-properties' for containers-0.5.10.2..
Building test suite 'intmap-lazy-properties' for containers-0.5.10.2..

<no location info>: warning: [-Wmissing-home-modules]
    These modules are needed for compilation but not listed in your
.cabal file's other-modules: Data.IntMap.Internal

                          Data.IntMap.Internal.Debug

                          Data.IntMap.Internal.DeprecatedDebug

                          Data.IntMap.Lazy

                          Data.IntSet

                          Data.IntSet.Internal

                          Utils.Containers.Internal.BitUtil

                          Utils.Containers.Internal.StrictFold

                          Utils.Containers.Internal.StrictPair

<no location info>: warning: [-Wmissing-home-modules]
    These modules are needed for compilation but not listed in your
.cabal file's other-modules: Data.IntMap.Internal

                          Data.IntMap.Internal.Debug

                          Data.IntMap.Internal.DeprecatedDebug

                          Data.IntMap.Lazy

                          Data.IntSet

                          Data.IntSet.Internal

                          Utils.Containers.Internal.BitUtil

                          Utils.Containers.Internal.StrictFold

                          Utils.Containers.Internal.StrictPair
Preprocessing test suite 'map-strict-properties' for containers-0.5.10.2..
Building test suite 'map-strict-properties' for containers-0.5.10.2..

<no location info>: warning: [-Wmissing-home-modules]
    These modules are needed for compilation but not listed in your
.cabal file's other-modules: Data.Map.Internal

                          Data.Map.Internal.Debug

                          Data.Map.Internal.DeprecatedShowTree

                          Data.Map.Merge.Strict

                          Data.Map.Strict

                          Data.Map.Strict.Internal

                          Data.Set

                          Data.Set.Internal

                          Utils.Containers.Internal.BitQueue

                          Utils.Containers.Internal.BitUtil

                          Utils.Containers.Internal.PtrEquality

                          Utils.Containers.Internal.StrictFold

                          Utils.Containers.Internal.StrictMaybe

                          Utils.Containers.Internal.StrictPair

<no location info>: warning: [-Wmissing-home-modules]
    These modules are needed for compilation but not listed in your
.cabal file's other-modules: Data.Map.Internal

                          Data.Map.Internal.Debug

                          Data.Map.Internal.DeprecatedShowTree

                          Data.Map.Merge.Strict

                          Data.Map.Strict

                          Data.Map.Strict.Internal

                          Data.Set

                          Data.Set.Internal

                          Utils.Containers.Internal.BitQueue

                          Utils.Containers.Internal.BitUtil

                          Utils.Containers.Internal.PtrEquality

                          Utils.Containers.Internal.StrictFold

                          Utils.Containers.Internal.StrictMaybe

                          Utils.Containers.Internal.StrictPair
Preprocessing test suite 'intset-strictness-properties' for
containers-0.5.10.2..
Building test suite 'intset-strictness-properties' for containers-0.5.10.2..

<no location info>: warning: [-Wmissing-home-modules]
    These modules are needed for compilation but not listed in your
.cabal file's other-modules: Data.IntSet

                          Data.IntSet.Internal

                          Utils.Containers.Internal.BitUtil

                          Utils.Containers.Internal.StrictFold

                          Utils.Containers.Internal.StrictPair

<no location info>: warning: [-Wmissing-home-modules]
    These modules are needed for compilation but not listed in your
.cabal file's other-modules: Data.IntSet

                          Data.IntSet.Internal

                          Utils.Containers.Internal.BitUtil

                          Utils.Containers.Internal.StrictFold

                          Utils.Containers.Internal.StrictPair
Preprocessing test suite 'deprecated-properties' for containers-0.5.10.2..
Building test suite 'deprecated-properties' for containers-0.5.10.2..

<no location info>: warning: [-Wmissing-home-modules]
    These modules are needed for compilation but not listed in your
.cabal file's other-modules: Data.IntMap

                          Data.IntMap.Internal

                          Data.IntMap.Internal.DeprecatedDebug

                          Data.IntMap.Lazy

                          Data.IntMap.Strict

                          Data.IntSet.Internal

                          Data.Map

                          Data.Map.Internal

                          Data.Map.Internal.Debug

                          Data.Map.Internal.DeprecatedShowTree

                          Data.Map.Lazy

                          Data.Map.Strict

                          Data.Map.Strict.Internal

                          Data.Set.Internal

                          Utils.Containers.Internal.BitQueue

                          Utils.Containers.Internal.BitUtil

                          Utils.Containers.Internal.PtrEquality

                          Utils.Containers.Internal.StrictFold

                          Utils.Containers.Internal.StrictMaybe

                          Utils.Containers.Internal.StrictPair

<no location info>: warning: [-Wmissing-home-modules]
    These modules are needed for compilation but not listed in your
.cabal file's other-modules: Data.IntMap

                          Data.IntMap.Internal

                          Data.IntMap.Internal.DeprecatedDebug

                          Data.IntMap.Lazy

                          Data.IntMap.Strict

                          Data.IntSet.Internal

                          Data.Map

                          Data.Map.Internal

                          Data.Map.Internal.Debug

                          Data.Map.Internal.DeprecatedShowTree

                          Data.Map.Lazy

                          Data.Map.Strict

                          Data.Map.Strict.Internal

                          Data.Set.Internal

                          Utils.Containers.Internal.BitQueue

                          Utils.Containers.Internal.BitUtil

                          Utils.Containers.Internal.PtrEquality

                          Utils.Containers.Internal.StrictFold

                          Utils.Containers.Internal.StrictMaybe

                          Utils.Containers.Internal.StrictPair
Preprocessing test suite 'set-properties' for containers-0.5.10.2..
Building test suite 'set-properties' for containers-0.5.10.2..

<no location info>: warning: [-Wmissing-home-modules]
    These modules are needed for compilation but not listed in your
.cabal file's other-modules: Data.IntSet

                          Data.IntSet.Internal

                          Data.Set

                          Data.Set.Internal

                          Utils.Containers.Internal.BitUtil

                          Utils.Containers.Internal.PtrEquality

                          Utils.Containers.Internal.StrictFold

                          Utils.Containers.Internal.StrictPair

<no location info>: warning: [-Wmissing-home-modules]
    These modules are needed for compilation but not listed in your
.cabal file's other-modules: Data.IntSet

                          Data.IntSet.Internal

                          Data.Set

                          Data.Set.Internal

                          Utils.Containers.Internal.BitUtil

                          Utils.Containers.Internal.PtrEquality

                          Utils.Containers.Internal.StrictFold

                          Utils.Containers.Internal.StrictPair
Running 12 test suites...

This makes it quite difficult to see actual, substantive warnings that
might appear. We should squash these warnings, either by adding the missing
modules to other-modules in the right places or by suppressing them with
-Wno-missing-home-modules.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/haskell/containers/issues/434>, or mute the thread
