### ISSUE TITLE
add ordNub somewhere in containers

### ISSUE THREAD

**Issue by gbaz** [haskell/containers#439]
After dropping the standard ordNub (i.e. this: https://github.com/nh2/haskell-ordnub) code into a codebase for the zillionth time I went and checked the history of why it never made it into a standard lib. It can't go into base because it requires containers or reimplementing `Set` just for this purpose, which is silly. It doesn't necessarily belong in the `Data.Set` module. But perhaps it could fall into a new module, like `Data.SetUtils` or `Data.ContainerUtils` or the like? Anyway, this package is the most natural place for it to live, even if it doesn't quite fit, and everyone ends up using it everywhere, so it would be really nice to just have a standard for it...

**Comment by treeowl** [comment]
There are actually two containers supporting `nub`-like operations with
different constraints: `Data.Set` and `Data.IntSet`. Does it make sense to
put these operations in? I dunno. It feels like a bit of a strange place. I
suggest you raise the question of where these things belong (and what they
should be called) on the libraries list.

**Comment by nh2** [comment]
Libraries discussion: https://mail.haskell.org/pipermail/libraries/2017-October/028269.html

**Comment by gbaz** [comment]
As I wrote there:

"The discussion period is well over and it seems the consensus is for
adding this, basically as David proposes.  -- i.e. ordNub, and
ordNubOn, but not ordNubBy. (and also the -1 variants and the int-
variants). I think the only module name proposed to add them to is
Data.Containers.ListUtils, so I guess that stands.

David -- are you up for adding these, or would you like someone else
(i.e. me) to prepare a patch?"

**Comment by treeowl** [comment]
Either way.

**Comment by treeowl** [comment]
We'd better get to this.

**Comment by gbaz** [comment]
See PR
