### ISSUE TITLE
Missing powerSet

### ISSUE THREAD

**Issue by ekmett** [haskell/containers#442]
```
powerSet :: Set a -> Set (Set a)
```

can be efficiently implemented with Set internals with no constraint necessary, but can't be as efficiently implemented externally.

**Comment by treeowl** [comment]
That's a nice puzzle. I don't know how to solve it off the top of my head.
Since sets are strict, the big trick must be to maximize sharing. I'll
think about this for a bit, but if I run into trouble I'll ask for help.

**Comment by ekmett** [comment]
Here's a reference implementation you can feel free to improve upon:

```haskell
powerSet :: Set a -> Set (Set a)
powerSet xs0 = insertMin empty (foldr' step Tip xs0) where
  step x pxs = insertMin (singleton x) (insertMin x `mapMonotonic` pxs) `glue` pxs
```

This popped up when writing some NFA <-> DFA code.

**Comment by ekmett** [comment]
Once you start doing set-theoretic operations with `Set`: these also pop up:

```haskell
newtype Merge a = Merge { getMerge :: Set a }

instance Monoid (Merge a) where
  mempty = Merge empty
  mappend (Merge m) (Merge n) = Merge (merge m n)

product :: Set a -> Set b -> Set (a, b)
product as bs = getMerge $ foldMap (\a -> Merge $ mapMonotonic (a,) bs) as

sum :: Set a -> Set b -> Set (Either a b)
sum as bs = merge (mapMonotonic Left as) (mapMonotonic Right bs)
```

not attached to the names (in fact I'm against the names i used.)

**Comment by treeowl** [comment]
I'll be happy to add `powerSet`, because the name is obvious. Do you have a proof/argument for the balance being okay, or just tests? I'm not very comfortable with the latter for something like this.

The other names are no good, and I don't understand why you'd want those functions. Each of them seems to turn an efficient representation of a set into an inefficient one.

**Comment by treeowl** [comment]
Oh, I guess the size difference is always just 1, so that should be fine.

**Comment by ekmett** [comment]
Yeah, the proof for `powerSet` is pretty easy.

The `sum` and `product` I gave there arise when you go to compute the set of states for things like NFA intersections and unions respectively. `powerSet` arises in the naive encoding of the NFA -> DFA translation.

I definitely don't like the names, but I wind up forced to use the operations, they are cheaper than the arbitrary unions you'd get if you tried to implement them without knowledge of ordering using `merge`, and they are just non-trivial enough to implement to raise them over the Fairbairn threshold in my eyes.

**Comment by treeowl** [comment]
I still don't understand why you'd need to actually take the sum or
product, rather than using something generic-trie like.

**Comment by ekmett** [comment]
A trie would bias the tree making me pay proportional to path lengths, which after several operations can get wildly lopsided, rather than know my path length is bounded by the number of elements.
