### ISSUE TITLE
Add Data.IntMap.!? operator

### ISSUE THREAD

**Issue by m-renaud** [haskell/containers#453]
# What

The addition of the `!?` operator to `IntMap`.

The function

```
(!?) :: IntMap a -> Key -> Maybe a
```

# Why

This function was added to the Data.Map API but not the IntMap API. I'm assuming this was simply an oversight (let me know if there was a specific reason it wasn't included).

# How

The Pull Request (to be added shortly) contains the straight-forward implementation of the `!?` operator on `IntMap`, with test cases.

**Comment by treeowl** [comment]
Agreed for IntMap; left out by mistake. What are you saying about Set?
Adding such a thing for Set has proven controversial on the libraries list,
and will not be done without some community consensus.

**Comment by m-renaud** [comment]
> Agreed for IntMap; left out by mistake
Cool, will send a PR soon.

> What are you saying about Set?
Disregard that. Accidentally hit enter before I had finished the issue body, copied some words from another issue which contained Set.

**Comment by m-renaud** [comment]
Also, I noticed that in `Data.Map.Internal` that `!` and `!?` are marked as `INLINE` but that annotation is missing from the IntMap implementation. Should I add that here as well?

https://github.com/haskell/containers/blob/master/Data/Map/Internal.hs#L438

**Comment by treeowl** [comment]
I'm not sure about the inlining thing. Maybe the pragmas should be removed in `Data.Map`; GHC should inline such a trivial thing anyway, no?

**Comment by m-renaud** [comment]
My understanding (mostly from reading about performance) is that GHC _should_ do a good job inlining such functions, but I feel like in the past I've read blog posts about adding an INLINE pragma being required in some cases. My vote would be to omit them unless benchmarks show that they should be added, but at that point it would probably be better to file a GHC bug.

**Comment by m-renaud** [comment]
Unrelated: Are there instructions on how to run the tests locally? I've tried various versions of cabal, sandboxes, etc. but its never able to satisfy the dependencies needed to run the tests.

**Comment by treeowl** [comment]
I don't remember if there are directions; some might have been added a year
or two ago. You'll have to install the test dependencies manually. I think
you may also have to skip cabal configure --enable-tests, but I don't
remember for sure.

**Comment by sjakobi** [comment]
> Are there instructions on how to run the tests locally?

`stack test` kind of works but will recompile a lot of test dependencies after each change.

**Comment by m-renaud** [comment]
`stack init && stack test` appears to have worked (with tonnes of recompiles as you mentioned), thanks! I was unable to get the dependencies installed properly with cabal, maybe consider adding a `CONTRIBUTORS.md` doc with that advice. Anyways, all the tests pass locally now and have been pushed to the branch. Sorry for the noise in the pull request, I was using that as my test runner.

**Comment by m-renaud** [comment]
FYI sent Pull Request #455 to add a CONTRIBUTING.md file with instructions for building and testing the containers package.
