### ISSUE TITLE
Cannot use stack for lts > 7.24

### ISSUE THREAD

**Issue by m-renaud** [haskell/containers#458]
The last Stackage LTS which included the ChasingBottoms package was 7.24, using any more recent LTS does not include this which causes an error on initialization.

```shell
$ stack init --resolver lts-10.0
...
Resolver 'lts-10.0' does not have all the packages to match your requirements.
    ChasingBottoms not found
        - containers requires -any
...
$ stack init --resolver lts-9.20
...
Selected resolver: lts-9.20
Resolver 'lts-9.20' does not have all the packages to match your requirements.
    ChasingBottoms not found
        - containers requires -any
...
$ stack init --resolver lts-7.24
...
Initialising configuration using resolver: lts-7.24
Total number of user packages considered: 1
Writing configuration to file: stack.yaml
All done.
```

I looked at the [hackage page for ChasingBottoms](https://hackage.haskell.org/package/ChasingBottoms) but there was no email address to contact the maintainer (Nils Anders Danielsson) and the code isn't hosted on GitHub (just a Darcs repo on a server) so there's no way to file an issue.

Getting in contact with the maintainer and seeing if they can get it incorporated into the Stackage LTS is probably the best way forward.

**Comment by treeowl** [comment]
The maintainer of `ChasingBottoms` provides [contact info](http://www.cse.chalmers.se/~nad/contact.html) on his website. But he may not be responsible for this Stackage business. I suspect the right approach for *us* is to add an extra dependency in the `stack.yaml`, but you're welcome to try to find out why the package is no longer included.

**Comment by m-renaud** [comment]
>  provides contact info on his website

Doh, sorry, I should have looked closer.

>  the right approach for us is to add an extra dependency in the stack.yaml

Yup, that would work :) There isn't currently a `stack.yaml` in the repo, should I just go ahead and add one that's properly configured?

**Comment by treeowl** [comment]
That would probably be good, I imagine.
