### ISSUE TITLE
Cannot configure containers with tests and benchmarks enabled

### ISSUE THREAD

**Issue by m-renaud** [haskell/containers#462]
I'm not sure if this is a containers problem or cabal problem, but `cabal configure --enable-tests --enable-benchmarks` is unable to solve the constraints:

```
$ cabal configure --enable-tests --enable-benchmarks

Resolving dependencies...
Warning: solver failed to find a solution:
Could not resolve dependencies:
rejecting: containers-0.5.10.2:!bench (constraint from config file, command
line flag, or user target requires opposite flag selection)
trying: containers-0.5.10.2:*bench
unknown package: random (dependency of containers-0.5.10.2:*bench)
Dependency tree exhaustively searched.
Trying configure anyway.
Configuring containers-0.5.10.2...
cabal: Encountered missing dependencies:
ChasingBottoms -any,
HUnit -any,
QuickCheck >=2.7.1,
criterion >=0.4.0 && <1.3,
random <1.2,
test-framework >=0.3.3,
test-framework-hunit -any,
test-framework-quickcheck2 >=0.2.9
```

This causes our instructions in `CONTRIBUTING.md` to be more complex than they should be.

**Comment by hvr** [comment]
kinda related discussion at https://github.com/haskell/cabal/issues/4981#issuecomment-354320341

**Comment by sjakobi** [comment]
With regards to benchmarks I think we should switch from `criterion` to  `gauge` once a new release of gauge has been made. The upstream version of gauge has neither direct nor transitive dependencies on `containers`.

**Comment by treeowl** [comment]
@sjakobi, how does `gauge` compare to `criterion`? What else do we gain/lose? How hard would it be to port the existing benchmark suite?

**Comment by treeowl** [comment]
@sjakobi, I took a glance at `gauge`. I think it would be good to *add* support for it, but it's clearly less capable than `criterion`, so I'm reluctant to make a hard switch. I also must say I'm not entirely sold on the *way* it cuts down dependencies, seeming to focus for now on human-readable output. But I can probably be convinced.

**Comment by sjakobi** [comment]
gauge is just fork of criterion with much fewer dependencies and a few additional features.

> how does gauge compare to criterion?

See https://github.com/vincenthz/hs-gauge#features-compared-to-criterion.

> What else do we gain/lose?

gauge only supports GHC versions >= 7.8.

> How hard would it be to port the existing benchmark suite?

So far it's been as simple as replacing the imports of `Criterion` and `Criterion.Main` with `import Gauge`.

> it's clearly less capable than criterion

What features do you miss the most?

**Comment by sjakobi** [comment]
Here's a trick for building tests and benchmarks with `cabal`:

```
mv containers.cabal kontainers.cabal
sed -i 's/name: containers/name: kontainers/1' kontainers.cabal 
sed -i 's/containers,/kontainers,/g' kontainers.cabal
```

This renames the package to `kontainers`, removing the circular dependency.

**Comment by sjakobi** [comment]
This has been fixed in https://github.com/haskell/containers/pull/626.

To avoid the test dependencies getting rebuilt with every library change, it's enough to remove `containers` from the `packages` stanza in the `cabal.project`. It would be good to document this properly though…

**Comment by sjakobi** [comment]
@m-renaud Can this issue be closed?
