### ISSUE TITLE
Cut the fromList clutter

### ISSUE THREAD

**Issue by treeowl** [haskell/containers#479]
I think all the `fromList` invocations all over the docs seem very noisy, and make it harder to see at a glance what's really important. How can we fix this? In theory, I'd probably want sequences, maps, and sets displayed using "weird brackets". Something like `⟦1,2,3⟧` for a sequence, `⦃7,8,12⦄` for a set, and perhaps `⟪(1,'a'), (2, 'b')⟫` for a map. There are two problems:

1. I don't know a particularly pleasant way to actually write those into the docs. Because nothing can ever be as easy as it should be, I've always had trouble with the way Unicode is displayed in VIM on my terminal (the Unicode characters make other things shift around in weird ways with cursor movement). Maybe there's a way to fix that; I dunno. But in any case, entering Unicode is always somewhat annoying. I wonder if we could use some kind of preprocessor to turn `\[` and `\]` into the bracket appropriate to the module in question. That would be quite tolerable. Those are usually used as display math delimiters, but I don't think we need any such displays.

2. Users may not have the fonts they need to display the weird brackets, in which case everything will be terrible. Maybe there's a way to work around that with a Haddock CSS customization to use webfonts or something, but the customization doesn't seem to be very well documented and I don't know much about this web stuff.

**Comment by jwaldmann** [comment]
related discussion: https://mail.haskell.org/pipermail/haskell-cafe/2018-January/128403.html

* "moving the set/map/sequence construction to a line above and assigning it to a
variable is a good compromise;" https://mail.haskell.org/pipermail/haskell-cafe/2018-January/128411.html
* [ fromList ] "are maybe somewhat verbose and distracting, but they are also
explicit (compared to OverloadedLists) and do not introduce new stuff
(compared to funny brackets). I would leave it as it is." https://mail.haskell.org/pipermail/haskell-cafe/2018-January/128408.html

**Comment by treeowl** [comment]
I don't really like the idea of assigning things to variables in this context. But it seems the people have spoken; I'll close this ticket.
