### ISSUE TITLE
Add set-theoretic IntSet operations

### ISSUE THREAD

**Issue by treeowl** [haskell/containers#482]
I've added `powerSet`, `disjointUnion`, and `cartesianProduct` to `Data.Set` at @ekmett's urging. We should add similar functions to `Data.IntSet`.

**Comment by Zemyla** [comment]
How do they work, considering an `IntSet` can only hold an `Int`? I assume it's something like this:

```haskell
cartesianProduct :: ((Key, Key) -> Key) -> IntSet -> IntSet
disjointUnion :: (Either Key Key -> Key) -> IntSet -> IntSet
powerSet :: (IntSet -> Key) -> IntSet -> IntSet
```

If we do that, though, we should probably change the names to `cartesianProductWith`, `disjointUnionWith`, and `powerSetWith` so we don't have two different signatures for each name.

**Comment by treeowl** [comment]
@Zemyla I'm not buying any of those. I think I just didn't think this through enough. I'll close this, but feel free to let me know if there's anything useful in this space.
