### ISSUE TITLE
Make ReadTheDocs point to the right place

### ISSUE THREAD

**Issue by treeowl** [haskell/containers#483]
https://haskell-containers.readthedocs.io/en/latest/ isn't pointed at the right file. Please fix that. Additionally, @wrengr and I should probably have access to the documentation administration, just in case you disappear unexpectedly.

**Comment by m-renaud** [comment]
Fixed. Can the two of you create an account at https://readthedocs.org and let me know what your usernames are?

**Comment by treeowl** [comment]
I'm dfeuer. Dunno about Wren.

**Comment by m-renaud** [comment]
Added you as a maintainer, you can see the project dashboard at https://readthedocs.org/projects/haskell-containers/. I'm going to close this issue, when Wren creates an account I'll add her as a maintainer as well.

**Comment by m-renaud** [comment]
So, it appears that I don't have permission to setup webhooks for the haskell organization. I'm not sure if there's special permissions that I or one of the other maintainers need to have to configure them. As it currently stands the docs won't be rebuilt when a new commit to the docs/ directory is made.

**Comment by treeowl** [comment]
Okay.

On Jan 10, 2018 1:30 PM, "Matt Renaud" <notifications@github.com> wrote:

So, it appears that I don't have permission to setup webhooks for the
haskell organization. I'm not sure if there's special permissions that I or
one of the other maintainers need to have to configure them. As it
currently stands the docs won't be rebuilt when a new commit to the docs/
directory is made.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/haskell/containers/issues/483#issuecomment-356693335>,
or mute the thread
