### ISSUE TITLE
Add sortOn for Data.Sequence

### ISSUE THREAD

**Issue by treeowl** [haskell/containers#499]
```haskell
sortOn, unstableSortOn :: Ord b => (a -> b) -> Seq a -> Seq a
sortOn f xs = fmap fst . sortBy (compare `on` snd) $ fmap (\x -> (x, f x)) xs
unstableSortOn f xs = fmap fst . unstableSortBy (compare `on` snd) $ fmap (\x -> (x, f x)) xs
```

But it should be quite a bit faster to build these directly over the heap sort instead of mapping twice. @oisdk, do you think you could write these up real quick, or should I give it a go?

**Comment by oisdk** [comment]
I can try it! I should be able to use the standard functions for generating the heap

**Comment by oisdk** [comment]
If we apply these functions while we build the heap, would that expose the opportunity for fusion in cases like:

```haskell
sort . fmap f
fmap f . sort
```

And so on? I could imagine a rule being something like:

```haskell
sortBy cmp (fmap f (Seq xs)) =
    maybe
        (Seq EmptyT)
        (execState (replicateA (size xs) (popMinS cmp)))
        (toPQS cmp (\s (Elem x) -> PQS s (f x) Nl) 0 xs)
```

And on the other side something like:

```haskell
fmap f (sortBy cmp (Seq xs)) =
    maybe
        (Seq EmptyT)
        (execState (replicateA (size xs) (fmap f (popMinS cmp))))
        (toPQS cmp (\s (Elem x) -> PQS s x Nl) 0 xs)
```

**Comment by treeowl** [comment]
Sounds plausible. Be sure to use fmapSeq in your rules, and use a phased
INLINABLE for the sort. Make sure it doesn't hurt when it doesn't apply.
