### ISSUE TITLE
IntSetValidity: commonPrefix too loose

### ISSUE THREAD

**Issue by nomeata** [haskell/containers#522]
This code:
```
-- Invariant: Prefix is the common high-order bits that all elements share to
--            the left of the Mask bit.
commonPrefix :: IntSet -> Bool
commonPrefix t =
  case t of
    Nil -> True
    Tip _ _ -> True
    b@(Bin p _ _ _) -> all (sharedPrefix p) (elems b)
  where
    sharedPrefix :: Prefix -> Int -> Bool
    sharedPrefix p a = 0 == (p `xor` (p .&. a))
```
is too weak, I believe: It checks only that the outermost prefix is correct, but not of the `Bin`’s inside the left and right tree.

Maybe 
```
-- Invariant: Prefix is the common high-order bits that all elements share to
--            the left of the Mask bit.
commonPrefix :: IntSet -> Bool
commonPrefix t =
  case t of
    Nil -> True
    Tip _ _ -> True
    b@(Bin p _ l r) -> all (sharedPrefix p) (elems b) && commonPrefix l && commonPrefix r
  where
    sharedPrefix :: Prefix -> Int -> Bool
    sharedPrefix p a = 0 == (p `xor` (p .&. a))
```
would be better?

**Comment by nomeata** [comment]
Isn’t `0 == (p `xor` (p .&. a))` just a complicate way of writing `p == p .&. a`?

**Comment by m-renaud** [comment]
> Isn’t 0 == (pxor(p .&. a))  just a complicated way of writing p == p .&. a?

Yes, yes it is :P 

I'll have to take a closer look at your updated commonPrefix tonight/tommorow, thanks for bringing this up!

**Comment by m-renaud** [comment]
Yup, you're right. I'll send a PR when I get home from work tonight, good catch!

**Comment by nomeata** [comment]
Same with `maskRespected`.

**Comment by m-renaud** [comment]
Sorry for the delay, was really busy last week. The PR referenced above fixes these issues. Thanks again for pointing these out :)
