### ISSUE TITLE
Optimize Data.Graph.indegree

### ISSUE THREAD

**Issue by m-renaud** [haskell/containers#533]
The current implementation looks incredibly inefficient:

```haskell
indegree  = outdegree . transposeG
```

We should add benchmarks and optimize the implementation.

**Comment by treeowl** [comment]
If I read it right, `Data.Array.accumArray` is accidentally too lazy to do the trick, and we'll have to do it by hand. I just filled https://ghc.haskell.org/trac/ghc/ticket/14785

**Comment by treeowl** [comment]
Side note: the result type is unfortunate. This function should really produce an unboxed array. Dealing with a boxed one just adds useless allocation and indirection while annoying the garbage collector with a bunch of pointer mutation.
