### ISSUE TITLE
Traversal order of Map/IntMap/Set

### ISSUE THREAD

**Issue by merijn** [haskell/containers#535]
A lot of code relies on the assumption that the traversals/folds of containers happen in ascending key order, however nowhere does the documentation promise this. If this is something people SHOULD be able to rely on, it should probably be documented somewhere.

**Comment by treeowl** [comment]
This is a promise we keep, and I think we should make it too. We have little if any incentive to leave open the possibility of other traversal orders for these particular data structures, and users surely appreciate having something predictable.

Side note: the wild traversal order of `unordered-containers:Data.HashMap` has me wondering about the right way to document that module. A `HashMap` really doesn't just represent a map from keys to values; it represents a map from hashes to lists of key-value pairs in which each key hashes to the corresponding hash and the keys are unique. But that's a rather unfriendly description.
