### ISSUE TITLE
Infinite loop when benchmarking graphFromEdges with a cyclic graph

### ISSUE THREAD

**Issue by OlivierSohn** [haskell/containers#550]
While writing the benchmarks of #549, I discovered that if the benchmarked function returns a graph with cycles, it never finishes.

To reproduce, start from #549, and replace: 

```haskell
  mkNeighbour k distance
    | neighbour < n = Just neighbour
    | otherwise = Nothing
    where
      neighbour = k + distance
```

with

```haskell
  mkNeighbour k distance
    | neighbour < n && neighbour >= 0 = Just neighbour
    | otherwise = Nothing
    where
      neighbour
        | even distance = k + quot distance 2
        | otherwise = k - quot distance 2
```

to make created graphs ~~acyclic~~cyclic.

**Comment by OlivierSohn** [comment]
I'm pasting here a comment from @snowleopard made on another thread, related to this issue, suggesting a way to analyze this bug:

> Hey @OlivierSohn! Thanks, that's good to know. Could you test Data.Graph on cyclic graphs by writing a custom function for fully evaluating it instead of relying on rnf?

**Comment by treeowl** [comment]
This sounds like a problem. What "other thread" are you talking about?

**Comment by OlivierSohn** [comment]
This one : https://github.com/snowleopard/alga/issues/14

**Comment by treeowl** [comment]
So have you checked with a custom `rnf`? Do we know if the problem is with graph creation or just with the fact that `rnf` doesn't make sense for `Graph`?

**Comment by treeowl** [comment]
I mean, is this really a bug in `Data.Graph`, or is this a bug in your benchmark? I'm not so clear on what the story is.

**Comment by OlivierSohn** [comment]
I believe the benchmarks is ok, and it's a bug in the library. It's easily reproducible (see hereabove the description of the issue).

I won't have the time to investigate, though.

**Comment by nobrakal** [comment]
Hi,

I can't reproduce the bug: with the modification you wrote, all benchmarks ended successfully.

Anyway, I tried with containers-0.5.11.0:
```Haskell
main :: IO ()
main = defaultMain [bch]
  where
    bch = bench "cycle" $ nf graphFromEdges [('a',0,[1]), ('b',1,[0])] 
```
Which end also successfully.

I am doing anything wrong ?

@treeowl Why `rnf` doesn't make sens for graph ?

Ps: 
I think it is as mistype, but with your instructions to reproduce, you wrote

> to make created graphs acyclic.

Is it to make graph *cyclic* ?

**Comment by OlivierSohn** [comment]
So I can't reproduce it either, I think I must have made a mistake in an earlier version of the benchmark (but I can't be sure of that because I didn't version control it at that time.)

Hence, I'll close the issue. Sorry for the noise induced by this!
