### ISSUE TITLE
Data.Graph.stronglyConnComp : document ordering

### ISSUE THREAD

**Issue by jwaldmann** [haskell/containers#561]
It says "topologically sorted" but the output order seems reversed w.r.t. my expectation.

For a graph with edges 0 -> 1 -> 2, we get [2,1,0]
```
Prelude Data.Graph> stronglyConnComp [(0,0,[1]),(1,1,[2]),(2,2,[])]
[AcyclicSCC 2,AcyclicSCC 1,AcyclicSCC 0]
```

**Comment by treeowl** [comment]
Huh .... that is surprising. Do you want to submit a PR to document that oddity?

**Comment by jwaldmann** [comment]
Will do.

**Comment by jwaldmann** [comment]
I was hoping to find a reason for this in the paper, but I found that the implementation differs from the paper, and the code in the paper computes the expected result.

The paper http://citeseerx.ist.psu.edu/viewdoc/summary?doi=10.1.1.52.6526 has (Algorithm 4)
```
scc g = dfs (transposeG g) (reverse (postOrd g))
```
while the code https://github.com/haskell/containers/blob/master/Data/Graph.hs has (Line 625)
```
scc g = dfs g (reverse (postOrd (transposeG g)))
```

**Comment by treeowl** [comment]
Surprising. Do we also have a function that does what the paper says? If
not, we might want to add one.

**Comment by jwaldmann** [comment]
I dug out some history:

* Data.Graph appears first at https://github.com/haskell/containers/commit/e6492fce6f70270acda18b5747f408d3add29724#diff-db47dc4bb340fd2bce42b46d02e53b00 (in 2003, that must have been ghc-6.0) with the comment "from GHC's Digraph"
* the code `dfs g (reverse (postOrd (transposeG g)))` is at `ghc/compiler/utils/Digraph.lhs` since at least ghc-3.02 (it's not in ghc-0.29, and I don't find 2.10 sources)

and it has a note  (see https://hackage.haskell.org/package/ghc-8.4.3/docs/src/Digraph.html#stronglyConnCompG) "the components are returned topologically sorted: later components depend on earlier ones, but not vice versa i.e. later components only have edges going from them to earlier ones."  (0.29 has different implementation but the same specification, with a note "... these cycles are topologically sorted, so that if there is an edge from cycle A to cycle B, then A occurs after B in the result list")

Well, that kind of "topological sortedness" is the opposite of what Cormen/Leiserson/Rivest define.

I still say we keep the code as is, and only add documentation as suggested in my PR. The work-around (add `reverse`) is trivial, and only adds linear cost - in the number of vertices, to something that is already linear, in the number of (vertices plus) edges.

**Comment by treeowl** [comment]
My question is whether the version that "natively" produces them the other way is a constant factor faster than adding a `reverse` on top. If so, I tend to think we should offer it. I imagine that would be determined best by benchmarking.

**Comment by jwaldmann** [comment]
I understand the question, but I don't have time to investigate. 

My proposal was just to document the behaviour. 

Everything else would mean an API change, and due process for that is more cumbersome? For good reasons - but I don't have the time for that (now).
