### ISSUE TITLE
Does containers-0.5.11 support GHC-8.6

### ISSUE THREAD

**Issue by phadej** [haskell/containers#565]
The bounds say it **does**, and `containers-0.5.11.0` seems to compile fine. I wonder if it's still supported configuration (and not just overlooked by `base <5` bound), as for sure there will be install-plans with `containers-0.5` and GHC-8.6?

**Comment by phadej** [comment]
Semi related:

```
                      8.6.1  8.4.3  8.2.2  8.0.2  7.10.3  7.8.4  7.6.3  7.4.2  7.2.2  7.0.4
containers-0.6.0.1/   OK     OK     OK     OK     OK      OK     OK     NO-IP  NO-IP  NO-IP
containers-0.5.11.0/  OK     OK     OK     OK     OK      OK     OK     OK     OK     OK   
containers-0.5.10.2/  FAIL   FAIL   OK     OK     OK      OK     OK     OK     OK     OK   
containers-0.5.10.1/  FAIL   FAIL   OK     OK     OK      OK     OK     OK     OK     OK   
containers-0.5.9.2/   FAIL   FAIL   OK     OK     OK      OK     OK     OK     OK     OK   
containers-0.5.9.1/   FAIL   FAIL   OK     OK     OK      OK     OK     OK     OK     OK   
containers-0.5.8.2/   FAIL   FAIL   OK     OK     OK      OK     OK     OK     OK     OK   
containers-0.5.8.1/   FAIL   FAIL   OK     OK     OK      OK     OK     OK     OK     OK   
containers-0.5.7.1/   OK     OK     OK     OK     OK      OK     OK     OK     OK     OK   
containers-0.5.7.0/   OK     OK     OK     OK     OK      OK     OK     OK     OK     OK   
containers-0.5.6.3/   NO-IP  NO-IP  NO-IP  NO-IP  OK      OK     OK     OK     OK     OK   
containers-0.5.6.2/   NO-IP  NO-IP  NO-IP  NO-IP  OK      OK     OK     OK     OK     OK   
containers-0.5.6.1/   NO-IP  NO-IP  NO-IP  NO-IP  OK      OK     OK     OK     OK     OK  
```

**Comment by phadej** [comment]
@treeowl sorry if I were unclear.

`containers-0.5.11.0` (in fact all of 0.5 series) has currently `base < 5` as the upper bound for `base`. I'm skeptical about this forward-compatibility: the matrix above highlights that (I'm going to add upper bounds to `containers-0.5.8.1--0.5.10.2` which are broken by Semigroup-Monoid change). I'd rather also add `base <4.12` for the rest today, before `base-4.12` is officially released.

I'm motivated by the fact, that it will make simpler to reason about dependencies:

> if you use `GHC-8.6`, then you have `containers >=0.6`

That would simplify providing wide support in the *boot-libs are the only dependencies* -kind of libraries (CPP logic etc.)

**Comment by treeowl** [comment]
If the versions work, we shouldn't exclude them artificially, IMO. But I
could be convinced otherwise by a more detailed explanation.

**Comment by phadej** [comment]
I have subtly bitten by assumptions that `transformers` aren't never upgraded (or especially degraded!), so had to resort to e.g. https://github.com/ekmett/recursion-schemes/blob/master/recursion-schemes.cabal#L64-L69 - but such shenanigans are anecdotal.

@treeowl could you make revisions to fix reds in https://matrix.hackage.haskell.org/package/containers

**Comment by treeowl** [comment]
I'm unclear on what more, if anything, needs to happen on this ticket.

**Comment by treeowl** [comment]
Since there hasn't been a response recently, I'm closing. @phadej, if there's still a problem, I'll be happy to reopen.
