### ISSUE TITLE
Containers-0.6.0.1 has some sort of bug in fromList

### ISSUE THREAD

**Issue by mrkkrp** [haskell/containers#568]
Hi, when enabling testing with GHC 8.6.1 for my package `wave` I've run into a strange failure. I reduced it to this minimal exmaple:

https://github.com/mrkkrp/containers-bug

As the readme says, if you run:

```
$ nix-shell --run "cabal new-run containers-bug"
```

then you'll see that

```
demonstrates a bug FAILED [1]

Failures:

  app/Main.hs:37:7:
  1) demonstrates a bug
       Falsifiable (after 5 tests and 1 shrink):
         [SpeakerBackRight,SpeakerBackLeft]
       expected: fromList [SpeakerBackLeft,SpeakerBackRight]
        but got: fromList [SpeakerBackRight,SpeakerBackLeft]

  To rerun use: --match "/demonstrates a bug/"

Randomized with seed 734218656

Finished in 0.0007 seconds
1 example, 1 failure
```

It could be that `QuickCheck` is to blame, but its definition of `Arbitrary (Set a)` has not changed and looks fine to me. Note that manual construction from list and then equality testing won't expose the bug, something trickier is going on here, but I don't know what.

**Comment by treeowl** [comment]
What actual list is failing the test? What happens if you feed that list in manually?

**Comment by mrkkrp** [comment]
It's not possible to reproduce manually (from what I tried). It's not about a concrete list that causes failure. I also could not reproduce in GHCi. But please take time and try to run the repro I provide. It does fail and it obviously should not. So there is a problem, but I don't have time to dig further.

```

**Comment by treeowl** [comment]
I believe you. Reading your test result more closely, I see these disturbing lines:

```
        expected: fromList [SpeakerBackLeft,SpeakerBackRight]
        but got: fromList [SpeakerBackRight,SpeakerBackLeft]

```

The second list *isn't sorted*, which means the `Set` structure was built wrong and we must have a bug in `fromList`. Presumably this only kicks in when the input has a certain structure wrt duplicates and order. Converting the broken `Set` to a list and back "repairs" it. What I want to know is what `xs` actually was when failure struck. I'd bet an ice cream cone it had some duplicates...

**Comment by mrkkrp** [comment]
> What I want to know is what xs actually was when failure struck.

I think `QuickCheck` prints it in the beginning of the error message? (I think it used to print arguments of `property` after the test, but this may have changed. So it should be this:

```
[SpeakerBackRight,SpeakerBackLeft]
```

But it doesn't work for manual reproduction, so I'm a bit confused.

**Comment by jwaldmann** [comment]
Can confirm. Tested with ghc-8.6.1, containers-0.6.0.1 and leancheck-0.7.5 (so it does not seem to depend on the testing framework). Error occurs:

* with ghc -O1 and -O2 (but not with -O0)
* and if data type has at least 9 elements

So, likely a bug in ghc's optimizer.

in some cases, input has duplicates, but not always.

**Comment by treeowl** [comment]
@jwaldmann, can we get a single reliable test case? It would be nice to be able to dig down deep instead of dealing with all this wildness. Also, does it happen for older containers versions before we started using pointer equality?

**Comment by benclifford** [comment]
I noticed that the lists aren't even always the same length. I tried:

```
length x `shouldBe` length y
```

and get:

```
Failures:

  app/Main.hs:37:7: 
  1) demonstrates a bug
       Falsifiable (after 15 tests and 5 shrinks):
         [SpeakerFrontCenter,SpeakerFrontCenter]
       expected: 1
        but got: 2
```

**Comment by minad** [comment]
I observed a similar issue with `Map.fromList` on 8.6.1.

**Comment by jwaldmann** [comment]
simplified test case, does not depend on extra libraries:
```
import qualified Data.Set as S
import Control.Monad

main = mapM_ print $ do
  let pos = [ minBound .. maxBound :: T ]
  x1 <- pos
  x2 <- pos
  let xs = [x1,x2]
      x = S.fromList xs
      y = S.fromList ( S.toList x )
  guard (x /= y)
  return (xs,x,y)

data T = T1 | T2 | T3 | T4 | T5 | T6 | T7 | T8 | T9
  deriving (Show, Read, Eq, Ord, Bounded, Enum)
```
gives this output (one line for each argument that makes the test fail)
```
([T2,T2],fromList [T2,T2],fromList [T2])
([T3,T2],fromList [T3,T2],fromList [T2,T3])
([T3,T3],fromList [T3,T3],fromList [T3])
([T4,T2],fromList [T4,T2],fromList [T2,T4])
([T4,T3],fromList [T4,T3],fromList [T3,T4])
([T4,T4],fromList [T4,T4],fromList [T4])
([T5,T2],fromList [T5,T2],fromList [T2,T5])
([T5,T3],fromList [T5,T3],fromList [T3,T5])
([T5,T4],fromList [T5,T4],fromList [T4,T5])
([T5,T5],fromList [T5,T5],fromList [T5])
([T6,T2],fromList [T6,T2],fromList [T2,T6])
([T6,T3],fromList [T6,T3],fromList [T3,T6])
([T6,T4],fromList [T6,T4],fromList [T4,T6])
([T6,T5],fromList [T6,T5],fromList [T5,T6])
([T6,T6],fromList [T6,T6],fromList [T6])
([T7,T2],fromList [T7,T2],fromList [T2,T7])
([T7,T3],fromList [T7,T3],fromList [T3,T7])
([T7,T4],fromList [T7,T4],fromList [T4,T7])
([T7,T5],fromList [T7,T5],fromList [T5,T7])
([T7,T6],fromList [T7,T6],fromList [T6,T7])
([T7,T7],fromList [T7,T7],fromList [T7])
([T8,T2],fromList [T8,T2],fromList [T2,T8])
([T8,T3],fromList [T8,T3],fromList [T3,T8])
([T8,T4],fromList [T8,T4],fromList [T4,T8])
([T8,T5],fromList [T8,T5],fromList [T5,T8])
([T8,T6],fromList [T8,T6],fromList [T6,T8])
([T8,T7],fromList [T8,T7],fromList [T7,T8])
([T8,T8],fromList [T8,T8],fromList [T8])
([T9,T2],fromList [T9,T2],fromList [T2,T9])
([T9,T3],fromList [T9,T3],fromList [T3,T9])
([T9,T4],fromList [T9,T4],fromList [T4,T9])
([T9,T5],fromList [T9,T5],fromList [T5,T9])
([T9,T6],fromList [T9,T6],fromList [T6,T9])
([T9,T7],fromList [T9,T7],fromList [T7,T9])
([T9,T8],fromList [T9,T8],fromList [T8,T9])
([T9,T9],fromList [T9,T9],fromList [T9])
```
it seems `fromList[x1,x2]` is wrong iff `x1 >= x2 >= T2`

**Comment by jwaldmann** [comment]
The error seems to go away when `S.fromList`  is not inlined:
```
main = mapM_ print $ do
  let pos = [ minBound .. maxBound :: T ]
  x1 <- pos
  x2 <- pos
  let xs = [x1,x2]
      {-# noinline fromList #-}
      fromList xs = S.fromList xs
      x = fromList xs
      y = S.fromList ( S.toList x )
  guard (x /= y)
  return (xs,x,y)
```

**Comment by jwaldmann** [comment]
This is even shorter:
```
import qualified Data.Set as S

main = print $
  let {-# noinline f #-}
      f () = T2
  in  S.fromList [f (), f ()]
  
data T = T1 | T2 | T3 | T4 | T5 | T6 | T7 | T8 | T9
  deriving (Show, Read, Eq, Ord, Bounded, Enum)
```
prints 
```
fromList [T2,T2]
```
And as I said earlier, comment out the `T9` constructor => prints `fromList [T2]`  as it should.

**Comment by jwaldmann** [comment]
The bug does occur with ghc-8.6.1 for both containers-0.5.11.0 and containers-0.6.0.1,
and it does not occur with ghc-8.4.3 (neither for containers-0.5.11.0 nor containers-0.6.0.1).

I was compiling like this
```
/opt/ghc/ghc-8.6.1/bin/ghc -O1 -fforce-recomp -package containers-0.5.11.0 CB.hs
```

**Comment by jwaldmann** [comment]
is this something about the (inlined version of the) derived Ord instance of T? The bug goes away when I implement exactly the cases that will be used by S.fromList 
```
data T = T1 | T2 | T3 | T4 | T5 | T6 | T7 | T8 | T9
  deriving (Show)

instance Eq T where

instance Ord T where
  T2 >= T2 = True
  compare T2 T2 = EQ
```
Should probably submit this to the ghc tracker, with subject or keywords "derived Ord instance for enumeration with >= 9 elements"

**Comment by mrkkrp** [comment]
So is this reported to GHC issue tracker?

**Comment by treeowl** [comment]
Not that I know of. Do you want to report it?

**Comment by mrkkrp** [comment]
I will then, I need this fixed.

**Comment by mrkkrp** [comment]
I reported it here: https://ghc.haskell.org/trac/ghc/ticket/15696.

**Comment by treeowl** [comment]
@RyanGlScott appears to have verified that this is a GHC issue we can't do anything about in `containers`.

**Comment by treeowl** [comment]
It has become absolutely clear that this is a compiler or RTS bug. GHC 8.6.1 should be considered completely unusable except as a technology preview. @bgamari has tentatively scheduled 8.6.2 for release in two weeks, pending a fix for this bug.
