### ISSUE TITLE
Use instances of Ix instead of Int as the type for Vertex in Data.Graph

### ISSUE THREAD

**Issue by L-TChen** [haskell/containers#599]
The cited paper in `Data.Graph` indicates that any instance of `Ix` can be used as `Vertex`, but the current implementation simply uses `Int`. Since Array is the underlying container, it seems also easy to make this change. 

Is there any particular reason to stick with `Int` instead of the type class `Ix`? 
Vertexes in a grid are naturally indexed by coordinates. Changing from `Int` to `Ix` would make the code dealing with this kind of vertexes simpler in this case.

**Comment by treeowl** [comment]
`Ix` doesn't seem to support all the operations we need. As an experiment, try generalizing `graphFromEdges` to

```haskell
graphFromEdges
  :: (Ord key, Ix v)
  => [(node, key, [key])]
  -> (Array v [v] -> (node, key, [key]), key -> Maybe v)
```

See how much you have to change to accemplish that.

**Comment by sjakobi** [comment]
If the proposal isn't feasible, how about we close the issue?

**Comment by L-TChen** [comment]
Sorry for not getting back to this issue. I will try @treeowl’s comment and evaluate my proposal soon.
