### ISSUE TITLE
Strict Merge not strict

### ISSUE THREAD

**Issue by dwincort** [haskell/containers#609]
Hi,

I believe that the `merge` function for `IntMap` is not properly strict.  Consider the following example:
```haskell
import qualified Data.IntMap.Merge.Strict as IntMap
import qualified Data.IntMap.Strict as IntMap

myMap = IntMap.fromList [(1,1),(2,2)]

seq (IntMap.merge IntMap.dropMissing IntMap.preserveMissing (IntMap.zipWithMatched (\t x y -> undefined)) myMap myMap) ()

seq (IntMap.merge IntMap.dropMissing IntMap.preserveMissing (IntMap.zipWithMatched undefined) myMap myMap) ()
```
When I evaluate either of the two `seq` lines, I get `()` instead of an error as I would expect.

**Comment by treeowl** [comment]
There is indeed something very lazy about the `IntMap` versions. For some reason, the `Strict` module re-exports the same `zipWithMatched`! Are you sure there's also a problem with `Map`?

**Comment by dwincort** [comment]
You're totally right -- this is only a problem with `IntMap` and not with `Map`.  In my application, I'm using `merge` for both `Map` and `IntMap`, and it wasn't working -- I wrote this simple test with `IntMap` and apparently never checked `Map` directly.   Sorry for mis-reporting!

I've updated the issue to be only about `IntMap`.

**Comment by treeowl** [comment]
Thanks. I'm putting together a fix now. There's an inconsistency with `Data.Map` that's been bugging me: the `Strict` module re-exports the do-nothing `preserveMissing`. Should it instead force things?
