### ISSUE TITLE
Add bind and join for Sets and Maps

### ISSUE THREAD

**Issue by xaverdh** [haskell/containers#613]
Set and Map may not have a monad instance, since the standard library does not allow functors / monads to be defined on a subcategory of Hask (OrdHask in this case), but that should not prevent us from manually adding funtions "bindSet/Map" and "joinSet/Map" which witness those monads.

**Comment by oisdk** [comment]
`bind` is `flip foldMap` for `Set`, right?

As for `Map`, you'd have to decide what the bias is.

**Comment by xaverdh** [comment]
Yes for Set it is just foldMap. Although it may still be nice to make that fact explicit.

**Comment by treeowl** [comment]
I don't really see the point, unless there's an efficiency benefit (which doesn't seem to be the case). Feel free to start a discussion/proposal on the libraries list if you really want this, but I'm going to close the ticket for now.
