### ISSUE TITLE
Update for new Cabal

### ISSUE THREAD

**Issue by treeowl** [haskell/containers#625]
We currently use deprecated `cabal-install` commands that are going away. Let's not.

**Comment by treeowl** [comment]
@phadej @hvr, I'm hoping maybe one of you could help out with this.

**Comment by phadej** [comment]
Simple solution doesn't work

```
% cabal new-build --enable-tests --enable-benchmarks
Resolving dependencies...
cabal: Could not resolve dependencies:
[__0] trying: containers-0.6.0.1 (user goal)
[__1] rejecting: containers:!test (constraint from config file, command line
flag, or user target requires opposite flag selection)
[__1] trying: containers:*test
[__2] next goal: ChasingBottoms (dependency of containers *test)
[__2] rejecting: ChasingBottoms-1.3.1.5 (cyclic dependencies; conflict set:
ChasingBottoms, containers)
```

with issue being https://github.com/haskell/cabal/issues/4087

---

The workaround is to split tests and benchmarks into own package(s), used only in CI.

```
packages:
  containers/
  containers-tests/
  contaienrs-benchmarks/
```

That's straightforward thing to do, and both `cabal v2-build` and `stack` would work with this. One could say that downside is that say, Stackage, won't build tests and benchmarks, but it doesn't anyway so it doesn't matter. (Some Nix users might actually build container tests, but I doubt, as they'll need to solve circularity as well).

**Comment by treeowl** [comment]
Splitting tests and benchmarks into their own packages sounds very nice, but it has its own complication. Those packages will need to be built on top of a `containers` compiled for testing, which sounds like a bit of a mess. Will we need a custom CI script to handle it?

**Comment by phadej** [comment]
[haskell-ci](https://github.com/haskell-ci/haskell-ci) handles that with ease, e.g. 
- https://github.com/dmwit/universe
- https://github.com/haskell-servant/servant

**Comment by treeowl** [comment]
I'm sorry, could you point me to the relevant parts? What I'm talking about is that running the `containers` tests and benchmarks requires `containers` to be compiled with `-DTESTING`, which is not how it should usually be compiled. We could probably change that, and maybe we should, but it will be extremely annoying. In particular, `QuickCheck` uses `show` to explain what failed; if we can't customize `Show` for testing, we'll need to work out another way to get `QuickCheck` to show us what we want.

**Comment by treeowl** [comment]
It seems this is mostly done, but the testing on GHC/Cabal head has been removed, presumably by mistake.

**Comment by treeowl** [comment]
@phadej, I'd appreciate your help restoring testing for ghc/cabal head. The new `.travis.yml` is too different from the old for me to know what to do with that; in particular all the `env` stuff is gone.

**Comment by phadej** [comment]
Do you *really* want to let CI fail for GHC HEAD? I suspect it will happen when you less want to track moving target?

**Comment by phadej** [comment]
Or did I misunderstood? Adding `ghc-head` job which **can** fail is relatively simple: I explained in https://github.com/haskell/containers/pull/628 

Making that job to be required, i.e. so whole build **can** fail is not supported.

**Comment by sjakobi** [comment]
I'll tentatively close this, since the setup has evolved a lot since the last activity here.

Please reopen if there's more to be addressed here.
