### ISSUE TITLE
Add alterF-alike for sets

### ISSUE THREAD

**Issue by treeowl** [haskell/containers#629]
I thought there was already a ticket for this, but I don't see it. I'm talking about

```
twiddle :: (Ord a, Functor f) => (Bool -> f Bool) -> a -> Set a -> f (Set a)
```

This would improve `nubOrdOn` by capturing the insertion path when the value isn't found.

**Comment by sjakobi** [comment]
Seems like this function can be adapted from `Set`'s instance for `Control.Lens.At`:

```haskell
instance Ord k => At (Set k) where
  at k f m = f mv <&> \r -> case r of
    Nothing -> maybe m (const (Set.delete k m)) mv
    Just () -> Set.insert k m
    where mv = if Set.member k m then Just () else Nothing
  {-# INLINE at #-}
```

**Comment by treeowl** [comment]
The problem `alterF` addresses is that the `Ord` instance may not be super-cheap, in which case the double descent isn't so great.

**Comment by treeowl** [comment]
By recording the path into the tree, it can follow that back in later.
