### ISSUE TITLE
IntMap.traverseWithKey goes in unexpected order

### ISSUE THREAD

**Issue by ryantrinkle** [haskell/containers#631]
This code:
```haskell
Data.IntMap.traverseWithKey (\k _ -> print k) $ Data.IntMap.fromList [(-1, ()), (0, ())]
```
prints:
```
0
-1
```

Is this expected?  I found it pretty surprising.

**Comment by treeowl** [comment]
Can you check with the master branch? I believe that's been fixed. And yeah, we should make a release....

**Comment by 3noch** [comment]
According to docs, `traverseWithKey f s == fromList $ traverse ((k, v) -> (,) k $ f k v) (toList m)` yet `toList m` doesn't *claim* to make any guarantees about the order of the list. Considering `toAscList` exists, I would almost expect `toList` to not be in ascending order. If this is truly not expected, should we also update the docs of `traverseWithKey` to use `toAscList` instead?

**Comment by treeowl** [comment]
No, this is no longer expected. It was a bug, and I believe it's fixed in master. Do you need me to make a release this week? That could be arranged.

**Comment by 3noch** [comment]
My question, in particular, is whether or not the docs for `traverseWithKey` should make it clear that the traverse happens on ascending keys?

**Comment by treeowl** [comment]
Yes, we definitely want to document that.

**Comment by Vlix** [comment]
I've just stumbled into this inconsistency. It appears in the update from `0.6.0.1` to `0.6.1.1` the `traverseWithKey` function has changed, and I can't see why.

**0.6.0.1**

```haskell
traverseWithKey :: Applicative t => (Key -> a -> t b) -> IntMap a -> t (IntMap b)
traverseWithKey f = go
  where
    go Nil = pure Nil
    go (Tip k v) = Tip k <$> f k v
    go (Bin p m l r) = liftA2 (Bin p m) (go l) (go r)
```

**0.6.1.1**

```haskell
traverseWithKey :: Applicative t => (Key -> a -> t b) -> IntMap a -> t (IntMap b)
traverseWithKey f = go
  where
    go Nil = pure Nil
    go (Tip k v) = Tip k <$> f k v
    go (Bin p m l r)
      | m < 0     = liftA2 (Bin p m) (go r) (go l)
      | otherwise = liftA2 (Bin p m) (go l) (go r)
```

The following holds for `0.6.0.1.traverseWithKey`, but not for `0.6.1.1.traverseWithKey`:

```haskell
λ> intMap = IntMap.fromList [(-1, ()),(0,())]
λ> Identity newMap = traverseWithKey (\_ -> Identity) intMap
λ> newMap == intMap
```

Why was this changed?

**Comment by treeowl** [comment]
Uh.... That looks like a serious mistake. It should be

```haskell
traverseWithKey :: Applicative t => (Key -> a -> t b) -> IntMap a -> t (IntMap b)
traverseWithKey f = go
  where
    go Nil = pure Nil
    go (Tip k v) = Tip k <$> f k v
    go (Bin p m l r)
      | m < 0     = liftA2 (flip (Bin p m)) (go r) (go l)
      | otherwise = liftA2 (Bin p m) (go l) (go 
```

Would you like to open a PR?

**Comment by Vlix** [comment]
Why was it even added? why was the original with just the `otherwise` line not sufficient?

**Comment by treeowl** [comment]
The old one was wrong for a different reason: it performed the `Applicative` effects in a weird order if the tree contained both negative and non-negative numbers.

**Comment by sjakobi** [comment]
@Vlix See https://github.com/haskell/containers/pull/593.

**Comment by Vlix** [comment]
Ah, so one inconsistency led to another, heh.

I can make a PR, brb.

**Comment by Vlix** [comment]
Here's the PR:

https://github.com/haskell/containers/pull/688

**Comment by treeowl** [comment]
Yeah, we want all the traversals to go in the same order. There is no such thing as a strict `IntMap`: there's only one `IntMap` type. So we don't have a choice about that part.

**Comment by Vlix** [comment]
On second thought, I fail to see the difference between:
`liftA2 (flip (Bin p m)) (go r) (go l)`
and
`liftA2 (Bin p m) (go l) (go r)`

That's like saying there's a difference between:
`flip map myMap (+1)`
and
`map (+1) myMap`

Why did the `traverseWithKey` get changed when there was a problem with `Foldable`?

**Comment by treeowl** [comment]
There's a big difference. The effects happen in the opposite order. If they write to and read from the same file, for instance, then that could make one correct and the other totally bogus. We need to maintain the law that `foldMap = Data.Traversable.foldMapDefault` and similarly for the keyed versions.

**Comment by Vlix** [comment]
Could you give a list of such invariants? I'd like to add more than just the "`traverseWithkey` shouldn't alter structure" test

**Comment by sjakobi** [comment]
> We need to maintain the law that `foldMap = Data.Traversable.foldMapDefault` and similarly for the keyed versions.

#593 added this property test but it failed to catch the bug:

https://github.com/haskell/containers/blob/5ff5247f6ea45f8aee8cba3ac77477df24b9dcf2/containers-tests/tests/intmap-properties.hs#L1178-L1180

**Comment by treeowl** [comment]
We often use lists for this sort of thing. Roughly speaking, `traverseWithKey f = fmap fromList . traverseAssocListWithKey . toList`.

**Comment by treeowl** [comment]
@sjakobi It sounds like we may have multiple problems....

**Comment by sjakobi** [comment]
> #593 added this property test but it failed to catch the bug:

Sorry for the noise – that property couldn't have caught the bug @Vlix reported: It doesn't check the structure of the resulting `IntMap`. It _does_ check the order of the traversal, which #593 fixed.

**Comment by Vlix** [comment]
Apparently, `foldMapDefault` uses `Const` with `traverse`, and:
`traverse Const intMap` <- correct order
`traverse Identity intMap` <- wrong order

**Comment by treeowl** [comment]
Right, right. So the folds are okay. *Whew*

**Comment by Vlix** [comment]
@sjakobi is right, the traversal is in the correct order, just not the resulting `IntMap`

```
λ> traverse print intMap 
"-2"
"-1"
"0"
"1"
"2"
fromList [(0,()),(1,()),(2,()),(-2,()),(-1,())]
```

**Comment by sjakobi** [comment]
Can this issue be closed now?

**Comment by sjakobi** [comment]
I believe everything here has been addressed. Please reopen if there's more to do here.
