### ISSUE TITLE
Checking IntMaps for disjointness

### ISSUE THREAD

**Issue by sjakobi** [haskell/containers#641]
Is this code optimal?

```
disjoint :: IntMap a -> IntMap b -> Bool
disjoint a b = null (intersection a b)
```

At least I think that it's non-obvious that it's optimal, so it would be good to add it to `IntMap` (and analogously `Map`).

**Comment by treeowl** [comment]
Definitely not. Please go right ahead. We already have that for `Data.Set`. Please also check on `Data.IntSet`.

**Comment by treeowl** [comment]
(Definitely not optimal constant factors, anyway. It builds a whole map we don't need.)
