### ISSUE TITLE
Make sure gitignore is up to date

### ISSUE THREAD

**Issue by treeowl** [haskell/containers#643]
@phadej recently reorganized the directory structure. Let's double check that the `gitignore` file still ignores things in the right places.

**Comment by sjakobi** [comment]
I think it's easier to fix any issues as we go. We have CI and code review, so I'm pretty confident that we'll catch any issues.

Do you mind if I close this?

**Comment by treeowl** [comment]
Mmm.... I guess, but there'll be heck to pay if something really massive slips in. Neither of us has the authority to rewrite git history here.

**Comment by sjakobi** [comment]
> Neither of us has the authority to rewrite git history here.

I'll just ask chessai then. ;)
