### ISSUE TITLE
Composing maps?

### ISSUE THREAD

**Issue by alexfmpe** [haskell/containers#647]
I was surprised that I couldn't find a `Map` composition function in `containers`. It seems it could be done with something no worse than `O(n * log m)`, where `n` is the size of the initial/source map.
```haskell
composition :: (Ord a, Ord b) => Map.Map b c -> Map.Map a b -> Map.Map a c
composition bc ab = flip Map.mapMaybe ab $ flip Map.lookup bc
```

**Comment by alexfmpe** [comment]
It's also possible to intersect on the `b` keys and `b` values. Everything here is linear except `sortOn`, so that gives `O(n * log n + m)` instead. Might matter if `m` is much larger than `n`
```haskell
composition :: (Ord a, Ord b) => Map.Map b c -> Map.Map a b -> Map.Map a c
composition bc ab = Map.fromList $ fmap snd $ intersect
   (List.sortOn fst $ fmap (\(a,b) -> (b,a)) $ Map.assocs ab)
   (Map.assocs bc)
  where
    intersect :: Ord k => [(k,x)] -> [(k,y)] -> [(k, (x,y))]
    intersect kxs@((k,x):kxs') kys@((k',y):kys') = case k `compare` k' of
      GT -> intersect kxs kys'
      LT -> intersect kxs' kys
      EQ -> (k, (x,y)) : intersect kxs' kys'
    intersect _ _ = []
```

**Comment by treeowl** [comment]
The first option is quite natural. If I'm calculating right the second is *never* better. Write out the difference `n log n + m - m log n = n log (n / m) + m` in terms of `n` and `s = m/n`: `n (log (1/s) + s)`, and then partially differentiate with respect to `s`: `n (1 - 1/s)`. This is always positive when `m > n`.

 Or just look at some plots and calculate some sample values.

**Comment by treeowl** [comment]
Actually, once you get to `log (1/s) + s`, see http://m.wolframalpha.com/input/?i=log+%281%2Fs%29+%2B+s+%3C+0

**Comment by treeowl** [comment]
Conclusion: the first implementation is the correct one. But you should be able to tighten up the constraints a tad. In particular, we shouldn't need `Ord a`:

```haskell
composition :: Ord b => Map.Map b c -> Map.Map a b -> Map.Map a c
composition bc ab = flip Map.mapMaybe ab $ flip Map.lookup bc
```

Please start a proposal on the libraries list; that will ensure the community likes the idea and help settle on a good name if so.

**Comment by alexfmpe** [comment]
> Please start a proposal on the libraries list; that will ensure the community likes the idea and help settle on a good name if so.

Thanks for the feedback. Will do

**Comment by treeowl** [comment]
I haven't seen the proposal yet.

**Comment by jwaldmann** [comment]
for reference, this is the start of the mailing list discussion: https://mail.haskell.org/pipermail/libraries/2019-July/029731.html

**Comment by chshersh** [comment]
I think that having this `compose` function in the `containers` library is a good thing! In terms of the performance, you can have a composable interface around `Map` with fast lookups, but you need to sacrifice the ability to traverse the resulting `Map`. So something like this is possible:

```haskell
mapToKleisli :: Ord k => Map k v -> Kleisli Maybe k v
mapToKleisli m = Kleisli (\k -> Map.lookup k m)
```

Where [`Kleisli`](https://hackage.haskell.org/package/base-4.12.0.0/docs/Control-Arrow.html#t:Kleisli) is defined in `base`. And now `compose` for this `Kleisli` is just `>>>` or `<<<` from the [`Category` typeclass](https://hackage.haskell.org/package/base-4.12.0.0/docs/Control-Category.html#t:Category). Not sure it's worth mentioning in the documentation, just a compelling use case, how abstractions from the standard library allow to reuse data types and provide an alternative implementations 🙂

**Comment by sjakobi** [comment]
Can this be closed now that #672 has been merged?

**Comment by alexfmpe** [comment]
> It seems it could be done with something no worse than O(n * log m), where n is the size of the initial/source map.

It just hit me that the simple implementation actually matches the asymptotic lower bound. 
```haskell
n :: Map a b
m :: Map b c
m `compose` n :: Map a c
```
Given there's `|n|` entries in the first map, the composition essentially maps each `a` in `n` to `Maybe c`. 
That is, either one of the `c` in `m` or `Nothing`. 
The number of possible such mappings is `(|m| + 1) ^ |n|`. 

Now we can do an information theory reasoning similar to the one for the lower bound of sorting: https://cs.stackexchange.com/questions/32311/proving-the-lower-bound-of-compares-in-comparison-based-sorting/35229#35229

To distinguish between `x` possible values, we need `log (x)` bits.
Thus, we have a lower bound of `log ((|m| + 1) ^ |n|) = |n| log (|m| + 1)` bits.

Given `Data.Map` lookups are comparison-based, each comparison gives us at most one bit of information - in the worst case we'll always be left with at least half of the remaining possible values.
Meaning we need at least as many comparisons as we need bits.

I'd like to put this info near the code, but I'm also reluctant of adding a big block of text to 4 different implementations (strict/lazy, poly/int). 
Is there a way to put the explanation in one place and link to it somehow from haddocks in the implementations?

**Comment by alexfmpe** [comment]
> I'd like to put this info near the code, but I'm also reluctant of adding a big block of text to 4 different implementations (strict/lazy, poly/int).

We don't have the strict variants anymore, and IntMap works differently, so I just went for it in https://github.com/haskell/containers/pull/960
