### ISSUE TITLE
improve documentation for Data.Graph

### ISSUE THREAD

**Issue by jwaldmann** [haskell/containers#648]
(see messages in this thread https://mail.haskell.org/pipermail/libraries/2019-June/029674.html)

we could
* add a sentence (in the module header) stating that the purpose is to compute SCCs quickly (we can even copy the O(V+E) claim from the paper?)
* add complexity information to some functions

Example for non-obvious behaviour: http://hackage.haskell.org/package/containers-0.6.1.1/docs/src/Data.Graph.html#graphFromEdges will sort the edge list (so you can't build the graph in linear time?) and the `key_vertex` function it returns, will take logarithmic time?

**Comment by meooow25** [comment]
The documentation is better today: https://hackage.haskell.org/package/containers-0.7/docs/Data-Graph.html
@jwaldmann do you think there is anything else that should be added?

**Comment by meooow25** [comment]
Do reopen if there is more that can be improved.
