### ISSUE TITLE
Data.Graph.dff bug?

### ISSUE THREAD

**Issue by KentaroUrata** [haskell/containers#650]
Data.Graph.dff returns two different output given semantically identical tree:

### Wrong?
Data.Graph.dff $ Data.Graph.buildG (1, 4) [(1,2),(1,3),(4,1)]

==>[Node {rootLabel = 1, subForest = [Node {rootLabel = 3, subForest = []},Node {rootLabel = 2, subForest = []}]},Node {rootLabel = 4, subForest = []}]

### Right
Data.Graph.dff $ Data.Graph.buildG (1, 4) [(1,2),(2,3),(2,4)]

==>[Node {rootLabel = 1, subForest = [Node {rootLabel = 2, subForest = [Node {rootLabel = 4, subForest = []},Node {rootLabel = 3, subForest = []}]}]}]

Notably the first wrong is failing to account for the fact Node 4 has Node 1 as child. Am I missing something here?

**Comment by jwaldmann** [comment]
API doc says "starting from each vertex in an unspecified order" http://hackage.haskell.org/package/containers-0.6.1.1/docs/Data-Graph.html#v:dff 

A DFF does contain only the "down" edges of the graph, while (4,1) is a back edge in your first example?

**Comment by KentaroUrata** [comment]
The first graph is: 4 -> 1 -> (2, 3)
And the second graph is: 1 -> 2 -> (3, 4)

According to the _Structuring Depth-First Search Algorithms in Haskell_ paper, back edge appears to be determined in relative to the _primary edges_ that allows to connect as many vertices as the graph allows (section 3). Since both example graphs are really trees (== only _primary edges_), there's no back edge in these examples?

Since the "shape" of the tree is identical, this result seems to imply that "name" we give to each node can influence the result of DFS and that feels wired, no?

**Comment by jwaldmann** [comment]
> trees (== only primary edges)

No - if you start the DFS in a non-root, some edges will be back edges, thus, not appear in the DFF.

**Comment by KentaroUrata** [comment]
Agreed. But the example I showed use dff where it would do dfs from each vertices in the graph, and with that both example would appear as tree?

BTW, thanks for sharing your insights!

**Comment by KentaroUrata** [comment]
I dug into it more. dfs would actually return the right answer if I give the root as input:
dfs  buildG (1, 4) [(1,2),(1,3),(4,1)] 4
==> [Node {rootLabel = 4, subForest = [Node {rootLabel = 1, subForest = [Node {rootLabel = 3, subForest = []},Node {rootLabel = 2, subForest = []}]}]}]

It appears that the problem is chop function which is not able to tell when it discovered it started its pruning logic from a middle of tree (dff would call dfs with all vertices as root of trees).

I'm wondering maybe it can be addressed by calling chop after eliminating trees that are contained by another...?

**Comment by KentaroUrata** [comment]
I'm going to close this issue as I was probably expecting too much out of dff/dfs function in terms of the forest it generates.
