### ISSUE TITLE
A generalized unionWithKey

### ISSUE THREAD

**Issue by sjakobi** [haskell/containers#660]
I [recently](https://github.com/dhall-lang/dhall-haskell/pull/1067) needed a function of type

```
Ord k => (a -> c) -> (b -> c) -> (k -> a -> b -> c) -> Map k a -> Map k b -> Map k c
```

This type would also have done the trick too, of course:

```
Ord k => (k -> a -> c) -> (k -> b -> c) -> (k -> a -> b -> c) -> Map k a -> Map k b -> Map k c
```

This is very similar to what the `semialign` package currently offers as [`alignWith`](http://hackage.haskell.org/package/semialign-1/docs/Data-Semialign.html#v:alignWith).

I believe that the types above give a very clear picture of what the functions will do, and that makes them more useful (but less general of course) than `merge` or `mergeWithKey`.

**Comment by treeowl** [comment]
Why not just use `alignWith` then? It's actually implemented for maps using `merge`.

**Comment by sjakobi** [comment]
`alignWith` doesn't give access to the keys!

Also I didn't want to add a new dependency  for a single function, and didn't want to bring in the `These` type.

I suspect that `containers` could also implement this function more efficiently than  what's possible via `merge`.

**Comment by treeowl** [comment]
`merge` is pretty darn efficient. Note in particular that it is marked `INLINE` specifically because it's intended for writing functions just like the one you want. And that means not having to add a bunch of different little variations on merging, which was the whole point.

**Comment by sjakobi** [comment]
That's good to know!

I'd still argue that the types above are much less complex that those of the `merge` machinery.

**Comment by alexfmpe** [comment]
> `alignWith` doesn't give access to the keys!
> 
> Also I didn't want to add a new dependency for a single function, and didn't want to bring in the `These` type.
> 
> I suspect that `containers` could also implement this function more efficiently than what's possible via `merge`.

How about [`ialign`](https://hackage.haskell.org/package/these-0.8.1/docs/Data-Align-Indexed.html) (or, after `these` split in parts, [`ialignWith`](https://hackage.haskell.org/package/semialign-indexed-1/docs/Data-Semialign-Indexed.html)) ?

**Comment by treeowl** [comment]
No, nothing with alignment is a union. Those are all intersections!

**Comment by treeowl** [comment]
Er... Actually, brain blip there. Forget my last comment!

**Comment by alexfmpe** [comment]
Haha I was confused for a bit there. Went from "Oh right, intersection" to "wait what"

**Comment by alexfmpe** [comment]
`Apply` is what would be intersection, I think

**Comment by sjakobi** [comment]
> How about [`ialign`](https://hackage.haskell.org/package/these-0.8.1/docs/Data-Align-Indexed.html) (or, after `these` split in parts, [`ialignWith`](https://hackage.haskell.org/package/semialign-indexed-1/docs/Data-Semialign-Indexed.html)) ?

Cheers, that's very close to what I want! Although I could do without the `These` part.

**Comment by treeowl** [comment]
@sjakobi I really think your best bet is to write the exact function you want using `merge`. The interface may be a bit intimidating at first, but it's really not bad.

**Comment by sjakobi** [comment]
FWIW, I ended up implementing this using `mergeWithKey` due to compatibility concerns:

```haskell
outerJoin fa fb fab ma mb =
    Data.Map.mergeWithKey
            (\k a b -> Just (fab k a b))
            (fmap fa)
            (fmap fb)
            ma
            mb
```

The merge API would have worked too though.
