### ISSUE TITLE
'stack test --file-watch' recompiles the world

### ISSUE THREAD

**Issue by jwaldmann** [haskell/containers#671]
I am in `containers` (the top directory of a checkout) with
```
stack --resolver=lts test containers-tests:intset-properties --file-watch
```
Whenever I do a one-line change in `containers/src/Data/IntSet/Internal.hs`, `stack` will recompile lots (all?) libraries (regex-posix, binary, QuickCheck, text, xml, ChasingBottoms, test-framework, ..)

(possibly related to #630)

Strange thing is that no libraries are recompiled with "bench" instead of "test"
```
stack --resolver=lts bench containers-tests:intset-benchmarks  --file-watch --ba "-q instance"
```
NB: And the worrisome thing is that the tests don't detect that my one-line change is wrong (using only a small number of examples?), and benchmarks happily print their timings all green (while they could check semantics - I know the size of the resulting DFA)

**Comment by treeowl** [comment]
Hrm.... If tests aren't working, that's bad. I don't *think* benchmarks are run by our Travis setup at the moment, but I could be wrong.

**Comment by treeowl** [comment]
As for recompilation, that's a bit of a mess because all sorts of testing things depend on `containers`. That doesn't happen anymore for benchmarks because we switched from `criterion` to `gauge`.

**Comment by sjakobi** [comment]
When working on `containers` it's generally a good idea to remove `containers` from the `packages` section in the `stack.yaml` or `cabal.project`. That solves the recompilation issue with the test dependencies.
