### ISSUE TITLE
0.6.2.1 breaks building unregisterized ghc-8.8.1 RC1

### ISSUE THREAD

**Issue by juhp** [haskell/containers#673]
See also https://gitlab.haskell.org/ghc/ghc/issues/16973 for more details.
containers-0.6.2.1 (in ghc-8.8.1 RC1) breaks unregisterized builds of ghc-8.8.1-rc1.
Reverting to 0.6.0.1 (and adding `#define USE_UNBOXED_ARRAYS 1`) allows unregisterized 8.8.1-rc1 to build. (It might be worth trying 0.6.1.1 too?)

cc @bgamari

**Comment by sjakobi** [comment]
@juhp I see that the linked GHC issue is closed, but I haven't taken a closer look.

Is there more to do here?

**Comment by juhp** [comment]
The Disable-unboxed-arrays.patch is still needed in Debian and Fedora for ghc-8.8.3 and 8.10.1 for bigendian archs.

**Comment by juhp** [comment]
I think the ghc ticket is closed on the assumption that disabling USE_UNBOXED_ARRAYS on unregisterised bigendian archs is a workaround.

So I don't know the best way to handle this transparently in containers/ghc: maybe some CPP or a flag?

**Comment by treeowl** [comment]
Has anyone tracked down the actual source of this problem?

**Comment by sjakobi** [comment]
Thanks for the quick response @juhp! :)

I'm thoroughly unfamiliar with the issue and the whole problem space, so if you would like to get this fixed upstream, please do take the lead.


> The Disable-unboxed-arrays.patch is still needed in Debian and Fedora for ghc-8.8.3 and 8.10.1 for bigendian archs.

> So I don't know the best way to handle this transparently in containers/ghc: maybe some CPP or a flag?

A good first step should be to just put the patch up in a PR. We can then see whether and how to integrate it.

(CC @bgamari)

**Comment by trommler** [comment]
The source of the problem seems to be an issue with GHC's array primitives on big-endian systems. The issue is tracked in https://gitlab.haskell.org/ghc/ghc/-/issues/16998.
While this issue is still open, containers cannot use unboxed arrays on big-endian architectures. I put up PR #808 to implement this.

**Comment by treeowl** [comment]
@trommler, do you know if everything is okay on unregisterized little-endian builds?

**Comment by trommler** [comment]
GHC HEAD passes validate for unregisterised x86_64 running Debian Linux. See https://gitlab.haskell.org/ghc/ghc/-/jobs/897089.
