### ISSUE TITLE
WordMap

### ISSUE THREAD

**Issue by Ericson2314** [haskell/containers#683]
Hey @treeowl in https://github.com/haskell/containers/issues/608#issuecomment-478430757 you mention someone was working on `WordMap`. Know where that is? Searching `WordMap` yields no other issue or PR.

**Comment by gereeter** [comment]
The comment was likely referring to #340, for which my [original (out-of-tree)](https://github.com/gereeter/bounded-intmap) implementation was of `WordMap`, not of `IntMap`.

**Comment by sjakobi** [comment]
Since the question appears to be answered, I'll close this issue.
