### ISSUE TITLE
Should minimum and maximum for IntMap handle negative keys before positive keys?

### ISSUE THREAD

**Issue by sjakobi** [haskell/containers#691]
I noticed that these would traverse values associated with positive keys before negative keys:

https://github.com/haskell/containers/blob/5ff5247f6ea45f8aee8cba3ac77477df24b9dcf2/containers/src/Data/IntMap/Internal.hs#L479-L496

That means that they could pick a different element than `(minimum . elems)` or `(maximum . elems)` would.

**Comment by Vlix** [comment]
Best to keep the order the same, right?

**Comment by Vlix** [comment]
Added fix to #688 , also fixed `showTree`

**Comment by sjakobi** [comment]
Fixed in #688. 

Thanks again, @Vlix! :)
