### ISSUE TITLE
Data.IntMap.Internal.filterWithKeyA may traverse positive keys before negative keys

### ISSUE THREAD

**Issue by sjakobi** [haskell/containers#692]
https://github.com/haskell/containers/blob/5ff5247f6ea45f8aee8cba3ac77477df24b9dcf2/containers/src/Data/IntMap/Internal.hs#L1824-L1830

I don't currently understand how it's used by the `merge` utils, so I'm not sure whether this is a problem or not.

**Comment by sjakobi** [comment]
I'm also not sure whether `mergeA` ought to take the sign of the keys into account. It currently looks like it doesn't.

https://github.com/haskell/containers/blob/5ff5247f6ea45f8aee8cba3ac77477df24b9dcf2/containers/src/Data/IntMap/Internal.hs#L2027-L2107

**Comment by treeowl** [comment]
We certainly want `mergeA` to take it into account.

**Comment by treeowl** [comment]
And yes, `filterWithKeyA` will need fixing. It should be equivalent to the implementation in terms of `traverseMaybeWithKey`.

**Comment by sjakobi** [comment]
Indeed it seems that `mergeA` attempts to handle effects in ascending key order, but fails with regard to negative keys:

```
> f k v = print k >> pure Nothing
> g k v1 v2 = print k >> pure Nothing
> mergeA (traverseMaybeMissing f) (traverseMaybeMissing f) (zipWithMaybeAMatched g) (fromList [(-2, ()), (1, ())]) (fromList [(-1, ()), (2, ())])
1
2
-2
-1
fromList []
```

**Comment by Vlix** [comment]
`filterWithKeyA` was easy to fix, but my head is spinning after trying to fix `mergeA`.
Can someone find the spots where what should be flipped?
I'm gonna leave it at this. (#688)

**Comment by sjakobi** [comment]
I can't find _any_ tests at all for `IntMap.mergeA`!

`Map.mergeA` gets at least some test coverage via `merge`, but its effect handling appears to be completely untested too.

That's kind o

**Comment by treeowl** [comment]
Blargh! Yeah, we'd better fix that.

**Comment by sjakobi** [comment]
@wrengr Can you help? You seem to be the author of `mergeA`.

**Comment by sjakobi** [comment]
@treeowl I think we could add a property test where we use `Data.Map.mergeA` as a model for `Data.IntMap.mergeA`'s effects handling, maybe using `Writer`.

Once we have a good test, we should be able to fix `mergeA`. It seems to me that all of the effects sequencing happens in `liftA2`, so maybe we could use a variant of `liftA2` that performs the sign check.

**Comment by treeowl** [comment]
Yes, we could definitely test one against the other. Probably state rather than writer. In theory, we should get the most bang for our buck using free applicatives over one or more functors, but those could get expensive. But I really don't yet understand why the code is the way it is now. `linkA` is especially mysterious. It smells very strange not to know the order things will go in yet. Is that a real effect of `IntMap` structure or a mistake?

**Comment by sjakobi** [comment]
> `linkA` is especially mysterious. It smells very strange not to know the order things will go in yet. Is that a real effect of `IntMap` structure or a mistake?

If you look at how it's used, it kind of makes sense, I think. The two submaps come from different inputs, and no ordering has been established yet.

**Comment by treeowl** [comment]
We also need to fix `elem`, `isSubmapOfBy`, and `isProperSubmapOfBy`.

**Comment by sjakobi** [comment]
> We also need to fix `elem`, `isSubmapOfBy`, and `isProperSubmapOfBy`.

Can you demonstrate the problems/bugs?

**Comment by treeowl** [comment]
@sjakobi Yeah, just use `Data.IntMap.Lazy` so you can stick some undefined values in.

**Comment by sjakobi** [comment]
> @sjakobi Yeah, just use `Data.IntMap.Lazy` so you can stick some undefined values in.

Sorry, I'm not sure what you mean.

**Comment by treeowl** [comment]
Compare ``5 `elem` fromList [(1, 5), (2, undefined)]`` to ``5 `elem` fromList [(-1, 5), (2, undefined)]``. The first one will hit `(1,5)` first and succeed; the second will hit `(2, undefined)` first and blow up.

**Comment by sjakobi** [comment]
@treeowl Why is this a problem?

**Comment by treeowl** [comment]
@sjakobi Users expect consistency. We expect `elem = elem . elems`. Reasoning about efficiency is also affected in some cases.

**Comment by sjakobi** [comment]
> Users expect consistency. We expect `elem = elem . elems`. Reasoning about efficiency is also affected in some cases.

So far I can't imagine a situation where this would be a _real_ (TM) problem.

If users put `undefined` into their `IntMap`s and then run `elem` on it, I'd say it's their own fault. ;)

Since the fix would reduce performance (ever so slightly) I don't think it's worth changing.

**Comment by treeowl** [comment]
Hrmmmm.... A similar argument applies to `minimum` and `maximum`; if you care which of two `==` values you get, then you're probably doing something wrong.

A bit of a side question: all these functions are trouble because ordering is weird in the high bit. Just how hard would it be to add `minBound` to each key before insertion (and to subtract it where appropriate)?

**Comment by sjakobi** [comment]
> Hrmmmm.... A similar argument applies to `minimum` and `maximum`; if you care which of two `==` values you get, then you're probably doing something wrong.

In https://github.com/haskell/containers/issues/691 the issue is that the returned element is a different one. `elem` doesn't care which equal element we find – it's purpose is to detect whether an equal element is in the map at all.



> A bit of a side question: all these functions are trouble because ordering is weird in the high bit. Just how hard would it be to add `minBound` to each key before insertion (and to subtract it where appropriate)?

Can you clarify what you mean? Honestly I don't understand the `IntMap` internals well at this stage. My patch for `mergeA` was largely mechanical.
