### ISSUE TITLE
sequence-benchmarks seems to use the wrong `replicate`

### ISSUE THREAD

**Issue by sjakobi** [haskell/containers#703]
While extracting the reproducer for https://gitlab.haskell.org/ghc/ghc/issues/17724, I noticed that some benchmarks used list's `replicate` instead of `Data.Sequence.replicate`:

https://github.com/haskell/containers/blob/0658f3ab1a0e249a724d79d7f45ca34621957334/containers-tests/benchmarks/Sequence.hs#L129-L139

**Comment by treeowl** [comment]
Ouch.
