### ISSUE TITLE
New release for GHC 8.12

### ISSUE THREAD

**Issue by sjakobi** [haskell/containers#717]
A few bug fixes and features have been added since the last release – it would be nice if they could be released in time for GHC 8.12.

What do you think, @treeowl? If you want, I could try my hand at updating the changelog…

**Comment by treeowl** [comment]
Yeah, that'd be helpful!

**Comment by sjakobi** [comment]
I'll submit a PR for the changelog soon.

I also found some `@since UNRELEASED` annotations that I'd like to update. Are we sticking with v0.6.3.1 for the new version number, or should the behaviour changes resulting from the `IntMap` fixes cause a major version bump? I see that 0.6.1.1, a minor bump, contained similar fixes…

**Comment by sjakobi** [comment]
Changelog PR: https://github.com/haskell/containers/pull/718

**Comment by sjakobi** [comment]
Is there anything else to merge before the release? The remaining open PRs all are a bit older.

I'm unsure about https://github.com/haskell/containers/pull/592, but my impression is that there's more to discuss there…

@treeowl Have you made a decision on the version number? I would still like to update and add a bunch of `since`-annotations.

**Comment by treeowl** [comment]
I don't remember if there's major-bump material. I don't think we want a major bump for what I see as bug fixes.

**Comment by sjakobi** [comment]
Ok. I'll stick with 0.6.3.1 for the `since`-annotations then.

**Comment by treeowl** [comment]
@sjakobi, if you think *you* can do the final benchmarking to get that merged, I would be most incredibly grateful.

**Comment by sjakobi** [comment]
> I'm a bit sad that @gereeter hasn't finalized his big `IntMap` rewrite just yet.


> @sjakobi, if you think _you_ can do the final benchmarking to get that merged, I would be most incredibly grateful.

Honestly, I'm unhappy too that all that work is left without a proper conclusion. And believe me, I'd also be very grateful if someone else would provide somewhat trustworthy benchmark results on real-world workloads. :)

But I'm not motivated enough to do more benchmarking of that branch on GHC. Benchmarking GHC is tricky and onerous work, probably more so than benchmarking a simpler application. If anyone wants to give it a spin, there are many valuable hints in [this `ghc-devs` thread](https://mail.haskell.org/pipermail/ghc-devs/2020-April/018763.html).

From my perspective the increase in code size and complexity is so considerable, that even if GHC's metrics had improved across the board, the merge would be a tough choice. However, in the last CI pipeline I ran, I still got [15 stat failures](https://gitlab.haskell.org/sjakobi/ghc/-/jobs/302703#L2693)   ([stat-failures.txt](https://github.com/haskell/containers/files/4705984/stat-failures.txt)).

I still wished that you or @gereeter would publicize this work a bit, so other people could play with it and ideally test it in their applications. Or maybe improve on it!

I also believe that even though the rewrite may not change the API, the change is profound enough that it should be brought up on the libraries mailing list.

But all this is just my own perspective – you're still the maintainer @treeowl! :)

**Comment by jwaldmann** [comment]
Is there a way to release the new IntMap independently of containers? Perhaps this makes it easier to test?

**Comment by sjakobi** [comment]
I've made an MR for GHC to check the compatibility of the latest `master`: https://gitlab.haskell.org/ghc/ghc/-/merge_requests/3522

**Comment by fumieval** [comment]
Regarding the IntMap rework, it would be nice to have a separate release for now, now that GHC 8.12 is imminent. I have a change I'd like to merge to 8.12 on top of a new container release.

**Comment by sjakobi** [comment]
Ping @treeowl! :)

If you don't find the time, I'd be happy to cut and upload the release myself, if you give me the necessary permissions.

**Comment by sjakobi** [comment]
Thanks, @treeowl! :)

http://hackage.haskell.org/package/containers-0.6.3.1
