### ISSUE TITLE
Data.IntSet.alterF?

### ISSUE THREAD

**Issue by sjakobi** [haskell/containers#719]
I noticed that we didn't add an `IntSet` version of `alterF` in #682. 

The type should be

```haskell
alterF :: Functor f => (Bool -> f Bool) -> Key -> IntSet -> f (IntSet)
```

A trivial implementation using `delete` and `insert` should probably be good enough.

Is it worth adding?

**Comment by treeowl** [comment]
Yes, for the sake of consistency.
