### ISSUE TITLE
FunctorWithIndex.imap (or Eq) in version 0.6.2.1 is broken

### ISSUE THREAD

**Issue by blackgnezdo** [haskell/containers#730]
This test passes in GHC 8.6.4 and fails in 8.10.1 with lens-4.19.2:
```haskell
import Control.Lens
import GHC.Exts (IsList(..))
import qualified Data.IntMap as IM

main :: IO ()
main = do
    let f i a = 5 + i * a
        g i a = a + 2 * i
        m = fromList [(-2,1),(0,-4)] :: IM.IntMap Int
        -- This is a FunctorWithIndex law.
        x = imap f (imap g m)
        y = imap (\i -> f i . g i) m
    print m
    print x
    print y
    print $ x == y
```

8.6 prints the expected:
```
fromList [(-2,1),(0,-4)]
fromList [(-2,11),(0,5)]
fromList [(-2,11),(0,5)]
True
```

8.10 prints:
```
fromList [(-2,1),(0,-4)]
fromList [(-2,11),(0,5)]
fromList [(0,5),(-2,11)]
False
```

**Comment by blackgnezdo** [comment]
@RyanGlScott FYI, in case the problem is in lens.

**Comment by sjakobi** [comment]
Thanks for the report, @blackgnezdo. Could you reduce the reproducer, so it depends only on `containers`? It might be worth checking it with `master` – there have been quite a few fixes of `IntMap` traversals since the last release: https://github.com/haskell/containers/blob/master/containers/changelog.md

**Comment by treeowl** [comment]
Yeah, this smells like that.

**Comment by blackgnezdo** [comment]
Sadly I can't get a standalone repro outside of our ghc environment at all. Let me get at least this much isolated before other people spend time on it.

**Comment by sjakobi** [comment]
I've had a brief look at `imap` in `lens`. AFAICT the definition is derived from the `TraversableWithIndex` instance, which is defined with `traverseWithKey`:

http://hackage.haskell.org/package/lens-4.19.2/docs/src/Control.Lens.Indexed.html#line-703

So I'm quite certain that you're hitting the bug that we've already fixed on `master`:

> Fix `traverse` and `traverseWithKey` for `IntMap`, which would
  previously produce invalid `IntMap`s when the input contained
  negative keys

@treeowl BTW, when do you expect to cut the next release? With the possible exception of https://github.com/haskell/containers/pull/729, everything seems to be ready.

**Comment by blackgnezdo** [comment]
Yes, I verified 7c40db193a063175e6a6abc9d1d4eb181f7fe03b fixes the problem.
