### ISSUE TITLE
All complexity annotations should be in MathJax format

### ISSUE THREAD

**Issue by sjakobi** [haskell/containers#731]
…because it's beautiful!

MathJax is already used in:

* `Data.Sequence`
* `compose` (as of https://github.com/haskell/containers/pull/729)

**Comment by treeowl** [comment]
I'm glad you like it! I converted `Data.Sequence` over some time ago, but I decided to leave the rest alone in case I got a bunch of complaints—MathJax has historically been a bit troublesome in some browsers. Fortunately, the complaints haven't materialized, so I guess the situation is now good enough. Let's do this.

**Comment by sjakobi** [comment]
> I converted `Data.Sequence` over some time ago, but I decided to leave the rest alone in case I got a bunch of complaints—MathJax has historically been a bit troublesome in some browsers.

https://github.com/haskell/containers/commit/fdc4ccaa1e29d5fc541815d4ff6f4d058db82a1a seems to contain at least some of your work. Hopefully the browser support issue has been resolved by now!

**Comment by treeowl** [comment]
Ah, that reminds me of the loading time concern.... Regardless, the complaints have not poured in, so we proceed.
