### ISSUE TITLE
Git tags for v0.6.3.1

### ISSUE THREAD

**Issue by sjakobi** [haskell/containers#737]
There's a bit of confusion about the git tag that corresponds to the [`v0.6.3.1` Hackage upload](http://hackage.haskell.org/package/containers-0.6.3.1).

* The [`v0.6.3.1`](https://github.com/haskell/containers/releases/tag/v0.6.3.1) and [`v0.6.3.1a`](https://github.com/haskell/containers/releases/tag/v0.6.3.1a) tags still have the wrong package version number in the cabal file.

* [`v0.6.3.1b`](https://github.com/haskell/containers/releases/tag/v0.6.3.1b) has the correct package version number, but doesn't specify any `default-language` fields:

  ```
  $ cabal check
  Warning: The following warnings are likely to affect your build negatively:
  Warning: Packages using 'cabal-version: >= 1.10' must specify the
  'default-language' field for each component (e.g. Haskell98 or Haskell2010).
  If a component uses different languages in different modules then list the
  other ones in the 'other-languages' field.
  Warning: These warnings may cause trouble when distributing the package:
  Warning: 'ghc-options: -O2' is rarely needed. Check that it is giving a real
  benefit and not just imposing longer compile times on your users.
  Warning: Hackage would reject this package.
  ```

* https://github.com/haskell/containers/commit/97fe43c54c5c8a9b93ecf5abd7509e8085b63d41 seems to correspond to the uploaded version, but hasn't been tagged yet.

I'm not sure how to best resolve this. How about we tag https://github.com/haskell/containers/commit/97fe43c54c5c8a9b93ecf5abd7509e8085b63d41 as e.g. `v0.6.3.1-release` to clarify that this is _the one_?

CC @fumieval

**Comment by treeowl** [comment]
Yeah, makes sense. I suck at tagging. Please go ahead and do that.

**Comment by sjakobi** [comment]
No worries @treeowl!

Let's try to be sure that we solve this properly now though.

> How about we tag 97fe43c as e.g. v0.6.3.1-release to clarify that this is the one?

@fumieval What do you think about this idea?

**Comment by fumieval** [comment]
Sounds good to me

**Comment by sjakobi** [comment]
I've made a proper GitHub release to give this tag a bit more authority. ;)

https://github.com/haskell/containers/releases/tag/v0.6.3.1-release

**Comment by sjakobi** [comment]
I wonder whether we should delete the other tags?!

**Comment by treeowl** [comment]
Oh, is that a thing we can even do?

**Comment by treeowl** [comment]
Looks like yes! Done. Wish I'd known that......

**Comment by sjakobi** [comment]
Cool! :)

Note that AFAIK it's a bit of a no-no to reassign published tags. We've avoided that here though.

**Comment by sjakobi** [comment]
BTW, I used this SO answer to delete the removed tags from my local repo: https://stackoverflow.com/a/5373319/1013393
