### ISSUE TITLE
Branch protections

### ISSUE THREAD

**Issue by sjakobi** [haskell/containers#739]
I noticed that I can't force-push to feature branches in this repo. This is a bit annoying, since I now tend to push to this repo, then remember the issue and push to my fork, and then have to delete my branch here…

Wouldn't it be sufficient if only `master` was protected?

**Comment by treeowl** [comment]
I believe that's set by the `haskell` organization and is totally out of my hands.

**Comment by sjakobi** [comment]
`bytestring` doesn't have the same branch protections – I just checked.

Can't you modify the settings at https://github.com/haskell/containers/settings/branches, @treeowl?

**Comment by treeowl** [comment]
That's a 404 error.

**Comment by sjakobi** [comment]
> > Can't you modify the settings at https://github.com/haskell/containers/settings/branches, @treeowl?
>
> That's a 404 error.

I think it's the right URL – I can access it for `bytestring` for example.



@chessai Could you possibly help us out and limit the branch protections to `master`? :)

**Comment by chessai** [comment]
@sjakobi admins in haskell/ can't change it. We have to contact GitHub support. Because I see:

```
Force pushes to all branches in this repository have been disabled by GitHub Support. Please contact us if you'd like that changed.
```

It is not clear to me how this came to be. Possibly a haskell admin asked for them to do this. And I'm unsure that me emailing in would upset someone who explicitly asked for them to do this. I don't see an issue with force-pushing to branches other than master, so I think whoever did this just felt it was easier to do that than configure each repo in the same way.

**Comment by sjakobi** [comment]
Thanks @chessai! What a curious thing!

Note that e.g. `vector` and `bytestring` don't have this weird rule though.

@hvr, @gbaz Would you happen to know anything about this? And could something be done about it with reasonable effort?

**Comment by chessai** [comment]
Weird. If it only applies to this repo, I'm even more confused. I will wait for one of the two tagged people to reply. If they do not after a while, I will just contact GitHub support. I see no issue with it seems @treeowl does not seem opposed to this change (correct me if im wrong)

**Comment by treeowl** [comment]
I dunno; I've never used feature branches in this repo. But it seems okay.

**Comment by sjakobi** [comment]
Ping @chessai. Sorry to bother you about this, but if possible, I'd like to see this speedbump removed.

**Comment by sjakobi** [comment]
Ping @chessai! :)

**Comment by gbaz** [comment]
I looked at that branch protection stuff and there's no rules configured for this repo. So I don't know what to tell you. I'm happy to push buttons, but there appear to be no buttons to push.

**Comment by chessai** [comment]
I have opened a support ticket with GitHub.

**Comment by chessai** [comment]
GitHub says this is resolved. Apparently an admin made the request 5 years ago to block force pushes in this manner. Anyway, 5 years later, it is fixed.

**Comment by sjakobi** [comment]
Yep, I can force-push to feature branches now. Thanks a lot, @chessai!
