### ISSUE TITLE
Add actually-strict versions of `Map` and `IntMap`

### ISSUE THREAD

**Issue by treeowl** [haskell/containers#74]
Obviously, the current `Data.Map.Strict` and `Data.IntMap.Strict` interfaces need to stick around for backwards compatibility, but they seem to be fundamentally broken:
1. Their `Functor`, `Traversable`, and (apparently) `Data` instances don't match their claimed strictness, because they share the same type as the lazy versions.
2. For the same reason, anyone using the `Strict` modules and getting a map from someone else has to assume the map might contain suspensions and therefore forcing its elements could generate exceptions or fail to terminate.

I think there are two sensible ways to make really strict versions:
#### Conservative

Wrap up the map implementations in `newtype`s and give them their own instances as appropriate. This is certainly the simplest approach. Its advantages:
1. Very little new code is needed.
2. The package source and binary grow only slightly.
3. It costs almost no extra time to maintain.
4. It supports a trivial `strictToLazy` function (unwrapping the `newtype`), a simple `lazyToStrict` function based on `deepseq`, and a cheap `unsafeLazyToStrict` function (the `newtype` wrapper).
#### Radical

Write completely new strict map types with strict fields. I imagine the function implementations, in most or all cases, would have exactly the same text as the lazy ones, so a bit of CPP hackery could probably reduce the source bloat, but not the binary bloat. Its advantages:
1. There's no need to carefully force everything by hand, and hope you didn't miss anything, because the data constructors will do the job themselves.
2. Any retrieved element is known to be forced, and GHC can probably take advantage of that to get a minor efficiency gain. It may or may not be able to improve strictness analysis and unbox more things.

It seems to me that the conservative approach would be pretty easy to swallow.

**Comment by lspitzner** [comment]
For future reference: The primary counterargument apparently is that a strict `fmap` would violate `Functor` laws; see
[libraries@haskell.org feb 2011](https://mail.haskell.org/pipermail/libraries/2011-February/015923.html)
[libraries@haskell.org nov 2014](https://mail.haskell.org/pipermail/libraries/2014-November/024398.html)
