### ISSUE TITLE
Add a monomorphic function `toList` in `Data.Sequence`?

### ISSUE THREAD

**Issue by kindaro** [haskell/containers#744]
[Presently, it says:][1]

> Create a sequence from a finite list of elements. There is a function toList in the opposite direction for all instances of the Foldable class, including Seq.

[1]: https://hackage.haskell.org/package/containers-0.6.3.1/docs/Data-Sequence.html#v:fromList

I propose that a monomorphic alias to `Foldable.toList` be added right into the module.

**Comment by sjakobi** [comment]
What's the motivation?

**Comment by kindaro** [comment]
1. Ergonomics: I may not like to import `Foldable` when all I want is to get a list from a `Sequence`. After all, I already imported `Sequence`.
2. Type inference: I may have a polymorphic value `Foldable f ⇒ f α`, so with `Foldable.toList` I shall need to put a type annotation somewhere.
3. Predictability: `Sequence.toList` tells the reader more than `Foldable.toList`.
4. Safety: a monomorphic function may enforce a beneficial restriction on the code.

**Comment by sjakobi** [comment]
Sounds good to me. Personally, I've wanted that function too.

**Comment by kindaro** [comment]
What is my next step? Should I make a pull request, or what? @sjakobi How does this work?

**Comment by treeowl** [comment]
Traditionally, most additions to `containers` are discussed on the libraries list first, to get community input. This one doesn't seem quite obvious enough to me to justify bypassing that process.

**Comment by kindaro** [comment]
@treeowl  I tried that before. It gives rise only to sadness and disappointment. I think I shall just go away.

**Comment by treeowl** [comment]
@kindaro, please don't close issues out of anger.

**Comment by kindaro** [comment]
@treeowl  I am not in need and I have no liking to these camarilla games. I was mistaken in the expectation that a meaningful conversation might take place and I apologize for imposing it on you to send me away. Having weighed my feelings, I retract the proposal and ask that the issue be closed and forgotten. Open one yourself if you like.
