### ISSUE TITLE
`(==)` for `Set` fails to specialize

### ISSUE THREAD

**Issue by sjakobi** [haskell/containers#772]
While building `dhall` with `-Wall-missed-specialisations`, GHC reported:

```
src/Dhall/Diff.hs: warning: [-Wall-missed-specialisations]
    Could not specialise imported function ‘Data.Set.Internal.$fEqSet_$c==’
    Probable fix: add INLINABLE pragma on ‘Data.Set.Internal.$fEqSet_$c==’
```

Any reason why the proposed fix wouldn't be a good idea?!

**Comment by treeowl** [comment]
That's surprising! Aren't class methods automatically `INLINABLE`?

**Comment by sjakobi** [comment]
> Aren't class methods automatically `INLINABLE`?

That would be news to me! Where is this documented?

The interface files for the `containers` shipped with GHC do include unfoldings for `(==)` though. For example for GHC 9.0.1:

```
  $fEqSet_$c== ::
    GHC.Classes.Eq a => Set a -> Set a -> GHC.Types.Bool
  [HasNoCafRefs, LambdaFormInfo: LFReEntrant 3, Arity: 3,
   Strictness: <L,U(C(C1(U)),A)><S,1*U><S,1*U>,
   Unfolding: (\ @a
                 ($dEq['Many] :: GHC.Classes.Eq a)
                 (t1['Many] :: Set a)
                 (t2['Many] :: Set a) ->
               case t1 of wild {
                 Bin dt ds ds1 ds2
                 -> case t2 of wild1 {
                      Bin dt1 ds3 ds4 ds5
                      -> case GHC.Prim.==# dt dt1 of lwild {
                           DEFAULT -> GHC.Types.False
                           1#
                           -> GHC.Classes.$fEq[]_$c==
                                @a
                                $dEq
                                ($fDataSet_$spoly_go1 @a dt ds ds1 ds2 (GHC.Types.[] @a))
                                ($fDataSet_$spoly_go1 @a dt1 ds3 ds4 ds5 (GHC.Types.[] @a)) }
                      Tip
                      -> case dt of wild2 {
                           DEFAULT -> GHC.Types.False
                           0#
                           -> GHC.Classes.$fEq[]_$c==
                                @a
                                $dEq
                                ($fDataSet_$spoly_go1 @a 0# ds ds1 ds2 (GHC.Types.[] @a))
                                (GHC.Types.[] @a) } }
                 Tip
                 -> case t2 of wild1 {
                      Bin dt ds ds1 ds2
                      -> case dt of wild2 {
                           DEFAULT -> GHC.Types.False
                           0#
                           -> GHC.Classes.$fEq[]_$c==
                                @a
                                $dEq
                                (GHC.Types.[] @a)
                                ($fDataSet_$spoly_go1 @a 0# ds ds1 ds2 (GHC.Types.[] @a)) }
                      Tip
                      -> GHC.Classes.$fEq[]_$c==
                           @a
                           $dEq
                           (GHC.Types.[] @a)
                           (GHC.Types.[] @a) } })]
```

**Comment by sjakobi** [comment]
> Aren't class methods automatically `INLINABLE`?

So the [docs for `-fspecialise-aggressively`](http://downloads.haskell.org/~ghc/9.0.1/docs/html/users_guide/using-optimisation.html#ghc-flag--fspecialise-aggressively) say

> By default only type class methods and methods marked INLINABLE or INLINE are specialised. This flag will specialise any overloaded function regardless of size if its unfolding is available. This flag is not included in any optimisation level as it can massively increase code size. It can be used in conjunction with -fexpose-all-unfoldings if you want to ensure all calls are specialised.

I'm not sure how to interpret the first sentence though. Is it meant like this?

> By default only (type class methods and ~~methods~~functions) marked INLINABLE or INLINE are specialised.

Or like this?

> By default only type class methods and (~~methods~~functions marked INLINABLE or INLINE) are specialised.

**Comment by treeowl** [comment]
I don't know where I encountered that info, but it's at least available buried in the documentation for an optimization flag:

> `-fspecialise-aggressively`
>
> By default only type class methods and methods marked `INLINABLE` or `INLINE` are specialised. This flag will specialise any overloaded function regardless of size if its unfolding is available. This flag is not included in any optimisation level as it can massively increase code size. It can be used in conjunction with `-fexpose-all-unfoldings` if you want to ensure all calls are specialised.

**Comment by treeowl** [comment]
I believe your first interpretation of that very badly constructed sentence is correct.

**Comment by treeowl** [comment]
Anyway, I don't know what's leading to the missed optimization warning. Have you looked at whether specialization actually takes place? Another question: how much does specialization actually help here, when it happens?

**Comment by sjakobi** [comment]
> Have you looked at whether specialization actually takes place?

There's no specialization:

```
                    lvl332 :: Bool
                    [LclId]
                    lvl332
                      = Data.Set.Internal.$fEqSet_$c==
                          @ Text Data.Text.$fEqText ksL ksR } in
```

 Another question: how much does specialization actually help here, when it happens?

Frankly, it probably doesn't matter in this case. I didn't check though. For now I'll assume that GHC has a good reason not to be more eager about specialization. (Probably compile time.)

Thanks for the discussion though! :) It's an interesting rabbit hole!
