### ISSUE TITLE
Release planning for GHC 9.2

### ISSUE THREAD

**Issue by sjakobi** [haskell/containers#777]
GHC 9.2 is scheduled to be released in early June. There's a compatibility patch (https://github.com/haskell/containers/commit/7fb91ca53b1aca7c077b36a0c1f8f785d177da34) which means that we need to cut a new release for `containers` too.

The following PRs look like they could make it too:

* [ ] https://github.com/haskell/containers/pull/750 needs final review
* [x] ~~I need to finish https://github.com/haskell/containers/pull/768.~~ #768 needs review
* [ ] https://github.com/haskell/containers/pull/774 needs review
* [ ] https://github.com/haskell/containers/pull/775 needs review

Anyone, feel free to suggest other changes that we should try to include.

**Comment by treeowl** [comment]
Been feeling the need to release too.

**Comment by sjakobi** [comment]
@treeowl Sounds good. I think the PRs above are waiting for your review. Could you give them a look?

**Comment by treeowl** [comment]
Yeah, this evening.

**Comment by sjakobi** [comment]
Ping @treeowl! :)

**Comment by sjakobi** [comment]
Another ping, @treeowl! :) These PRs aren't large – they shouldn't be much work to review.

**Comment by treeowl** [comment]
No, you're right, but I'm away from usable internet till tonight. Please
ping me tomorrow, when I will actually have the capacity to do it, finally.

**Comment by sjakobi** [comment]
Ping @treeowl! ;)

Am Sa., 29. Mai 2021 um 12:51 Uhr schrieb David Feuer <
***@***.***>:

> No, you're right, but I'm away from usable internet till tonight. Please
> ping me tomorrow, when I will actually have the capacity to do it, finally.
>

**Comment by treeowl** [comment]
Ugh. My travel plans went awry and I ended up getting home a day late.
Should be able to do it tomorrow.

**Comment by treeowl** [comment]
Released!

**Comment by sjakobi** [comment]
@treeowl Could you push the release changes (version bump, changelog update, etc.) to the repo and tag them?

Regarding this changelog entry:

> The Ord IntSet instance, which was broken in the last version, has been repaired.

This sounds like the bug was introduced in v0.6.4.1, when in fact it was introduced in v0.6.3.1. This should be clarified.

**Comment by treeowl** [comment]
Whoops.... Committed and tagged locally, but I guess I didn't push.   .

**Comment by treeowl** [comment]
Pushed now, and changelog updated.
