### ISSUE TITLE
Find values within a given interval for Data.Map

### ISSUE THREAD

**Issue by JakobBruenker** [haskell/containers#778]
Would it be possible to add a function to Data.Map that finds all entries whose keys lie within a given range?

Something like

```haskell
within :: Ord a => Map k a -> (a, a) -> Map k a
```

This doesn't seem like an operation that can be implemented efficiently with the functions exposed in the API (though I may simply be missing a way to do so), and yet also seems like something that should be doable efficiently given access to the internals.

One question is whether keys exactly matching the provided bounds should be included or not. Perhaps multiple versions should be provided, given the existence of `lookupLT` as well as `lookupLE`, etc.

**Comment by treeowl** [comment]
There are splitting operations you can combine to get that. It should be
only a constant factor off optimal.

**Comment by sjakobi** [comment]
Indeed,  this should be pretty easy to implement using [`splitLookup`](http://hackage.haskell.org/package/containers-0.6.4.1/docs/Data-Map-Lazy.html#v:splitLookup).

**Comment by JakobBruenker** [comment]
Indeed, I just realized this a minute ago as well, thank you both.
