### ISSUE TITLE
user larger keys for IntMap tests

### ISSUE THREAD

**Issue by jwaldmann** [haskell/containers#788]
Prompted by https://github.com/haskell/containers/issues/787#issuecomment-884565646, I replaced the Arbitrary instance with
```
instance Arbitrary a => Arbitrary (IntMap a) where
  arbitrary = fmap (fromList . fmap (\(k,v) -> (getLarge k, v))) arbitrary
```
Good thing: all tests are green. So, no action required. We still might want to replace the instance?

That section of the code has heading ` Arbitrary, reasonably balanced trees`. I think "reasonable" is the wrong goal here -  for correctness tests, I want _all_ sorts of data, including "unreasonable". This might be different from performance tests where we might want _typical_, and that could mean "small keys", as produced by the current instance.

**Comment by treeowl** [comment]
I certainly agree that we want extreme trees! Is `Large` a good way to get that? Or do we need to combine multiple generators? If you think this version is more thorough than what we did before, I'll happily merge.

Quick question: do you have any idea how to up the test count in CI?

**Comment by jwaldmann** [comment]
>  Is `Large` a good way to get that? 

I have no idea, and no experience. `Large` looked to me like one standard way to quickly get Ints that use all bits. I found out about it only after I made the ad-hoc definition `2^x * y`. Quickcheck's generator https://hackage.haskell.org/package/QuickCheck-2.14.2/docs/src/Test.QuickCheck.Arbitrary.html#arbitrarySizedBoundedIntegral  is different (better?) in the sense that it will use all bits (mine would just shift a few-bit pattern). On the other hand, an Int with a long tail of zeroes might be useful for the specific data structures that we want to test.

> If you think this version is more thorough than what we did before, I'll happily merge.

"more thorough" is hard to define/measure. One could fuzz the code and see how fast that's detected? (Nice student project ...)

> Quick question: do you have any idea how to up the test count in CI?

On the command line, I used `stack test --ta '-a 10000'`. [containers CI](.github/workflows/haskell-ci.yml)  uses cabal, I'm sure it has a way to pass options. This seems to work:
```
cabal test intset-properties --test-option="-a 10000"
```

The CI script is generated? Then we need to find a way to pass options through the generator?

**Comment by treeowl** [comment]
I'll merge now. We can investigate more options later.

**Comment by treeowl** [comment]
Oh wait, this isn't a PR. 🤦

**Comment by jwaldmann** [comment]
I can make  a PR.

**Comment by treeowl** [comment]
Thanks.

**Comment by treeowl** [comment]
Why didn't I merge this already?

**Comment by meooow25** [comment]
`Arbitrary IntMap` tests with large keys now.
https://github.com/haskell/containers/blob/5d4bc2ed62475062a09d76a037ca7a72ad3cbd45/containers-tests/tests/intmap-properties.hs#L229-L232
