### ISSUE TITLE
instance Eq1/2 etc are only available with base-4.9

### ISSUE THREAD

**Issue by phadej** [haskell/containers#807]
This is not indicated in the documentation of these instances, neither in the changelog.

Therefore I was fooled into making broken `hashable` release.

The easiest "fix" would be to drop GHC-7 support.

I'd also welcome removal of **all** other conditional interfaces, even at the cost of removal of old GHC support. (especially if it's only GHC-7).

**Comment by phadej** [comment]
I'm inclined to make restricting `base >=4.9` revisions for all `containers` since 0.5.9.1.

**Comment by treeowl** [comment]
`Eq1` and `Eq2` don't exist in earlier versions of `base`, do they? Different (superior, IMO) classes by the same names existed elsewhere.

**Comment by treeowl** [comment]
@phadej , why would you do that?

**Comment by phadej** [comment]
Because the conditional API makes it hard for me to support ranges of container versions. Or I'll just drop `hashable` GHC-7 support.

**Comment by treeowl** [comment]
I don't know how you expect `containers` to instantiate a class that doesn't exist.

**Comment by phadej** [comment]
The `Eq1` exists in `transformers`, and for non-boot libraries using then interchangeably is (almost) transparent. Ditto `hashable` issue.

**Comment by treeowl** [comment]
Okay, well, you're just going to have to test for both `base` and `containers` versions to use instances in `containers` of classes in `base`. That's normal.

**Comment by phadej** [comment]
I see this won't be fixed on `containers` side.

Please consider dropping old GHC support. It would make your life easier as well.

**Comment by treeowl** [comment]
I am all in favor of doing so.
