### ISSUE TITLE
Build instructions with `cabal` are way outdated

### ISSUE THREAD

**Issue by sjakobi** [haskell/containers#819]
https://github.com/haskell/containers/blob/master/CONTRIBUTING.md#with-cabal-install

Nobody is using `cabal sandbox` anymore, right?!

**Comment by treeowl** [comment]
Right.

**Comment by konsumlamm** [comment]
This has been fixed by #916.

**Comment by sjakobi** [comment]
> This has been fixed by #916.

Great! :)
