### ISSUE TITLE
CI fails for ghc-8.0.2, because of basement-0.0.13

### ISSUE THREAD

**Issue by jwaldmann** [haskell/containers#822]
looks like this https://github.com/haskell/containers/runs/5517053088?check_suite_focus=true and the reason seems to be https://github.com/haskell-foundation/foundation/issues/561 

I could reproduce this locally, and fix by adding  `--constraint 'basement<0.0.13'` to cabal commands.

**Comment by treeowl** [comment]
@sjakobi , do you think this is enough of a reason to drop GHC 8.0?

**Comment by sjakobi** [comment]
@treeowl I think dropping support for 8.0 should be fine. An alternative way to address this is to add constraints

```
basement < 0.0.13 || > 0.0.13
```

in the benchmarks.

Or migrate from `gauge` to `tasty-bench` which doesn't depend on `basement`.

**Comment by andreasabel** [comment]
I think I fixed this in 
- https://github.com/haskell-foundation/foundation/issues/561#issuecomment-1083441783

**Comment by Bodigrim** [comment]
I was looking to check performance of `containers` in GHC 9.4, but changes to `Word64` has broken `gauge` once again, and I do not expect it fixed any time soon. I’d be happy to submit a PR switching to `tasty-bench`, if that’s acceptable.

**Comment by treeowl** [comment]
Totally acceptable. I don't know if it's good, but bad is better than broken?
