### ISSUE TITLE
`instance (KnownSymbol sym) => HasField sym (Map String a) (Maybe a)`

### ISSUE THREAD

**Issue by parsonsmatt** [haskell/containers#829]
```haskell
instance 
    KnownSymbol sym 
  => 
    HasField (sym :: Symbol) (Map String a) (Maybe a)
  where 
    getField = 
      Map.lookup (symbolVal $ Proxy @sym)
)
```

This is pretty nice with `OverloadedRecordDot`. Would there be any interest in adopting this into the library itself?

**Comment by treeowl** [comment]
That's rather clever. I like it, and am inclined to accept it. However, I'm just a tad concerned about extension/generalization. If we do that, we'll surely also want

```haskell
instance 
    KnownSymbol sym 
  => 
    HasField (sym :: Symbol) (Map Text a) (Maybe a)
```

Where should that instance live?

Additionally, there's a conflicting potential instance based on `singletons`:

```haskell
instance (SingKind k, k' ~ Demote k, Ord k')
  => HasField (name :: k) (Map k' a) (Maybe a)
```

Of course, that's only useful if anyone actually uses `HasField` with non-`Symbol` keys; I don't know if they do.

**Comment by parsonsmatt** [comment]
> Where should that instance live?

Great question - I think if we just generalize to `IsString` then that solves the concern.

```haskell
instance (KnownSymbol sym, IsString str, Ord str) 
    => HasField sym (Map str a) (Maybe a) 
  where 
    getField = 
        Map.lookup (fromString (symbolVal $ Proxy @sym))

λ> let foo = Map.fromList [("hello", 1), ("goodbye", 2)]
λ> foo.hello
Just 1
λ> import Data.Text
λ> :set -XOverloadedStrings
λ> import Data.Text
λ> let foo = Map.fromList [("hello", 1), ("goodbye", 2)] :: Map Text Int
λ> foo.hello
Just 1
```

Though the `singletons` based approach is also quite cool! I *think* that is a generalization of the `Symbol/String` instance.

**Comment by treeowl** [comment]
Yeah, `IsString` solves it, at least for now. If `Symbol`s are (eventually?) represented in some fancier way, we may end up wanting `KnownSymbol` to be able to produce that, but I suppose we can accept some potential future breakage that way.

Surprisingly (to me), the `singletons` way is a generalization of the `Symbol`/`Text` one. See the `SingKind Symbol` instance in [`GHC.TypeLits.Singletons.Internal`](https://hackage.haskell.org/package/singletons-base-3.1/docs/src/GHC.TypeLits.Singletons.Internal.html).

**Comment by treeowl** [comment]
The question remains: is there any practical use for `HasField` instances with key kinds other than `Symbol`? If not, I think we should just do the `IsString` thing for now; otherwise I'm less confident and would like to consult the community.

**Comment by parsonsmatt** [comment]
Well I guess we could have:

```haskell
instance KnownNat n => HasField n (IntMap a) (Maybe a)
```

But we don't have any fun ways of using that. I don't think I've ever seen a manual `getField @"foobar"` in the wild, and seeing `getField @3 someIntMap` would be pretty wild.

I think it's probably a question of: do we want to support `OverloadedRecordDot` and be cute, or support `HasField` more generally and potentially lose adoption?

Or, heck, is there a way to use `OverloadedRecordDot` with non-`Symbol` types? Do we need a type-level `Read`? :joy:

**Comment by treeowl** [comment]
I've never used any of these extensions, and I haven't even read about overloaded record dot yet, so I have no idea.

**Comment by treeowl** [comment]
Can you explain what you mean by "potentially lose adoption"? I took a glimpse at the documentation for `OverloadedRecordDot`. I don't totally understand it, but from what I've seen I don't immediately see any issues; what problem do you anticipate?

**Comment by sol** [comment]
While neat, I don't think this provides much value + more importantly it
prevents us from adding things that potentially provide more value in the
future.

1.  This occupies the whole namespace, preventing any other instance on `Map`,
    e.g.:

    ```haskell
    instance HasField "toList" (Map k v) [(k, v)] where 
      getField = Map.toList
    ```

1.  Accessing a `Map` with a string key that is known at compile time is
    exceedingly rare.  The very purpose of a `Map` is to store keys that are
    not know at compile time.  If you know your keys at compile time you are
    likely better of using either

    ```haskell
    data Key = Foo | Bar | Baz
    ```

    or a record

    ```haskell
    data MyMap = MyMap {
      foo :: ...
    , bar :: ...
    , baz :: ...
    }
    ```

    Not convinced? Feel free to point me at code some Haskell code that uses a
    string literal to access a `Map` and I'll show you how to refactor that
    code in a way so that is is more concise, easier to understand, more type
    safe and more efficient.

**Comment by sol** [comment]
Instead, how about:

```haskell
instance Ord k => HasField "lookup" (Map k v) (k -> Maybe v) where 
  getField = flip Map.lookup
```

**Comment by parsonsmatt** [comment]
Ok, yeah. As cute d the proposed instance is, it would actually be much nicer to just put the api of Map on the hasfield instances

**Comment by treeowl** [comment]
To ... write Haskell like people write Java? Doesn't sound that nice to me.

**Comment by parsonsmatt** [comment]
It does have some advantages. An expression `m.lookup "hello"` has a general type of `(IsString str, HasField "lookup" s (str -> Maybe a)) => Maybe a`, which means it is actually potentially polymorphic across `Map Text a`, `HashMap Text a`, `KeyMap a`, `[(String, a)]`, etc. All without having to define a common interface that these types must share ahead-of-time, which resolves the question of "where does the class/instances live" somewehat nicely.

It's a moderately principled duck type, and about 80% of what I want from PureScript's row types.
