### ISSUE TITLE
Export Data.Map.trim or a variant

### ISSUE THREAD

**Issue by 3noch** [haskell/containers#834]
`Data.Map`'s unexported utility `trim` function seems exceedingly useful in doing interval-related queries against a `Map`. Is there a reason this has not been exported or converted into a variant that could be exported safely?

**Comment by treeowl** [comment]
That function has been gone for several years now. It was used by the "hedge union" algorithm and friends. Those were replaced by simpler divide-and-conquer algorithms whose performance was (relatively recently) proven to have asymptotically good bounds (unlike the uncharacterized, and likely worse, hedge algorithms), and which also proved to be faster in practice.

`trim` itself has no terribly clean semantics, as far as I can tell. Is there a reason you don't want to just split the map twice?

**Comment by 3noch** [comment]
Oh dear, Hoogle brought me to containers 0.4 and I assumed it was recent. I see now I was looking at very old code!

Splitting the Map twice seems perfectly reasonable, however, instead of a `trim` function.

What I'm really after is N-dimensional interval trees, which would be much easier to implement if I had more of the guts of Map available, but can make-do with copy-paste.

**Comment by treeowl** [comment]
What guts do you need that aren't exposed (now) through the `Internal` module?

**Comment by 3noch** [comment]
Haha, and once again my memory's snapshot of 0.4 has bitten me. Fantastic. Thank you.

**Comment by treeowl** [comment]
Good luck! Would be interested in looking at whatever you make.

**Comment by 3noch** [comment]
Correction: Google brought me to 0.4, not Hoogle. I believe this is a known gotcha with Hackage that I should have been wary of.
