### ISSUE TITLE
Some strictness tests are broken on GHC head

### ISSUE THREAD

**Issue by treeowl** [haskell/containers#853]
@coot, you were the author of `Utils.NoThunks`. Do you think you could you investigate why strict fold tests fail on GHC head?

**Comment by treeowl** [comment]
I don't know how pinging works in GitHub. In case it only works in comments, hey @coot!

**Comment by coot** [comment]
It did work twice :), I'll take a look.

**Comment by treeowl** [comment]
Thanks!

**Comment by sjakobi** [comment]
@treeowl Are you referring to the test failures in the CI jobs with `ghc-9.4.0.20220523`?

That GHC version seems to be a pre-release of GHC 9.4, far from GHC HEAD, and not worth supporting IMHO. I'd suggest to remove that job and to add CI with an official release of GHC 9.4, e.g. 9.4.2.

**Comment by treeowl** [comment]
Ugh. That's what I got telling `haskell-ci` that I wanted head. And I tried to add 9.4, but... it didn't work? I'm not really sure where I went wrong. Should've said 9.4.2, not 9.4.1, but most likely I used a wrong invocation.

**Comment by Bodigrim** [comment]
@treeowl I think you need to build `haskell-ci` from https://github.com/haskell-CI/haskell-ci, the latest Hackage release was in March and it does not know about 9.4 yet.

**Comment by treeowl** [comment]
Thanks, @Bodigrim, I'll give it a go.

**Comment by treeowl** [comment]
OK, I guess this was all just confusion on my part. Sorry!
