### ISSUE TITLE
Add foldMapWithIndex and traverseWithIndex

### ISSUE THREAD

**Issue by treeowl** [haskell/containers#89]
It just seems weird to have `foldrWithIndex` and `foldlWithIndex` but not `foldMapWithIndex` or `traverseWithIndex`. If I figure out the right way to implement the strict folds, I may want indexed versions of those too.

**Comment by m-renaud** [comment]
Data.Sequence now has both `foldMapWithIndex` and `traverseWithIndex`. Can we close this, or was there another container you were referring to?

**Comment by treeowl** [comment]
Thanks for the reminder. I forgot about this. Yeah, I think we can close it. We can defer to packages like `lens` to figure out what an indexed traversal means for `Tree`, and the maps offer `traverseWithKey`.
