### ISSUE TITLE
Provide instance Foldable1 Tree

### ISSUE THREAD

**Issue by Bodigrim** [haskell/containers#906]
With [`Data.Foldable1`](https://ghc.gitlab.haskell.org/ghc/doc/libraries/base-4.18.0.0/Data-Foldable1.html) in `base-4.18` it would be nice for `containers` to provide `instance Foldable1 Tree` as per https://github.com/phadej/foldable1/blob/e4c303568c82945c0451ab9afec32ea5d7d34e49/src/Data/Foldable1.hs#L555-L571. 

CC @phadej

**Comment by treeowl** [comment]
I missed that development. Yes, you're absolutely right.

**Comment by treeowl** [comment]
@meooow25 You were working on similar stuff with the `Foldable` instance recently, IIRC. Would you like to give this one a go?

**Comment by meooow25** [comment]
Sure I can do that, but I don't know how to test this given that it's an unreleased base/GHC.

**Comment by Bodigrim** [comment]
@meooow25 You can install GHC 9.6.0-alpha1 with ghcup, just enable [pre-release channel](https://www.haskell.org/ghcup/guide/#pre-release-channels).

**Comment by treeowl** [comment]
@meooow25 That's a challenge all right. You can do the development work in the `semigroupoids` repository. We may need to coordinate this with those folks anyway. @ekmett , @RyanGlScott .

**Comment by meooow25** [comment]
The ghcup prerelease channel works, thanks!

**Comment by RyanGlScott** [comment]
There are plans to re-export `base`'s `Foldable1` class from `semigroupoids` whenever possible (#130). We can also backport a `Foldable1 Tree1` instance in `semigroupoids` when building with older versions of `base`.

**Comment by treeowl** [comment]
@RyanGlScott There's already a `Foldable1 Tree` instance in `semigroups`. So we should just need to make sure to guard that with an `#if !MIN_VERSION_containers(whatever)`. But I figured @meooow25 would likely have thoughts about optimizing the instance.

**Comment by RyanGlScott** [comment]
Oops, I completely overlooked the fact that `semigroupoids` already defines this instance! (See [here](https://github.com/ekmett/semigroupoids/blob/b9151e725856265717fe462c7abe4e59417ec593/src/Data/Semigroup/Foldable/Class.hs#L212-L214).)

**Comment by phadej** [comment]
> We can also backport a `Foldable1 Tree1` instance in `semigroupoids` when building with older versions of `base`.

It would be better to define instances for boot packages in the shim package, as it's done there: https://github.com/phadej/foldable1/blob/master/src/Data/Foldable1.hs#L551-L600

That said, I have no plans to work on the shim package myself. (I got a bad taste of that proposal, so I'll just stay away).

**Comment by phadej** [comment]
I'd say that it's better to have *some* instance in `containers` bundled with GHC-9.6, than no instance at all.

`foldable1(-classes-compat)` won't be able to add the instance without also introducing some additional module for bunding instances when `Foldable1` is not defined in the package.

**Comment by meooow25** [comment]
@phadej I have a PR implementing it, pending review (see above).

**Comment by phadej** [comment]
@meooow25 :+1:
