### ISSUE TITLE
What code is used to generate the appendTree0 & friends in Data.Sequence.Internal?

### ISSUE THREAD

**Issue by SamuelSchlesinger** [haskell/containers#908]
Just browsing the code to learn and saw
```haskell
-- The appendTree/addDigits gunk below is machine generated
```
in Data.Sequence.Internal. Wondering what code was used to generate that stuff?

**Comment by treeowl** [comment]
You'd have to ask @RossPaterson or [Ralf Hinze](https://pl.cs.uni-kl.de/homepage/en/staff/RalfHinze/). I don't know if that code was preserved somewhere outside the repo.

**Comment by RossPaterson** [comment]
Here it is: [mkappend.hs](https://github.com/haskell/containers/files/10498738/mkappend.txt). This code is 18 years old, and it seems the generated code has had some strictness annotations added to it since,

**Comment by treeowl** [comment]
@RossPaterson , yes, the amortization analysis lets us force the spines, and doing so seems quite beneficial for that operation.

**Comment by treeowl** [comment]
@RossPaterson And thanks!

**Comment by RossPaterson** [comment]
@treeowl Have you done an amortization analysis? I see you consistently force the new middle tree in the `Deep`-`Deep` case of `appendTree`. You also force the collected nodes between the trees in some cases of `appendTree` and `addDigits`, but I couldn't see a consistent pattern to it.

**Comment by treeowl** [comment]
@RossPaterson A fixed number of debits are allowed on each `Deep` node, and none elsewhere, so we're allowed to force along the spine as deep as the shallower tree, which is what we do (unless I made a mistake somewhere). The question of exactly how far off to force was guided by benchmarks; I think it's a matter of the cost of thunk creation vs. other calculation. If you think I've made a mistake somewhere, or could do better, *please* let me know.

**Comment by SamuelSchlesinger** [comment]
Thanks much.

**Comment by treeowl** [comment]
I think we should add the code to the repo for historical reference and so people can learn from it.

**Comment by treeowl** [comment]
@RossPaterson Are you satisfied that I haven't broken the amortized bounds? This conversation got stuck in the back of my mind.
