### ISSUE TITLE
CONTRIBUTING.md references `cabal sandbox`

### ISSUE THREAD

**Issue by mixphix** [haskell/containers#914]
I tried to follow the instructions on how to build and test this library, but [Cabal sandboxes no longer exist](https://github.com/haskell/cabal/issues/6445#issuecomment-629146662) on newer versions. What is the recommended way to do this today?

**Comment by treeowl** [comment]
It's clearly time for an update. And I need to un-break `cabal repl`. Things are mostly fairly normal. `cabal build` and `cabal test` and `cabal bench`. Are you running into issues?

**Comment by mixphix** [comment]
Just that I have to go into the respective subdirectories instead of running them at the top-level. Thanks!

**Comment by treeowl** [comment]
Oops, my mind slipped. You can (and generally should) do it from the top: `cabal build containers`, but `cabal test containers-tests` and `cabal bench containers-tests`. You're totally right that `CONTRIBUTING` needs fixing....
