### ISSUE TITLE
Build of container-test fails with cabal

### ISSUE THREAD

**Issue by autonym8** [haskell/containers#940]
Hello again !

So I just tried to compile ```containers-test``` via cabal and I ran into some other issue.

Compilation starts (which is an improvement compared with my previous attempt with stack) and eventually fails with 

``` 
cabal-3.6.2.0.exe: can't find source for Data\Containers\ListUtils in src,
tests,
E:\Documents\...\containers\dist-newstyle\build\x86_64-windows\ghc-9.2.5\containers-tests-0\build\autogen,
E:\Documents\....\containers\dist-newstyle\build\x86_64-windows\ghc-9.2.5\containers-tests-0\build\global-autogen
```

** Steps to reproduce : **
1. Uncomment the last two lines of ```cabal.project``` : 
```
package containers-tests
   ghc-options: -Werror
 ```
2. Run ```cabal test containers-tests```

As with stacks, compiling ```containers```, with the two lines above commented, works fine though.

Cheers !

**Comment by treeowl** [comment]
Alternatively (better?) you could copy that once, do whatever you need to do within the `containers-tests` directory, then copy it back before you commit. We use symbolic links to replicate the source of `containers` in `containers-tests`. That lets us uncomment the `containers` package from `cabal.project` to avoid recompiling all the test and benchmark framework stuff while iterating on changes. There may be a better way, but I'm not good at this sort of devops stuff and that's what @phadej was able to figure out.

**Comment by autonym8** [comment]
Yes, that was it ! I have managed to compile and run the tests, thanks a lot for your help !

**Comment by autonym8** [comment]
I closed the issue because this would be a duplicate of https://github.com/haskell/containers/issues/630#issue-435892433

**Comment by autonym8** [comment]
Sure, I'll do that tomorrow, I need some sleep first :)

**Comment by autonym8** [comment]
I added a pull request with some instructions. Actually it is possible on windows to use symlinks, so there's no need for the workaround you suggested before except for Windows 8 or earlier. This should also close https://github.com/haskell/containers/issues/630
