### ISSUE TITLE
Tree fusion

### ISSUE THREAD

**Issue by meooow25** [haskell/containers#947]
I found myself doing this a few times, creating a tree and immediately folding over it.  
But we don't have any fusion rules for `Tree a` that would avoid constructing the intermediate tree. So, let's add some?

We can have `unfoldTree`, `fmapTree` and `foldTree` participate in the fusion.

There is a question of which fold to base it on since a `buildTree` would need to match it. I would like `foldTree2` from #946, but I think we could also do with the current `foldTree`.

**Comment by treeowl** [comment]
It doesn't have to be just one or the other.

**Comment by meooow25** [comment]
What I mean is that we need to choose between
```hs
buildTree :: forall a. (forall b. (a -> [b] -> b) -> b) -> Tree a
buildTree g = g Node

-- foldTree f (buildTree g) = g f
```
and
```hs
buildTree :: forall a. (forall b c. (a -> b -> c) -> (c -> b -> b) -> b -> c) -> Tree a
buildTree g = g Node (:) []

-- foldTree2 f c n (buildTree g) = g f c n
```

Or am I missing something?

**Comment by treeowl** [comment]
Hmmm .... Good point. The latter does seem more promising....

**Comment by meooow25** [comment]
So does this seem like a good idea? 😃
I could try putting together a PR.

**Comment by treeowl** [comment]
We'll have to see how well it actually works out with some examples.

**Comment by meooow25** [comment]
Alright, here's the same example from #946.

```hs
{-# LANGUAGE RankNTypes #-}
import Data.List
import Data.Tree (Tree(..))
import Test.Tasty.Bench

main :: IO ()
main = defaultMain
    [ bench "nofusion" $ whnf (depthSum_rec . binTree) 2000000
    , bench "fusion" $ whnf (depthSum_foldTree2 . binTreeAlt) 2000000
    ]

binTree :: Int -> Tree Int
binTree n = unfoldTree (\x -> (x, takeWhile (<n) [2*x + 1, 2*x + 2])) 1

depthSum_rec :: Tree a -> Int
depthSum_rec t = go t 0 0 where
    go (Node _ ts) depth acc = foldl' (\acc' t' -> go t' (depth+1) acc') (acc + depth) ts

binTreeAlt :: Int -> Tree Int
binTreeAlt n = unfoldTreeAlt (\x -> (x, takeWhile (<n) [2*x + 1, 2*x + 2])) 1

depthSum_foldTree2 :: Tree a -> Int
depthSum_foldTree2 t = foldTree2 f f' (const id) t 0 0 where
    f _ k depth acc = k depth (acc + depth)
    f' k1 k2 depth acc = k2 depth (k1 (depth+1) acc)

----------

unfoldTree :: (b -> (a, [b])) -> b -> Tree a
unfoldTree f = go where
    go b = case f b of (a, bs) -> Node a (map go bs)

unfoldTreeAlt :: (b -> (a, [b])) -> b -> Tree a
unfoldTreeAlt f b0 = buildTree $ \node c n ->
    let go b = case f b of (a, bs) -> node a (foldr (c . go) n bs)
    in go b0

buildTree :: forall a. (forall b c. (a -> b -> c) -> (c -> b -> b) -> b -> c) -> Tree a
buildTree g = g Node (:) []
{-# INLINE [1] buildTree #-}

foldTree2 :: (a -> b -> c) -> (c -> b -> b) -> b -> Tree a -> c
foldTree2 f c z = go where go (Node x ts) = f x (foldr (c . go) z ts)
{-# INLINE [1] foldTree2 #-}

{-# RULES
"foldTree2/buildTree"
    forall f c n (g :: forall b c. (a -> b -> c) -> (c -> b -> b) -> b -> c) .
        foldTree2 f c n (buildTree g) = g f c n
  #-}
```

```
  nofusion: OK (0.21s)
    30.2 ms ± 2.2 ms
  fusion:   OK (0.14s)
    1.11 ms ±  89 μs
```

**Comment by treeowl** [comment]
Which operations would be changed? Maps, depth-first folds, and depth-first unfolds, I assume?

**Comment by meooow25** [comment]
I think so? Not sure which functions you mean exactly. We should be able to make this work with `unfoldTree`, `fmap`, `foldTree`, `foldr`, `foldl'`, `foldMap` at least.

**Comment by treeowl** [comment]
I'm concerned about a couple things.

1. As I vaguely recall, tree-shaped fusion has some problems in general, where sometimes the concrete structure will fuse away but leave behind something worse. I don't know details.
2. This is the one thing in `containers` that's still pretty approachable to rank beginners. How bad is it to monkey with that?

I'm not saying no; I'm saying I'm a bit concerned.

**Comment by meooow25** [comment]
1. If so we should definitely be concerned. Do you remember the source for this? I'll try to find out more about this regardless.
2. Not sure I follow this line of reasoning. It would be different if `containers` was primarily an instructional library.

**Comment by treeowl** [comment]
1. This info might be in the original "short cut to deforestation" paper.
2. Like I said, not a killer, but I'm a bit concerned about my own role in making the library less approachable. 😕

**Comment by meooow25** [comment]
I'm unable to find any information on issues with shortcut fusion for trees. Here's what I checked:

[A short cut to deforestation](http://doi.acm.org/10.1145/165180.165214) doesn't talk about anything other than lists.

[Stream fusion: practical shortcut fusion for coinductive sequence types](https://ora.ox.ac.uk/objects/uuid:b4971f57-2b94-4fdf-a5c0-98d6935a44da) is mostly about stream fusion, but mentions at one point (section 1.3.3)
> This approach is named shortcut deforestation or shortcut fusion. Shortcut fusion has primarily been applied to eliminate lists as intermediate data structures, though approaches exist to tackle trees and arrays.

[A Library Writer's Guide to Shortcut Fusion](https://www.cs.ox.ac.uk/publications/publication5396-abstract.html) implements shortcut fusion for binary trees and has some benchmarks.

[Monadic augment and generalised short cut fusion](https://www.cambridge.org/core/journals/journal-of-functional-programming/article/monadic-augment-and-generalised-short-cut-fusion/B9F2ABDD010E6521AC500CE66BA14FA9) decribes shortcut fusion for rose trees using the `(forall b. (a -> [b] -> b) -> b)` form, but they don't benchmark it.

**Comment by meooow25** [comment]
I was also curious if this could be useful for something like GHC, and I found one instance in [GHC.CmmToAsm.CFG](https://gitlab.haskell.org/ghc/ghc/-/blob/00a8a5ff9abf5bb1a0c2a9225c7bca5ec3bdf306/compiler/GHC/CmmToAsm/CFG.hs#L855-859). This has an unfold -> fmap -> fold. Now I don't know how important this is for GHC (probably not much because the fold is done inefficiently and they haven't improved it), but this shows that code in the wild can benefit from it.

**Comment by treeowl** [comment]
Go ahead and give it a shot!

**Comment by meooow25** [comment]
Hi, I got a little busy with other things so it has been a while, but I'll update on what I've done with this.

### Attempt with `foldTree2`

I implemented fusion using `buildTree` and `foldTree2`, mirroring what GHC does for lists. And I could make `unfoldTree`, `fmapTree`, `traverse`, `foldr`, `foldl'` work with fusion as expected.

But there was a problem function, `foldTree`.

```hs
foldTree :: (a -> [b] -> b) -> Tree a -> b
foldTree f = go where
    go (Node x ts) = f x (map go ts)
```

Now
```hs
foldTree2 :: (a -> b -> c) -> (c -> b -> b) -> b -> Tree a -> c
foldTree2 f c n = go where
    go (Node x ts) = f x (foldr (c . go) n ts)
```


So it seems obvious to change `foldTree` to

```hs
foldTree :: (a -> [b] -> b) -> Tree a -> b
foldTree f = foldTree2 f (:) []
```

But suppose we want to do something like `foldTree (\x ys -> x + sum ys)`. With the old definition, `sum` will fuse with `map` to optimize nicely, but with the new one, `sum` cannot fuse with `foldr` and the list `[b]` will be created!

This was disappointing to run into, so to avoid this I thought I would try fusion with `foldTree` instead of `foldTree2`.

### Attempt with `foldTree`

The problem right at the start is that `foldTree` does not optimize well (#946). Luckily I found a particular way of using it which optimized well in the cases I tried. So I asked about it on the GHC issue ([#23319](https://gitlab.haskell.org/ghc/ghc/-/issues/23319#note_497151)), but I got the response that this is not reliable :(  
So this does not seem like a good route, but let's proceed anyway.

Soon I ran into another problem. Consider `foldr` via `foldTree`:

```hs
foldr :: (a -> b -> b) -> b -> Tree a -> b
foldr f z0 = \t -> foldTree (\x ks -> f x . foldr (.) id ks) t z0
```

It is important that `foldr` here fuse with the `map` inside `foldTree`. But that is impossible if we mirror the list fusion phase control! What we need is for tree fusion to finish before list fusion starts.

Since the `map` to `mapFB` rules fires upto phase 2, we should ideally be done before that. That leaves us with phase 4 and 3 to work with (according to [this blog](https://markkarpov.com/tutorial/ghc-optimization-and-fusion.html#the-phase-control)). At this point I decided it was getting too hairy and did not pursue it further.

### So what does it mean

My conclusion is that have two good options:
1. Do nothing
2. Implement fusion with `foldTree2`, but leave out `foldTree` because we cannot be making it worse for normal usage.

Without `foldTree`, the appeal for fusion is a little less, but I still think it can useful because other functions such as `fmapTree`, `traverse`, `foldr`, `foldl'` and anything defined in terms of those will benefit. And of course, if we decide to expose `foldTree2`, that will also participate in fusion.

What do you think? And in case I'm missing a way to solve the `foldTree` problem I'd be happy to hear about it.

**Comment by meooow25** [comment]
Closing since I have no current plans to work on this. My enthusiasm for this lessened after discovering that due to interference with list fusion, `foldTree` would be left out of the tree fusion functions. I'm open to working on this or helping out if there is more interest in having this in the library.
