### ISSUE TITLE
NonEmpty for CyclicSCC

### ISSUE THREAD

**Issue by Bodigrim** [haskell/containers#952]
https://github.com/haskell/containers/blob/48196fba49386a228939824066f2215f933ce302/containers/src/Data/Graph.hs#L146-L149

How about changing this to `CyclicSCC (NonEmpty vertex)`? This could shave a number of unsafe `Data.List.head` in GHC and other compilers. 

Not sure about backward compatibility / migration schedule, probably a pattern synonym can help to ease the breakage.

**Comment by treeowl** [comment]
Yes, let's do something of this sort. Your second representation doesn't seem to distinguish properly between vertices with no edges and ones with a single edge to themselves.

```haskell
import Data.Graph

main :: IO ()
main =  do
  print $ stronglyConnComp [((), (), [()])]
  print $ stronglyConnComp [((), (), [])]
```

This gives

```
[CyclicSCC [()]]
[AcyclicSCC ()]
```

As I understand it, your `SCC` would represent these two the same.

**Comment by treeowl** [comment]
I must admit to some trepidation about committing to `NonEmpty` given the current lack of a plan for improving its laziness story. If we do use it, I imagine it should be strict and unpacked.

**Comment by treeowl** [comment]
I meant if you want `NonEmpty` it should probably be `{-# UNPACK #-} !(NonEmpty vertex)`. But unpacking by hand wouldn't be unreasonable either.

**Comment by treeowl** [comment]
I'd like to see how this affects the code, yeah.

**Comment by meooow25** [comment]
Can we maybe skip introducing the partial `CyclicSCC` -> `CyclicSCC'` pattern? It's unlikely someone would be making their own `SCC`s. And even with the pattern it's a breaking change if they do `CyclicSCC []`.

**Comment by treeowl** [comment]
@meooow25 , we can just make it unidirectional, right?

**Comment by meooow25** [comment]
Yes, that's what I meant, should have stated explicitly.  
Also this is only a suggestion, it comes down to whether we really don't want to break some code out there that is constructing `CyclicSCC`s and always with non-empty lists.
