### ISSUE TITLE
feat request: Add `popLeftWithValue` and `popWithValue` in `Data.Sequence`

### ISSUE THREAD

**Issue by sanao1006** [haskell/containers#977]
## Proposal
I think it would be useful to have a function in `Data.Sequence` that deletes the edge value and at the same time retrieves the rest of the Sequence without the edge value.

The naming is tentative, but the function is as follows
```haskell
-- Return `Nothing` if EmptyL
popLeftWithValue :: Seq a -> Maybe(a, Seq a)

-- Return `Nothing` if EmptyR
popWithValue :: Seq a -> Maybe(Seq a, a)
```

Also, functions like `head`, `tail`, `last`, and `init` using Maybe monad would surely be useful to add to `Data.Sequence`.

What do you think?

**Comment by sanao1006** [comment]
Please allow me to confirm the meaning of your statement. (Sorry, I'm not very good at English...)
- You said that "As long as we have Views, we don't need to bother adding those functions".
- You said that "Explain your approach to implementing the proposed function."
Which is it?

**Comment by meooow25** [comment]
> The naming is tentative...

I have seen these two be commonly called `uncons` and `unsnoc` in Haskell libraries.

> I think it would be useful to have a function in Data.Sequence that deletes the edge value and at the same time retrieves the rest of the Sequence without the edge value.

There are already two ways to do this:
* `viewl` and `viewr` (as jwaldmann has said)
* The patterns `Empty`, `:<|` and `Empty`, `:|>`

But I can see the utility in adding these for `Sequence` for 1. consistency (with other Haskell structures that define `uncons` and `unsnoc`) and 2. convenience of working with the result (for instance, we could say `safeLast = fmap snd . unsnoc`).

**Comment by sanao1006** [comment]
> There are already two ways to do this:

Yes, you are right. I think it is possible to implement both `unsnoc` and `uncons` by using `viewl` and `viewr`.

I would be inclined to create a PR if only the maintainer would allow me to do so.
